### ISSUE TITLE
Backend delete job is running for hours

### ISSUE THREAD

**Issue by batical** [aws-amplify/amplify-console#1722] opened 2021-04-03 07:33 UTC
### Before opening, please confirm:

I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

Deleting a back end env is running for hours without doing anything

Cannot update stack etc

A job is running 
"Jobs": [
        {
            "AppId": "*****",
            "BackendEnvironmentName": "dev",
            "CreateTime": "1617375907613",
            "JobId": "********",
            "Operation": "DeleteBackend",
            "Status": "RUNNING",
            "UpdateTime": "1617375915764"
        }
    ]
I have the blue line in the ui deleting backend env, sometime it disappear but always come back
### Expected behavior

Deleting the stack
At least, Is there a way to cancel this job. I don't really care about deleting it TBH

### Reproduction steps

Hit the button delete on aws console

**Comment by siegerts** [comment] 2021-04-07 14:13
Hi @batical, thanks for raising! Closing as this seems to be a duplicate of https://github.com/aws-amplify/amplify-console/issues/1642.

**Closed by siegerts** 2021-04-07 14:13 UTC
