### ISSUE TITLE
Console error reading inputParams googleClientId, facebookAppId

### ISSUE THREAD

**Issue by dahersoftware** [aws-amplify/amplify-console#300] opened 2019-11-25 18:04 UTC
I encounter this problem quite frequently(Until now I used to delete my app), I am using prod environment.
It is working fine from my local machine and I don't understand why I get "getting stack from env cache" line even though I am reseting my environment cache.

2019-11-25T16:28:56.016Z [INFO]: # Executing command: amplifyPush --environment prod
2019-11-25T16:28:56.020Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-11-25T16:28:56.026Z [INFO]: # Start initializing Amplify environment: prod
2019-11-25T16:28:56.028Z [INFO]: # Initializing new Amplify environment: prod (amplify init)
2019-11-25T16:29:16.860Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-11-25T16:29:21.331Z [WARNING]: - Initializing your environment: prod
2019-11-25T16:29:21.786Z [WARNING]: ✔ Initialized provider successfully.
2019-11-25T16:29:21.832Z [WARNING]: ✖ There was an error initializing your environment.
2019-11-25T16:29:21.833Z [INFO]: init failed
2019-11-25T16:29:21.834Z [INFO]: Error: auth headless init is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
at updateConfigOnEnvInit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:315:15)
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:241:28
at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-25T16:29:21.908Z [ERROR]: !!! Build failed
2019-11-25T16:29:21.909Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-25T16:29:21.909Z [INFO]: # Starting environment caching...
2019-11-25T16:29:21.909Z [INFO]: # Environment caching completed

My backend build file
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - 'cd packages/backend/'
        - echo "printing dir"
        - pwd
    build:
      commands:
        - echo "printing dir"
        - pwd
        - '# Execute Amplify CLI with the helper script'
        - envCache --set stackInfo ""
        - amplifyPush --environment prod --simple 
      commands:
        - 'cd ../../'

**Comment by kahdojay** [comment] 2019-12-10 19:27
@kevin-mitchell we have a known issue that we're working on resolving. In the meantime have you tried the workaround described here? https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-552548466

Let me know if this doesn't work for you. Also please scrub your comments to remove your googleClientId creds and rotate that key since this is a public forum.

**Comment by kevin-mitchell** [comment] 2019-12-10 20:35
@kahdojay I _have_ seen the workaround, to be honest part of the reason I've held off is because it wasn't clear to me if the issue was caused by something I was doing incorrectly, vs an actual known issue. It sounds pretty clear that in fact this is a "real" issue.

I will try to give the workaround a shot. Part of the reason I didn't just jump right in is because I wasn't entirely sure about which parts of the "workaround" needed to be edited. For example

```
AUTHCONFIG="{\
\"facebookAppIdUserPool\":\"888888888888888\",\
\"facebookAppSecretUserPool\":\"88888888888888888\"\
}"
```

Is that a "insert your credential here" thing? If so, how would I specify different environments for example? To somebody who really knows what they are doing this might be obvious, but for me it's unclear. 

BTW, those credentials should have already been scrubbed :) - I scrubbed them before posting!

**Comment by kahdojay** [comment] 2019-12-10 21:27
@kevin-mitchell Ah ok, apologies I didn't look closely enough at the secret value. That is indeed an insert-your-credentials area. One idea might be to leverage the AWS_BRANCH environment variable provided by Amplify: https://docs.aws.amazon.com/amplify/latest/userguide/environment-variables.html#amplify-console-environment-variables

(since this is a workaround we don't have a formal recommendation around this, we're trying to focus on fixing the underlying problem).

**Comment by kevin-mitchell** [comment] 2019-12-11 11:17
@kahdojay thank you so much for taking the time to reply to my questions and the ticket / issue. I'll take a look and likely give the workaround a shot.

That said, I'm sure you don't have a timeline for this, but can you give any insight into if this is something that is actively being looked at vs being deep in the backlog? A big part of the reason I went with Amplify vs "roll your own" stack is because it's turnkey, and (as lazy as this sounds) using Amplify allowed me to be ignorant about certain portions of my application / infrastructure. If this was going to be fixed in the next few weeks or even months I might just ignore the problem for now, and give the auto-deployment feature another shot in a few weeks / months.

Finally, I'm assuming #206 is the best place to track this issue? Or is there another ticket that I should watch?

Thanks again!

**Comment by swaminator** [comment] 2019-12-11 20:29
@kevin-mitchell This is something that is at the top of our backlog and we are actively working on.

**Closed** 2019-12-11 20:31 UTC

**Comment by aleksei-tro** [comment] 2020-08-28 04:45
I just had the same issue and I found a neat solution
modify your amplify.yml and add
`- amplifyPush -e $AWS_BRANCH --simple`
after `npm ci`
