### ISSUE TITLE
Access Denied - This XML file does not appear to have any style information associated with it. The document tree is shown below.

### ISSUE THREAD

**Issue by jaivinodha** [aws-amplify/amplify-console#954] opened 2020-08-11 09:32 UTC
**Issue/question**
amplify hosting add -> Hosting with Amplify Console ->Github-> connecting to Github -> successfully Deploying . But im getting Access Denied error with the master branch.

**Error message**
![image](https://user-images.githubusercontent.com/69211611/89880048-62cdcb00-dbe1-11ea-94d3-79eb3454e9fe.png)
![image](https://user-images.githubusercontent.com/69211611/89880065-682b1580-dbe1-11ea-9552-ee9d60e175fc.png)
![image](https://user-images.githubusercontent.com/69211611/89880081-6e20f680-dbe1-11ea-8028-4c7d296f72dc.png)

**Additional information**
1) Create a React App -> npm install -g @aws-amplify/cli . Set up Regions and IAM with Administrator Access
2) Amplify init -> Project name -> VS code -> Vs -> setup the project
3) npm install aws-amplify aws-amplify-react -> Dev -> Continuous hosting with Hosting Console -> Connect a repo of Github -> Save and Deploy -> Successful Deploy ->  Master branch Build link gives Access Denied error

I have google everything , gone through all the issues in github & tried and added all the configurations.Nothing worked . Literally Fedup

**Comment by swaminator** [comment] 2020-08-11 17:00
Dupe of #955

**Closed by swaminator** 2020-08-11 17:00 UTC
