### ISSUE TITLE
Amplify CI/CD just for backend repo.

### ISSUE THREAD

**Issue by GeekRishabh** [aws-amplify/amplify-console#2166] opened 2021-08-16 12:04 UTC
How can one add ci/cd to their repository which has just the backend code in it?

I am using bitbucket/GitHub for amplify repo. I don't have graphql schema with this repo

**YML build file I am  using**

`version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.8 11
        - /usr/local/bin/pip3.8 install --user pipenv
        - npm -v
        - node -v
        - nvm install 14
        - nvm use 14
        - npm -v
        - node -v
        - npm i -g @aws-amplify/cli
    build:
      commands:
        - amplify status
        - amplifyPush --Simple
frontend:
  phases:
    preBuild:
      commands:
        - export NODE_OPTIONS=--max-old-space-size=8500
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: build
    files:
      - "**/*"`

I have added a dummy react project to be built and also have enabled fully CI/CD from Amplify console service.
Just to add I have Lambda written i node & python both

**AWS Services I am utilizing?**

I am using AWS amplify along with the the resources like (API, Queue, S3 & Lambda)
<img width="83" alt="Screenshot 2021-08-16 at 5 30 39 PM" src="https://user-images.githubusercontent.com/23093075/129560461-0422e366-566c-480a-bcf0-7467b8a4ff81.png">

**Comment by behrooziAWS** [comment] 2021-08-16 22:39
Is this a duplicate of https://github.com/aws-amplify/amplify-cli/issues/1773?

**Comment by hloriana** [comment] 2021-12-03 21:52
Closing since this is a duplicate of the feature request mentioned above.

**Closed by hloriana** 2021-12-03 21:52 UTC
Labels: duplicate, pending-customer-response
