### ISSUE TITLE
Next.js SSR Build Error

### ISSUE THREAD

**Issue by lindsaybloomsonos** [aws-amplify/amplify-console#2406] opened 2021-11-16 22:57 UTC
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

Next.js

### Amplify APIs

Not applicable

### Amplify Categories

Not applicable

### Environment information

<details>

```
  System:
    OS: macOS 11.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 5.39 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.2 - ~/*****
  Browsers:
    Chrome: 96.0.4664.45
    Firefox: 94.0.1
    Safari: 14.1.2
  npmPackages:
    @ampproject/toolbox-optimizer:  undefined ()
    @babel/core: ^7.14.5 => undefined (7.15.8, 7.12.9, )
    @hookform/devtools: ^4.0.1 => 4.0.1 
    @lhci/cli: ^0.8.0 => 0.8.2 
    @loadable/babel-plugin: ^5.13.2 => 5.13.2 
    @loadable/webpack-plugin: ^5.15.1 => 5.15.1 
    @next/bundle-analyzer: ^11.1.0 => 11.1.2 
    @noshot/env: ^2.1.1 => 2.1.1 
    @preact/compat: 17.0.2 => 17.0.2 
    @storybook/addon-actions: ^6.4.0-beta.22 => 6.4.0-beta.22 
    @storybook/addon-essentials: ^6.4.0-beta.22 => 6.4.0-beta.22 
    @storybook/addon-links: ^6.4.0-beta.22 => 6.4.0-beta.22 
    @storybook/builder-webpack5: ^6.4.0-beta.22 => 6.4.0-beta.22 
    @storybook/manager-webpack5: ^6.4.0-beta.22 => 6.4.0-beta.22 
    @storybook/react: ^6.4.0-beta.22 => 6.4.0-beta.22 
    @testing-library/jest-dom: ^5.14.1 => 5.14.1 
    @testing-library/preact: ^2.0.1 => 2.0.1 
    @types/cookie: ^0.4.1 => 0.4.1 (0.3.3)
    @types/html-minifier-terser: ^5.1.2 => 5.1.2 (6.0.0)
    @types/node: ^16.0.1 => 16.11.6 (10.17.60, 14.17.32)
    @types/react: ^17.0.14 => 17.0.33 
    @types/react-dom: ^17.0.9 => 17.0.10 
    @types/set-cookie-parser: ^2.4.1 => 2.4.1 
    @types/shelljs: ^0.8.9 => 0.8.9 
    @types/use-persisted-state: ^0.3.0 => 0.3.0 
    @vanilla-extract/babel-plugin: ^1.1.2 => 1.1.2 
    @vanilla-extract/css: ^1.6.3 => 1.6.3 
    @vanilla-extract/css-utils: ^0.1.1 => 0.1.1 
    @vanilla-extract/next-plugin: ^1.0.1 => 1.0.1 
    @vanilla-extract/sprinkles: ^1.3.1 => 1.3.1 
    @vanilla-extract/webpack-plugin: ^2.1.0 => 2.1.0 
    @vercel/nft:  undefined ()
    amphtml-validator:  undefined ()
    arg:  undefined ()
    async-retry:  undefined ()
    async-sema:  undefined ()
    aws-cdk: ^1.111.0 => 1.129.0 
    aws-sdk: ^2.997.0 => 2.1017.0 
    babel-loader: ^8.2.2 => 8.2.3 
    bfj:  undefined ()
    cacache:  undefined ()
    ci-info:  undefined ()
    classnames: ^2.3.1 => 2.3.1 (2.2.6)
    cli-select:  undefined ()
    comment-json:  undefined ()
    compression:  undefined ()
    conf:  undefined ()
    constructs: ^3.3.138 => 3.3.161 
    content-type:  undefined ()
    cookie: ^0.4.1 => undefined (0.4.1, 0.4.0, , 0.3.1)
    critters: ^0.0.10 => 0.0.10 
    cross-env: ^7.0.3 => 7.0.3 
    cross-spawn:  undefined ()
    css-loader: ^6.2.0 => undefined (3.6.0, 5.2.7, 6.5.0, )
    csstype: ^3.0.9 => 3.0.9 (2.6.18)
    debug:  undefined ()
    devalue:  undefined ()
    dotenv: ^10.0.0 => 10.0.0 (8.6.0, 8.2.0)
    downshift: ^6.1.7 => 6.1.7 
    esbuild: ^0.12.24 => 0.12.29 (0.13.10, 0.11.23)
    escape-string-regexp:  undefined ()
    eslint-plugin-prettier: * => 4.0.0 (3.4.1)
    file-loader:  undefined ()
    find-cache-dir:  undefined ()
    find-up:  undefined ()
    framer-motion: ^5.0.0 => 5.0.0 
    fresh:  undefined ()
    glob:  undefined ()
    goober: ^2.0.41 => 2.0.41 
    goober-autoprefixer:  1.2.1 
    goober-global:  0.0.1 
    goober-should-forward-prop:  0.0.1 
    goober.macro:  1.0.0 
    graphql: ^15.5.1 => 15.7.2 
    graphql-hooks: ^5.4.0 => 5.4.1 
    graphql-request: ^3.5.0 => 3.6.1 
    gzip-size:  undefined ()
    html-minifier-terser: ^5.1.1 => 5.1.1 (6.0.2)
    http-proxy:  undefined ()
    husky: ^6.0.0 => 6.0.0 
    ignore-loader:  undefined ()
    is-animated:  undefined ()
    is-docker:  undefined ()
    is-wsl:  undefined ()
    json5:  undefined ()
    jsonwebtoken:  undefined ()
    jsx-runtime:  1.0.0 
    loader-utils:  undefined ()
    lodash.curry:  undefined ()
    lru-cache:  undefined ()
    mini-css-extract-plugin: ^2.4.3 => undefined (2.4.3, )
    monocdk: ^1.120.0 => 1.129.0 
    msw: ^0.35.0 => 0.35.0 
    msw-storybook-addon: ^1.4.1 => 1.4.1 
    nanoid:  undefined ()
    neo-async:  undefined ()
    next: ^11.1.2 => 11.1.2 
    next-cookie: ^2.8.0 => 2.8.0 
    next-plugin-preact: 3.0.6 => 3.0.6 
    next-sanity: ^0.3.0 => 0.3.0 
    next-sanity-image: 3.1.5 => 3.1.5 
    ora:  undefined ()
    postcss-flexbugs-fixes:  undefined ()
    postcss-loader:  undefined ()
    postcss-preset-env:  undefined ()
    postcss-scss:  undefined ()
    preact: 10.5.15 => 10.5.15 
    preact-compat:  4.0.0 
    preact-debug:  1.0.0 
    preact-devtools:  1.0.0 
    preact-hooks:  0.1.0 
    preact-render-to-string: 5.1.19 => 5.1.19 
    preact-ssr-prepass: 1.2.0 => 1.2.0 
    react: npm:@preact/compat@17.0.2 => undefined (17.0.1)
    react-fast-compare: ^3.2.0 => 3.2.0 
    react-hook-form: ^7.12.2 => 7.18.0 
    react-intersection-observer: ^8.32.1 => 8.32.2 
    react-placeholder: ^4.1.0 => 4.1.0 
    react-use-cookie: ^1.2.1 => 1.2.1 
    recast:  undefined ()
    resolve-url-loader:  undefined ()
    sass-loader:  undefined ()
    schema-utils:  undefined ()
    semver:  undefined ()
    send:  undefined ()
    set-cookie-parser: ^2.4.8 => 2.4.8 
    shelljs: ^0.8.4 => 0.8.4 
    source-map:  undefined ()
    storybook-addon-next-router: ^3.0.8 => 3.0.8 
    string-hash:  undefined ()
    strip-ansi:  undefined ()
    terser:  undefined ()
    test-utils:  0.1.0 
    text-table:  undefined ()
    ts-node: ^10.0.0 => 10.4.0 
    tsconfig-paths-webpack-plugin: ^3.5.1 => 3.5.1 
    typescript: ^4.3.5 => 4.4.4 
    unistore:  undefined ()
    use-debounce: ^7.0.0 => 7.0.0 
    use-persisted-state: ^0.3.3 => 0.3.3 
    web-vitals:  undefined ()
    webpack: ^5.60.0 => 5.60.0 (4.46.0, )
    webpack-sources:  undefined ()
    zen-observable:  undefined ()
  npmGlobalPackages:
    @sanity/cli: 1.149.9
    aws-cdk: 1.132.0
    dw-cli: 2.1.1
    gatsby-cli: 2.12.7
    n: 6.7.0
    npm: 7.15.1
    serverless: 1.67.1
    typescript: 3.6.4
    yarn: 1.22.10

```

</details>

### Describe the bug

```
Starting SSR Build...
2021-11-16T22:10:34.047Z [ERROR]: Error: pages-manifest not found. Check if `next.config.js` target is set to ''
                                  at CLI.renderError (/root/.npm/_npx/1415/lib/node_modules/@sls-next/-patched/node_modules/@/cli/src/Context.js:325:15)
                                  at Object.runComponents (/root/.npm/_npx/1415/lib/node_modules/@sls-next/-patched/node_modules/@/cli/src/index.js:237:13)
                                  at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

I started seeing this error suddenly without any code changes when deploying my Next.js app. I am able to reproduce this error in multiple Amplify environments without any code changes since the last successful build and deployment.

### Expected behavior

The build is expected to succeed and continue with the `postBuild` steps as follows:

```
2021-11-16T15:37:24.222Z [INFO]: Starting SSR Build...
2021-11-16T15:45:42.200Z [INFO]: SSR Build Complete.
2021-11-16T15:45:43.561Z [INFO]: # Completed phase: build
                                 # Starting phase: postBuild
```

### Reproduction steps

1. Create a Next.js app with a `next.config.ts` (use `.ts` extension) 
2. Connect yourr Next.js app in a Github repository to deploy on merges to a branch
3. Merge code into that branch
4. Watch the build logs for the Amplify deployment
5. See if the build step succeeds

### Log output

<details>

```
// Put your logs below this line


```

</details>

### Additional configuration

Build Settings:
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
    postBuild:
      commands:
        - yarn update:cookies --dist-id-key=$COOKIE_OVERRIDE_BRANCH
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
```

**Comment by hloriana** [comment] 2021-11-23 17:42
The team is working on a fix for this. Closing as duplicate of #2387

**Closed by hloriana** 2021-11-23 17:42 UTC
Labels: ssr, transferred
