### ISSUE TITLE
Amplify build fails with "NoSuchBucket" for environment that was removed and added

### ISSUE THREAD

**Issue by apanagos** [aws-amplify/amplify-console#293] opened 2019-12-05 22:22 UTC
**Describe the bug**
We were having problems with one of our build environments so we removed it. I went through and made sure that any remaining resources were deleted. For instance there were some CloudFormation stacks left with errors. I deleted those. So nothing left in S3, IAM, Lambda, and disconnected Ampify build. Created environment again and pushed successfully. Checked in code and then added source connection to environment back to Amplify console. But build fails 

**To Reproduce**
Amplify v4.5.0  (first time I did these steps I was on v3.17.0 hoping upgrading may help)

1. amplify env remove buildedge
2. Check to see if any resources were left around. IAM roles, S3 buckets, Lambda functions, CloudFormation Stacks, Amplify console build connection. I removed the connection to buildedge from the source branch. I didn't disconnect the other env from the App as they work.
3. There were 4 stacks with error left behind. I delete each one. Most were error on trying to remove a role. I deleted them and checked the role and then confirms the IAM roles were not there any longer.
4. amplify env add
  asked for new environment "buildedge" (the same name as before)
5. amplify push
It pushed successfully
6. git add *, git commit -m"blah", git push
7. I recreated the build in Amplify Console. But the build fails saying it cannot find the bit bucket.
![image](https://user-images.githubusercontent.com/3587937/70278585-2dcbc780-177a-11ea-9f65-b07cdf964709.png)

8. I also noticed that it create several empty apps in the top level of Amplify Console.
![image](https://user-images.githubusercontent.com/3587937/70278658-4d62f000-177a-11ea-821a-c826ee81d275.png)

**Expected behavior**
Environment should build and deploy.

**Additional context**
I have 4 environments. dev, build, test, and master. All the environments are currently working except for build.

I am assuming that if I create an environment with a different name it will probably work. I will try that and report back BUT this should work with the same name.

**Sample code**
Attached is the log file:
[amplify-console-log-20191205.txt](https://github.com/aws-amplify/amplify-console/files/3929363/amplify-console-log-20191205.txt)

Here is my amplify.yml file:
![image](https://user-images.githubusercontent.com/3587937/70279075-3a045480-177b-11ea-96b1-8b26ef9ae830.png)

**Comment by swaminator** [comment] 2019-12-06 18:20
@apanagos sorry to hear you're having troubles. Can you please share your appid?

**Comment by apanagos** [comment] 2019-12-07 18:51
Here is the ARN arn:aws:amplify:us-east-1:154535222214:apps/dmtcgpkyvwgrv

**Comment by swaminator** [comment] 2019-12-09 21:26
This looks like you deleted the S3 bucket for the environment. Can you goto your S3 console and see if you can find a bucket mtaching `projectname-buildedge-TIMESTAMP-deployment`?

**Comment by apanagos** [comment] 2019-12-09 22:09
So sorry, I deleted it just a few minutes ago because I needed to continue working. I created an environment with a different name (buildaaa) and that worked. It just completed building.

I did amplify env remove buildedge
This time most was removed EXCEPT if you look in the Amplify Console in the "Backend enironment" it still exists. I tried to deleted it there but it just says use amplify env remove.

And the nigh level Amplify console still has the empty apps as indicated in my comments above. I don't want to delete them in case they are connected somehow to the correct envirenment and I lose everything.

Now before I deleted the env I did see the deployment folder in S3. That was the first place i went thinking that maybe it didn't create it there. I compared it visually with the other environments and it looked the same.

**Comment by anatonie** [comment] 2019-12-12 20:14
Hi @apanagos 

We have root caused the issue and a fix is in the pipeline. If you'd like to unblock yourself immediately you can delete the backend environment from Amplify Console by using the following CLI command:

https://docs.aws.amazon.com/cli/latest/reference/amplify/delete-backend-environment.html

After doing that, please run another build and it will create a new backend as expected. 

Thanks,
Alex

**Comment by apanagos** [comment] 2019-12-13 03:30
Thanks Alex, Though I get an error saying that command does not exist.

aws amplify delete-backend-environment --app-id d250i8j55y2dby
usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help
aws.cmd: error: argument operation: Invalid choice, valid choices are:

create-app                               | create-branch
create-domain-association                | delete-app
delete-branch                            | delete-domain-association
delete-job                               | get-app
get-branch                               | get-domain-association
get-job                                  | list-apps
list-branches                            | list-domain-associations
list-jobs                                | start-job
stop-job                                 | update-app
update-branch                            | update-domain-association

When I do "aws amplify help" it lists the same commands as above.

The aws cli version I have is:
aws --version
aws-cli/1.16.96 Python/3.7.1 Windows/10 botocore/1.12.86

**Comment by apanagos** [comment] 2019-12-13 03:52
I went ahead and upgraded aws-cli and now I see the commands.
I ran but I cannot delete the apps (without environments).
When I ran to delete the one environment that is still hanging around I got the following:

aws amplify delete-backend-environment --app-id dmtcgpkyvwgrv --environment-name build
An error occurred (NotFoundException) when calling the DeleteBackendEnvironment operation: BackendEnvironment build does not exist.

I did the following commands to remove the apps that were created without environments and that worked for those apps:

aws amplify delete-app --app-id d3sfz2trn6hcxp


So know I only have the one app with the old environment that refuses to die. :)

**Comment by anatonie** [comment] 2019-12-13 17:28
@apanagos 
It looks like in your original post it was the buildedge environment that was giving you issues, not build. If that's still the case can you run the delete-backend-environment command with that environment-name?

Another option here would be to create a new environment using the Amplify CLI, push it, and then in the console, on the frontend page, you can point your frontend to the new backend you pushed from the CLI and then redeploy that frontend to use the new backend.

**Comment by apanagos** [comment] 2019-12-17 14:22
Oh yeah, duhh. Thanks. Yes it worked correctly and removed that stray backend. Thanks

**Closed** 2019-12-17 15:48 UTC
Labels: backend, bug

**Comment by apanagos** [comment] 2019-12-17 19:13
Thanks @swaminator for closing the ticket but I am checking if the bug has been recorded somewhere to follow up? @anatonie mentioned above that the issues has been found and a fix is int he pipeline. Do we have a link to follow up on? Thanks so much.

**Comment by Bulletninja** [comment] 2020-04-17 06:27
I've been getting this `NoSuchBucket` error for days and haven't been able to resolve it. Would be great if we had the link @apanagos mentions

**Comment by Bulletninja** [comment] 2020-04-17 06:31
And by the way, in my case the Deployment bucket actually exists, so i can't fix it creating it manually.
