### ISSUE TITLE
Domain activation is Failed - go daddy Domain not working

### ISSUE THREAD

**Issue by nagacheruvu** [aws-amplify/amplify-console#980] opened 2020-08-18 16:57 UTC
**App Id**: d3ldgeq2sl75h1
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

**Comment by cslogan-red** [comment] 2020-08-18 19:06
Closing as a duplicate of #979

**Closed by cslogan-red** 2020-08-18 19:06 UTC
Labels: duplicate
