### ISSUE TITLE
StorageError: Unexpected error occurred with message: Missing HTTP Response

### ISSUE THREAD

**Issue by niallkehoe** [aws-amplify/amplify-console#2092] opened 2021-07-26 22:46 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Describe the bug

I am uploading .mp4 and .png files to the S3 Buckets. I got it working a few days ago with now issues. I tried again to test it today without changing any of the code and I'm getting this error when it tries to upload anything to the cloud storage.
`
StorageError: Unexpected error occurred with message: Missing HTTP Response`

I checked the status of Amazon Services but nothing seems to be down.

This is my code throwing the problem:
```

Amplify.Storage.uploadData(
                        key: "example.png",
                        data: (image.pngData()!)
                    ) { thumbResult in
                        DispatchQueue.main.async {
                            switch result {
                            case .success(let key):
                                print("\(key) uploaded")
                            case .failure(let storageError):
                                print("fail to upload ", storageError)
                            }
                        }
                    }
```

I have Cognito added too btw, the Download part of the app is working perfectly but the upload does not work at all.
It worked a few days ago and I don't think anything has changed so...

### Expected behavior

The console to print that it had completed the upload, and the new file to appear in S3 Bucket.

### Reproduction steps

1. Setup the Storage API
2. Attempt to upload a file using `Amplify Storage`

**Comment by siegerts** [comment] 2021-08-02 13:47
Hi  @niallkehoe :wave:, thanks for raising. To get a bit more context, are you using `amplify-ios`?

**Comment by niallkehoe** [comment] 2021-08-02 16:39
@siegerts , I'm using Amplify on my iOS app and Android App. I mistakenly posted this here instead of on the amplify-ios page which I then rectified. Should I close this issue here because it seems to be an exclusively iOS issues -

The iOS App successfully downloads content from my S3 Bucket without problems, but gets a StorageError: `Unexpected error occurred with message: Missing HTTP Response` when attempting to upload.
The Android app uploads and  downloads without issue.

**Comment by siegerts** [comment] 2021-08-02 16:58
Yeah, you can go ahead and close this if you already opened an issue there, or I can transfer this over. Whichever is easier :)

**Comment by siegerts** [comment] 2021-08-02 20:07
Closing as a duplicate of https://github.com/aws-amplify/amplify-ios/issues/1343.

**Closed by siegerts** 2021-08-02 20:07 UTC
