### ISSUE TITLE
Resource is not in the state stackUpdateComplete -> API: s3:SetBucketEncryption Access Denied

### ISSUE THREAD

**Issue by jknapp25** [aws-amplify/amplify-console#2163] opened 2021-08-15 23:10 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2euhzjile9dj1

### Region

us-west-2

### Amplify Console feature

Access control

### Describe the bug

After editing `schema.graphql` and running amplify push, getting this error...

```
Resource is not in the state stackUpdateComplete
An error occurred during the push operation: Resource is not in the state stackUpdateComplete
```

...and the reason above...

```
Event Type: update
Reason: API: s3:SetBucketEncryption Access Denied
```

### Expected behavior

I expect my graphql schema to update successfully.

### Reproduction steps

1. Add a new key to the graphql schema model, for example, "emailAddress: String" on the Configuration model
2. `amplify push`
3. See error

### Additional information

It's been a few months since I've made any changes. Maybe one of my IAM roles is expired or something? I don't know, I have trouble remembering all of the different concepts in AWS.

**Comment by behrooziAWS** [comment] 2021-08-16 22:32
Your role likely hasn't expired, but the amplify cli >4.50 requires additional permissions.  Try adding the following permissions to the role you are using:

```
s3:GetEncryptionConfiguration
s3:PutEncryptionConfiguration
```

**Comment by jknapp25** [comment] 2021-08-20 01:10
@behrooziAWS I was searching for those roles but I can't find them. Can you direct me to some documentation?

**Comment by behrooziAWS** [comment] 2021-08-20 02:07
Look for the role called amplifyconsole-backend-role in the iam console: https://console.aws.amazon.com/iam/home?region=us-east-1#/roles

**Comment by jknapp25** [comment] 2021-08-20 02:19
@behrooziAWS I found the role, but I don't see how to add the permission

**Comment by behrooziAWS** [comment] 2021-08-20 15:46
Docs on how to modify the role are [here](https://docs.aws.amazon.com/IAM/latest/UserGuide/roles-managingrole-editing-console.html#roles-modify_permissions-policy).  If the role already has AdministratorAccess, the issue is something else.  If it doesn't add these two permissions to it:

s3:GetEncryptionConfiguration
s3:PutEncryptionConfiguration

**Comment by jknapp25** [comment] 2021-08-21 00:49
It does have `AdministratorAccess`

**Comment by behrooziAWS** [comment] 2021-08-21 02:22
Are you seeing this error locally?  I don't see any builds on our side for 5 months.  If so then it has to do with the credentials you are using the run the amplify cli.  Does your user have AdministratorAccess?  This talks about that user: https://docs.amplify.aws/cli/start/install/#option-2-follow-the-instructions

**Comment by hloriana** [comment] 2021-12-03 21:57
Closing. If you still need assistance, feel free to re-open this issue. Thank you!

**Closed by hloriana** 2021-12-03 21:57 UTC
Labels: pending-investigation
