### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by TemoLucky** [aws-amplify/amplify-console#53] opened 2019-08-14 10:03 UTC
**App Id**: d1dmgnwdmwopvw
**Region**: us-east-1
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
SSl verification pending, message :
" 
We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker.
"

**Error message**
No error, just pending
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Im using Cloudflare

**Comment by VividKnife** [comment] 2019-08-15 18:25
I looked into your domain, the verification record seems fine. Can you goto the domain manage page and click the `re-try` button?

**Comment by VividKnife** [comment] 2019-08-15 18:26
duplicate of https://github.com/aws-amplify/amplify-console/issues/57

**Closed by VividKnife** 2019-08-15 18:26 UTC
Labels: custom-domain
