### ISSUE TITLE
Console broken again (probably related to aws-amplify/cli 2.0.0)

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-console#88] opened 2019-08-28 18:59 UTC
**Describe the bug**
So once again my dev deployment broke in the Console.

Last time my Console deployments broke, it was suggested that I use the "Live package updates" and set Amplify CLI to `latest`. It's been like that since.

Late last night Amplify CLI released version 2.0.0. I'm not sure, but I believe that's the reason for my deployment issues in my `dev` environment.

The error I'm getting is:
```
                                 # Importing Amplify environment: dev (amplify env import)
2019-08-28T07:47:44.284Z [INFO]: Successfully added environment from your project
2019-08-28T07:47:44.336Z [INFO]: # Initializing existing Amplify environment: dev (amplify init)
2019-08-28T07:47:47.905Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-08-28T07:47:48.800Z [WARNING]: - Initializing your environment: dev
2019-08-28T07:47:49.325Z [WARNING]: ✔ Initialized provider successfully.
2019-08-28T07:47:50.535Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src398206400/src/my-amplify/amplify/backend/api/myapi/build/cloudformation-template.json
2019-08-28T07:47:50.591Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2019-08-28T07:47:50.982Z [INFO]: Throttling: Rate exceeded
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
2019-08-28T07:47:50.985Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2019-08-28T07:47:50.985Z [WARNING]: ✖ There was an error initializing your environment.
2019-08-28T07:47:50.985Z [INFO]: init failed
2019-08-28T07:47:50.987Z [INFO]: Error: Project stack doesn't exist
                                 at Response.cfnModel.describeStacks (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:248:22)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:364:18)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
2019-08-28T07:47:51.033Z [ERROR]: !!! Build failed
2019-08-28T07:47:51.034Z [ERROR]: !!! Non-Zero Exit Code detected
2019-08-28T07:47:51.034Z [INFO]: # Starting environment caching...
2019-08-28T07:47:51.034Z [INFO]: # Uploading environment cache artifact...
2019-08-28T07:47:51.129Z [INFO]: # Environment caching completed
Terminating logging...
```

My `prod` environment is deploying without issues and seems to have no problems, but as the "Live package updates" feature is global, it's also using Amplify CLI 2.0.0 when deploying.

I could do either:

1) Force 1.12.0 for both dev and prod, but I'm afraid of side effects or issues when rolling dev back even though it seems to have failed before doing anything. And I am running CLI 2.0.0 in my terminal now also (did not push in the CLI since upgrading). But I can't stay on 1.12.0 forever, so this is merely a workaround.

2) Push from the CLI using 2.0.0 and retry the Console deployment. Should I then `amplify env pull --restore` before?

I don't understand why this keeps happening. Calling Amplify production stable is a stretch to me considering the amount of issues I've hit only in the past week or two. Unfortunately, I am using it in production, so I'm gonna have to hang around and work through this.

**To Reproduce**
Automatic or manual deployment using the Amplify Console.

**Expected behavior**
That it works.

**Comment by swaminator** [comment] 2019-08-28 21:33
Seems like a CloudFormation throttling issue. Can you try hitting 'Redeploy this version'?

**Comment by houmark** [comment] 2019-08-28 21:47
Yeah, so I forgot to mention that sorry. Don't know how I forgot that. Yesterday it happened once, then as I also saw throttle issues, I retried a bit later and it worked. Since then I did not try again say 12 hours later. When I did, it did it again, so while this may be throttling, I don't understand why that would happen — and it has never happened before in over two months of doing it. And production is never hit by this.

So maybe something changed with 2.0.0 that makes this happen?

**Comment by houmark** [comment] 2019-08-28 22:44
Still not working. I have not attempted any deployment for hours (since my bug report). I think this is something else hiding under a throttling error:

```
2019-08-28T22:40:10.293Z [INFO]: # Initializing existing Amplify environment: dev (amplify init)
2019-08-28T22:40:13.770Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-08-28T22:40:14.672Z [WARNING]: - Initializing your environment: dev
2019-08-28T22:40:15.258Z [WARNING]: ✔ Initialized provider successfully.
2019-08-28T22:40:16.527Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src843251418/src/my-amplify/amplify/backend/api/myapi/build/cloudformation-template.json
2019-08-28T22:40:16.654Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2019-08-28T22:40:17.108Z [INFO]: Throttling: Rate exceeded
```

And later down:

```
2019-08-28T22:40:17.111Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
2019-08-28T22:40:17.111Z [WARNING]: ✖ There was an error initializing your environment.
2019-08-28T22:40:17.111Z [INFO]: init failed
2019-08-28T22:40:17.113Z [INFO]: Error: Project stack doesn't exist
                                 at Response.cfnModel.describeStacks (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-provider-awscloudformation/src/aws-utils/aws-cfn.js:248:22)
```

This must be related to 2.0.0 for sure because it never happened in the past.

**Comment by swaminator** [comment] 2019-08-28 23:26
@houmark we're unable to repro this at our end. Can you run `amplify status` and display how many resources you have?

**Comment by houmark** [comment] 2019-08-28 23:41
I have:

1 Auth (Cognito)
3 API, two REST, 1 graphql
8 Functions
1 Hosting

Only 1 function show Operation: Update which is partly correct as it was modified since my last push in CLI.

In addition, which may or may not be related.

I have a more or less mirrored setup in terms of data. My dev has a bit more data than production, but we are talking 500 vs. 600 main items which are in DynamoDB and being queried with GraphQL.

Since yesterday I started getting `errorType: "ResolverExecutionLimitReached"` when not limiting down to 2-300 items (I used to have 999 limit, then changed to 500 and now it does not work unless I pull less than 300).

The error is:

```
errors: Array(1)
0:
data: null
errorInfo: null
errorType: "ResolverExecutionLimitReached"
locations: []
message: "Resolver invocation limit reached."
path: []
```

But in production I still have the 500 limit, and it does not throw any errors. I cannot implement pagination due to bugs in `nextToken` and sorting with `searchable`.

Is that connected/related? I have been pulling the same 400+ items out for weeks on end while developing with 0 errors and today for the first time ever I see this error.

Remind you, I was able to deploy one time with 2.0.0 CLI through Console so my dev is running based on 2.0.0 changes but so is production with no issues (yet).

**Comment by houmark** [comment] 2019-08-29 09:20
I confirmed this is an issue with CLI 2.0.0. After having tried every few hours with the same error, I now went in and changed "Live package updates" from `2.0.0` to `1.12.0` which is effectively the same as the default CLI uses by standard at this time. It now ran backend without issues and deployed successfully:

`2019-08-29T09:18:21.169Z [INFO]: # Completed phase: build`

I did not push in any way from the CLI in the meantime. That would have been my next move. CLI 2.0.0 has some kind of bug in relation to the Console and maybe also the CLI — at least in my setup.

**Comment by swaminator** [comment] 2019-08-29 17:52
Thanks for the deepdive @hourmark and really apologize for the issues you're facing. We do have tests that run apps on the Amplify Console for CLI version bumps but it is sometimes very difficult to reproduce individual scenarios. Currently we're trying to diagnose if its an issue with the CLI only vs an issue the with CLI running in the build container. It would really help us root cause if you can run `amplify push` locally to see what's happening.

**Comment by houmark** [comment] 2019-08-29 19:19
@swaminator I can do a push in the CLI but please confirm:

CLI push is with 2.0.0 right?

If this creates problems and breaks even more, can I downgrade CLI and push again without further issues? I want to make sure it's not gonna get even worse than now.

**Comment by houmark** [comment] 2019-08-29 22:46
I did `amplify push` using CLI 2.0.0. I only had one function showing as needing update. I did not pull my env before in any way. That went without a problem, but it also looks like it skipped most of the updates as it detected no changes.

I can now try `amplify env pull --restore` and another push to see how that works.

Then I can try a simple API change to see if that does anything.

Is this the right path @swaminator?

**Comment by houmark** [comment] 2019-08-30 00:48
I now did a `amplify env pull --restore` which resulted in no local changes, so nothing to push.

I then did a blank line change in my schema.graphql and pushed using the CLI with 2.0.0 answering yes to all.

That resulted in the `amplify/backend/api/my-api/transform.conf.json` file to be created which is interesting. The push went without problems.

Next step is to commit and push a change to Git to make the Console deploy again. Probably this is very similar to last weeks issue.

**Comment by houmark** [comment] 2019-08-30 01:34
I now pushed changes to Git which resulted in a Console deployment which is again set to "Live package updates" Amplify CLI: latest which means it will use/patch to 2.0.0. 

It now deployed without issues, so this is once again an issue where the Console gets stuck until the CLI has deployed once after the update. This is really something the AWS team should look into figuring out.

Of course, the best solution would be if the Console would somehow imitate the CLI better when it detects any type of need to. Alternatively, it could at least detect and warn or guide the user to do a  manual CLI push and then redo the deployment.

**Comment by swaminator** [comment] 2019-09-18 01:36
We are working on a better integration between the Console and CLI so the Console is more aware of backend deployments. Closing this issue for now.

**Closed by swaminator** 2019-09-18 01:36 UTC
Labels: backend, bug

**Comment by im-dnsosso** [comment] 2019-10-09 11:00
same error with 3.11.0 
**Could not read cloudformation template at path: /codebuild/output/**

**Comment by swaminator** [comment] 2019-10-12 00:16
@im-dnsosso we fixed this with version `3.13.0`

**Comment by jcvalerio** [comment] 2019-12-06 22:07
upgrade from 2.0.0 to 4.0.0 fixed our `AccessDenied: Access Denied` error

**Comment by BardiaN** [comment] 2019-12-17 17:00
This is back on version 4.6!
