### ISSUE TITLE
Access Denied error after deploying Vue.js application

### ISSUE THREAD

**Issue by faizanbashir** [aws-amplify/amplify-console#436] opened 2020-02-13 10:15 UTC
I am trying to deploy a vue.js application, once the deploy completes I am getting the below error:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>69F14474972D101F</RequestId>
<HostId>
OUeLFCflVlOsrmr9dklT/JzhiMYpr49zIW7X9WflA0XpMrHeTI9rO7P4DasivogoEw2AVCzLTT8=
</HostId>
</Error>
```

**Comment by prasaddattu478** [comment] 2020-02-13 16:14
We got a similar issue. in our case, index.html was under /xyz/xyz/ subdirectory path instead of being at root level. To fix it we went inside the directory where index.html is present & did a zip. deployed the zip file and we are able to access it.

**Comment by Joycehao19** [comment] 2020-02-15 00:07
Hi @faizanbashir , sorry that you have this issue. Which amplify cli version did you use? Can you provide you appId and region? Thanks.

**Comment by faizanbashir** [comment] 2020-02-15 05:36
@Joycehao19 I deployed it from the amplify console for continuous deployment, there is no amplify cli involved. Also when I deploy the same vue.js app using amplify cli it works perfectly but using the amplify console it is giving me the aforementioned error. No amplify backend services are used in this application.

**Comment by ganipcanot** [comment] 2020-02-20 20:24
@faizanbashir Can you share your build settings?  There might be something wrong with how you are generating your output/artifacts folder/directory.

**Comment by fsthomas** [comment] 2020-03-01 22:23
I'm having a similar issue with a React app's images directory. They're all coming through as `AccessDenied`.

**Comment by jonkelling** [comment] 2020-03-06 08:27
I am also having trouble with this. index.html works but bundle.js comes through as AccessDenied.

**Comment by faizanbashir** [comment] 2020-03-09 06:43
@ganipcanot here is the `amplify.yml` build file:

```
version: 0.1
env:
  variables:
    NODE_ENV: production
    SOME_VAR_FOO: bar 
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
        - npm install -g @vue/cli-service @vue/cli-plugin-babel @vue/cli-plugin-eslint @vue/cli-plugin-pwa babel-eslint eslint eslint-plugin-vue node-sass sass-loader vue-template-compiler webpack webpack-cli webpack-dev-server
    build:
      commands:
        - export $(cat .env.staging)
        - npm install
        - vue-cli-service build --mode production
    postBuild:
      commands: 
  artifacts:
    baseDirectory: .
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```
Even after installing using both npm and yarn `vue-cli-service` is not found, so I manually tried to install the package and its dependencies and that also does not work and `npx vue-cli-service` also does not seem to work.

**Comment by ahasna** [comment] 2020-03-27 19:27
@faizanbashir I had a similar issue where I couldn't access any routes and was getting `AccessDenied`.
the only change I did is to change a `404 Redirect` to `404 Rewrite`  then all routes worked. 
Hope this helps!

**Comment by faizanbashir** [comment] 2020-03-28 06:28
@ahasna Thanks for the suggestion will try it out once the build works properly. Right now I am not able to run the build commands properly even though all the required packages are installed.

**Comment by 2manoj1** [comment] 2020-03-28 20:39
Same issue with Next.js app. After deploy got access denied error (403)

**Comment by swaminator** [comment] 2020-04-02 18:48
@2manoj1 we have an issue with hidden folders not deploying right now which we have prioritized a fix for. One way to unblock is to change the folder which you deploy to one without a `.`

**Comment by 2manoj1** [comment] 2020-04-04 21:03
@swaminator thank you. Able to deploy Nextjs frontend only useing 
`next build && next export`. Its out folder. But if I have Nextjs API how we will deploy in Amplify console?

**Comment by gauravhanda25** [comment] 2020-04-16 10:24
> @swaminator thank you. Able to deploy Nextjs frontend only useing
> `next build && next export`. Its out folder. But if I have Nextjs API how we will deploy in Amplify console?

I did same for frontend. My baseDirectory is out but still getting AccessDenied

**Comment by gauravhanda25** [comment] 2020-04-16 10:47
> @swaminator thank you. Able to deploy Nextjs frontend only useing
> `next build && next export`. Its out folder. But if I have Nextjs API how we will deploy in Amplify console?

@2manoj1  Can you provide your amplify.yml after success?

**Comment by 2manoj1** [comment] 2020-04-16 11:27
`version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run export
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
`

**Comment by 2manoj1** [comment] 2020-04-16 11:30
@gauravhanda25 --> in package.json -> "export": "next build && next export".

```version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run export
  artifacts:
    baseDirectory: out
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

**Comment by gauravhanda25** [comment] 2020-04-16 11:47
> @gauravhanda25 --> in package.json -> "export": "next build && next export".
> 
> ```
> backend:
>   phases:
>     build:
>       commands:
>         - '# Execute Amplify CLI with the helper script'
>         - amplifyPush --simple
> frontend:
>   phases:
>     preBuild:
>       commands:
>         - yarn install
>     build:
>       commands:
>         - yarn run export
>   artifacts:
>     baseDirectory: out
>     files:
>       - '**/*'
>   cache:
>     paths:
>       - node_modules/**/*
> ```
> 
> **
> 
> > build:
> > commands:
> > - yarn run export
> > artifacts:
> > baseDirectory: out
> 
> **
> 
> Github Link sample example-> [ToDoList](https://github.com/2manoj1/todolist-amplify-nextjs/tree/master)

@2manoj1  So you made it work with amplify cli. So it didnt work with amplify console ?

**Comment by 2manoj1** [comment] 2020-04-16 12:21
@gauravhanda25 in Amplify console -> build settings 
<img width="1392" alt="Screen Shot 2020-04-16 at 5 48 16 PM" src="https://user-images.githubusercontent.com/15128569/79455562-abe28980-800a-11ea-9526-fb858ca17433.png">

in package.json -> script changes 
**"export": "next build && next export".**

**Comment by gauravhanda25** [comment] 2020-04-16 12:32
> @gauravhanda25 in Amplify console -> build settings
> <img alt="Screen Shot 2020-04-16 at 5 48 16 PM" width="1392" src="https://user-images.githubusercontent.com/15128569/79455562-abe28980-800a-11ea-9526-fb858ca17433.png">
> 
> in package.json -> script changes
> **"export": "next build && next export".**

Still no luck. Deployment is always green tick but Access Denied is always there.
https://master.d1pgdow2brm58j.amplifyapp.com/

**Comment by 2manoj1** [comment] 2020-04-16 13:38
@gauravhanda25 Can we connect in Skype? So I will help you.

**Comment by Sut3kh** [comment] 2020-04-18 09:20
Same problem here with the connected branch frontend build.

We have 4 projects using amplify and only 2 of them have this problem. The 2 that work do not have an amplify backend - which implies there is some hidden or default config being triggered?

1 of the projects with the 403 problem has exactly the same amplify.yml as the 2 that work (no backend section) so just a manually pushed backend appears to be enough to trigger it (no hosting, just auth & api)

**Comment by shide1989** [comment] 2020-04-27 14:35
ahd the same issue, went to Amplify console to add a redirect rule on my application that works perfectly : 
<img width="802" alt="Capture d’écran 2020-04-27 à 16 35 23" src="https://user-images.githubusercontent.com/7138331/80384404-20d47f80-88a5-11ea-9379-3828134ff072.png">

**Comment by gvelez-postmates** [comment] 2020-05-17 22:46
Ah!  the  404 (rewrite) worked for me!  I had been getting the same error, and had been following some other suggestions for a 200 rewrite rule (that make sense to me), but the 400 rule 

![image](https://user-images.githubusercontent.com/41213676/82161924-93f26580-9855-11ea-8b4f-696dca4483d2.png)

worked!  no more 403..

![image](https://user-images.githubusercontent.com/41213676/82161846-0878d480-9855-11ea-8601-a0c9c147143d.png)

thank you, this had been driving us nuts for some time!

**Comment by gvelez-postmates** [comment] 2020-05-17 22:47
actually this worked, but broke images - I will replace with a regexp to exclude img files

**Comment by Joycehao19** [comment] 2020-06-04 00:50
Hello @Sut3kh , do you still face this issue? did you try adding rewrite rule?

**Comment by plotka** [comment] 2020-06-12 12:44
> We got a similar issue. in our case, index.html was under /xyz/xyz/ subdirectory path instead of being at root level. To fix it we went inside the directory where index.html is present & did a zip. deployed the zip file and we are able to access it.

I was having the same 403 error and the issue was that the index.html was not in the root folder. Thanks, @rama3319

**Comment by abarrdev** [comment] 2020-06-19 22:04
For anyone having this issue with React, the 404 rewrite worked for me as well. Thanks @shide1989 !

**Comment by swaminator** [comment] 2020-06-24 07:00
Closing this issue - we are going to update the Create app flow to automatically create a 404 rewrite instead.

**Closed by swaminator** 2020-06-24 07:00 UTC
Labels: question

**Comment by kewp** [comment] 2020-07-27 11:37
This has been covered before but it wasn't clear to me so I want to reiterate:

If you are doing a _manual deploy_ make sure you **don't zip the folder** but rather the _files_ in the folder. https://docs.aws.amazon.com/amplify/latest/userguide/manual-deploys.html. See the note half way down about the access denied message

**Comment by Darktofts** [comment] 2020-07-28 14:33
Hi I am getting the error 403, as many have.  I deployed the code via the console .   Using a bitbucket  connection 

I've added both a 202 and 404 rewrite rule. for `<*>` to `/index.html`

I'm getting 

`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>**</RequestId>
<HostId>*******</HostId>
</Error>`

Did anyone fix this another way ?

**Comment by Bhavikpatel576** [comment] 2020-08-01 17:19
For me, I had to look through my build logs to see if I was properly serving up the index.html file. Made adjustments to point to the correct directory and it worked for me.

**Comment by Njivaniaina** [comment] 2020-08-03 14:33
Same problem,
I made the redirection,
I no longer have access problems, but all my styles and images don't work anymore.

**Comment by tkwong94** [comment] 2020-08-05 07:33
Although the issue is already closed but just in case someone else need it, I am leaving my solution here.

My problem: Getting AccessDenied XML 
Background:  Nuxt universal(SSR/SSG) application, using frontend CI connected to a gitlab project (all green ticks during deployment), having backend env too
Solution: updated the build setting on console, make sure the baseDirectory is **dist**

**Comment by khushal87** [comment] 2020-08-05 19:43
Any solution for react 403?

**Comment by shide1989** [comment] 2020-08-06 08:04
Small update here using Gatsby+React :
We ended up removing the <*/> redirection to the index.html.
It seem that this rule rewrites **any request** to the index.html and causes assets not to work anymore,
which breaks everything.

Now our rewrite rules only have the main 301 redirects to the main website URL (with www.xxx.com), 
and 200 rewrites for a few subpaths : i.e /profile -> /profile/index.html -> 200 (Rewrite)
So that refreshing pages on these subpaths doesn't show the home page

@khushal87 I suggest you check your bulid settings, as 403 are usually returned when there are no assets/files available

**Comment by Liguo-Ma** [comment] 2020-09-23 07:07
Use this rule
[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]

**Comment by pvsvamsi** [comment] 2020-09-25 11:39
@Liguo-Ma Your rule has worked. But can you explain what this rule does?

**Comment by christophrrb** [comment] 2020-09-28 06:10
If you use the Vue cli with `npm run build`, the index.html file might not be in the `dist` folder. To account for that, the `baseDirectory` for `amplify.yml` can be set to the root directory, like `./`, so that Amplify finds it.

**Comment by Liguo-Ma** [comment] 2020-10-01 14:34
Hi @pvsvamsi 
Sorry for late
Please check https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html

**Comment by tonykaram1993** [comment] 2020-10-28 15:20
We had the same issue, and we where trying to follow the amplify documentation: https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa (Redirects for Single Page Web Apps (SPA)).

It did not work, but instead of: `</^[^.]+$|.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>` we used `</^((?!.(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$).)*$/>` and it worked perfectly.

I hop this helps someone else.

**Comment by kevinadhiguna** [comment] 2021-03-26 09:24
In my case, I misspelled.
`/</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>` (Invalid) 
`</^[^.]+$|\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>` (**Valid**)

Target Address was `/index.html` with Type `200 (Rewrite)` worked for me. Btw it's not VueJS but [Ant Design Pro](https://github.com/ant-design/ant-design-pro) (ReactJS).

Another difference was baseDirectory: `/dist/` and `cache` block : 

![image](https://user-images.githubusercontent.com/43397636/112610763-a236e800-8e4f-11eb-912d-2687df40cc4b.png)

**Comment by vktrgama** [comment] 2021-05-03 15:57
I had same issue, but found my issue was not using react-router for my links and navigation, otherwise they are considered external to react and pointing to a folder, hence, access denied, I have to dig more since recommendations, even if helpful, are a hacky band-aid.

**Comment by evcodes** [comment] 2021-08-16 03:19
> </^((?!.(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$).)*$/>

So I am building a React Application and using Antd for the frontend and this worked for me too! 
Original Address: </^((?!.(css|gif|ico|jpg|js|png|txt|svg|woff|ttf)$).)*$/>
Destination Addres: index.html
Redirect Type: 200

I am not sure if this makes a difference but it's my first rule. 
Cheers!

**Comment by zsan** [comment] 2022-05-22 11:01
<img width="859" alt="Screen Shot 2022-05-22 at 18 00 25" src="https://user-images.githubusercontent.com/229909/169691920-19ba8078-f074-404e-972b-6bb9f4005251.png">

Same issue, fixed by `404 rewrite` after `amplify publish`
