### ISSUE TITLE
Problems setting up 404 page on Gatsby site in AWS Amplify

### ISSUE THREAD

**Issue by swaminator** [aws-amplify/amplify-console#70] opened 2019-08-22 20:40 UTC
REF: https://stackoverflow.com/questions/56634467/problems-setting-up-404-page-on-gatsby-site-in-aws-amplify

I have a [simple Gatsby site](https://www.ember.to/) that I've deployed through AWS Amplify based on this guide. However, I'm struggling to set up a proper 404 page through the AWS Amplify Console (or via a config file).

I want it to behave like a standard 404 page such as that on Google.com – i.e.

Incorrect URLs show the content of my 404 page (ember.to/404)
The incorrect URL is kept the same in the URL bar – i.e. the user does not see a redirect
A 404 status code is returned in the header so the browser/GoogleBot knows it's a 404
What's happening currently:

- I've set up a rule in "Rewrites and redirects" of type "404" with source address "/<*>" and destination address "/404"
- This means that if someone goes to (e.g.) ember.to/blah which doesn't exist, they see the 404 page as desired. However, the URL in their browser bar changes to ember.to/404 (not desired) and the HTTP header does not give a 404 status
- I've also tried changing the redirect type to "200". This almost gives the right behaviour on incorrect URLs (URL stays same, 404 message is shown and 403 error returned to browser) but unfortunately that means all valid pages on my site show the 404 message
- I can't see any way of configuring it so that a 200 redirect is performed only when a 404 message is returned when accessing a URL
- Can anyone help with this? I'm not really clear if there are more advanced configuration options I'm missing outside the console? Can I do something with the build settings using the amplify.yml file?

**Comment by swaminator** [comment] 2019-08-23 18:14
For anyone else who lands here, we will add support for this feature in the coming weeks.

**Comment by swaminator** [comment] 2019-09-10 17:43
The fix has been deployed - please select a 404 rewrite to test. @jamieweavis @valtermartin1301 @sirichards can you please verify it works for you?
<img width="466" alt="Screen Shot 2019-09-10 at 10 42 21 AM" src="https://user-images.githubusercontent.com/2429410/64637043-cb9c3a00-d3b7-11e9-9199-e1c4a9b24f2d.png">

**Comment by jamieweavis** [comment] 2019-09-11 12:39
I'm not seeing my 404 page at all with that rewrite @swaminator, see: https://www.jamieweavis.dev/test

Rewrites and redirects:
![Screenshot 2019-09-11 at 13 35 08](https://user-images.githubusercontent.com/8133259/64697549-01651f80-d499-11e9-8cad-5770d8df83cf.png)

Also tried with the following target addresses:
- `/404`
- `https://www.jamieweavis.dev/404`

But that gives me:
![Screenshot 2019-09-11 at 13 38 33](https://user-images.githubusercontent.com/8133259/64697765-7a647700-d499-11e9-9d46-d5057d712e53.png)

**Comment by swaminator** [comment] 2019-09-11 18:01
@jamieweavis appears to be working for me?
<img width="610" alt="Screen Shot 2019-09-11 at 11 01 03 AM" src="https://user-images.githubusercontent.com/2429410/64722522-79c0e600-d483-11e9-84ec-862be3ca1285.png">

**Comment by jamieweavis** [comment] 2019-09-11 18:42
The status code is correct but I have a dedicated page at https://jamieweavis.dev/404 which I'd like to be shown without the URL changing (no redirect), for example https://jamieweavis.dev/test would show the 404 page but keep the `/test` URL, if that makes sense?

**Comment by anatonie** [comment] 2019-09-11 18:54
Hi @jamieweavis if you have a dedicated 404 page at https://jamieweavis.dev/404 please update the target address for your **404 (Rewrite)** rule to be **/test** instead of **/index.html**

**Comment by jamieweavis** [comment] 2019-09-11 19:05
Hi @anatonie - doing so gives the `AccessDenied` error mentioned above. The `/test` route was just an example of a route that doesn't exist and should display the 404 page

**Comment by swaminator** [comment] 2019-09-13 16:20
@sirichards both seem to work for me (with styles). Are you seeing an issue?

**Comment by sirichards** [comment] 2019-09-16 09:02
@swaminator sorry I had to revert back to a redirect as that website went live and it was causing the issue, I've created a new test here:
[https://master.d1qbgpt3cc978c.amplifyapp.com/page-2/](https://master.d1qbgpt3cc978c.amplifyapp.com/page-2/) (with trailing slash)
[https://master.d1qbgpt3cc978c.amplifyapp.com/page-2](https://master.d1qbgpt3cc978c.amplifyapp.com/page-2) (without trailing slash)

Without the trailing slash you get the flash of the 404, also the http status is also recorded as a 404.

**Comment by ariadne-github** [comment] 2019-09-16 09:55
@sirichards that is caused by the suggested 404 rule (`<*> => /404.html`), which conflicts with the default amplify behaviour. We solved by using `</index\.html/> => /404.html` instead.

**Comment by sirichards** [comment] 2019-09-16 10:08
@ariadne-github that seemed to fix the slash issue, however I am now getting 403 access denied when visiting a page that doesn't exist.

https://master.d1qbgpt3cc978c.amplifyapp.com/uyhyjuth/

![image](https://user-images.githubusercontent.com/21104091/64949897-1dd6d280-d872-11e9-92e5-6f4f4bd23779.png)


![image](https://user-images.githubusercontent.com/21104091/64949906-2202f000-d872-11e9-9636-de97e75a8895.png)

**Comment by ariadne-github** [comment] 2019-09-16 10:09
Hmmm, maybe try removing the starting "/"?

**Comment by sirichards** [comment] 2019-09-16 10:10
@ariadne-github that fixed it, thanks! :)

**Comment by ariadne-github** [comment] 2019-09-16 10:12
You are welcome. This seems to work for now, but please comment here if you notice any other side effect.

**Comment by swaminator** [comment] 2019-09-18 01:42
Closing this issue for now. Please reopen if you have any issues.

**Comment by steverandy** [comment] 2020-01-07 09:42
@ariadne-github @swaminator  there is a side effect with the above configuration.
When you load a non html file that does not exist, it shows `AccessDenied` page instead of 404.

**Comment by ryanbagwell** [comment] 2020-09-23 14:02
@swaminator we might need to reopen this. The 404 rewrites on our site are no longer working. I have the following rewrite in place:

`</index\.html/> => /404.html`

but I'm getting a 403 response when I go to https://www.example.com/foo/

**Comment by kylegwalsh** [comment] 2020-09-23 19:54
@ryanbagwell

We also just started seeing this issue today. It worked in the past, but suddenly stopped working today.

**Comment by shankinson** [comment] 2020-09-23 21:12
I am seeing the same thing.

**Comment by swaminator** [comment] 2020-09-25 20:55
@shankinson @kylegwalsh @ryanbagwell reopening this issue.

**Comment by shankinson** [comment] 2020-09-25 23:54
appid: d13epz5f3n6l5q, us-east-1

**Comment by hsspain** [comment] 2020-09-26 04:47
@shankinson @kylegwalsh @ryanbagwell  The issue has been identified and a resolution will be out shortly.

**Comment by hsspain** [comment] 2020-09-26 05:53
The issue with 404 rewrite rule has been resolved.  Please redeploy your app to continue to use the custom rewrite rule.

**Comment by swaminator** [comment] 2020-10-06 21:06
@shankinson @kylegwalsh @ryanbagwell can you please confirm?

**Comment by ryanbagwell** [comment] 2020-10-06 21:09
@swaminator looks good on my end. Many thanks.

**Comment by shankinson** [comment] 2020-10-07 12:37
Appears to be fixed.

**Comment by kylegwalsh** [comment] 2020-10-07 13:46
@swaminator The issues was fixed on our end as well.

**Closed** 2020-10-07 17:50 UTC
Labels: bug, pending-customer-response

**Comment by aalexcomas11** [comment] 2021-06-17 22:12
@swaminator I've tried the following mappings
`/<*>` => `/404.html`
`</index\.html/>` => `/404.html`

With 404 (rewrite) and I get 500 error `Internal Server Error: target response exceeds 1MB limit.`

Changing it back to 404 (redirect) "works" but it doesn't give the desired behavior you mentioned when opening this issue.

**Comment by Zecento** [comment] 2021-08-31 17:28
> @swaminator I've tried the following mappings
> `/<*>` => `/404.html`
> `</index\.html/>` => `/404.html`
> 
> With 404 (rewrite) and I get 500 error `Internal Server Error: target response exceeds 1MB limit.`
> 
> Changing it back to 404 (redirect) "works" but it doesn't give the desired behavior you mentioned when opening this issue.

Same on my end. 
I have my redirect setup like this:
`/<*>` => `/not-found`

With 404 (rewrite) i get the default chrome HTTP ERROR 404 page (I attached a screenshot)
With 404 (redirect) it "works" fine, even though it doesn't give the desired behavior that was mentioned when opening this issue (keeping the same url but changing the page).
![Capture](https://user-images.githubusercontent.com/83454162/131548638-2ad3194e-880e-456f-a6fa-84b667bef223.PNG)

**Comment by Emily-Thomas** [comment] 2021-09-09 20:43
Also having the same issue on a nextjs app hosted with amplify. 
With 404 (rewrite) getting the default chrome HTTP ERROR 404 page
With 404 (redirect) it works visually but does not have the intended behavior.

**Comment by alejoar** [comment] 2021-11-03 18:24
@sirichards how did you fix the 404 flash? I'm using Gatsby and also seeing this.

Without the slash, a flash for a second of the 404 page and then it loads the right page.

**Comment by Zecento** [comment] 2021-11-04 15:11
> n a nextjs app hosted with amplify.
> With 404 (rewrite) getting the default chrome HTTP ERROR 404 page
> With 404 (redirect) it works visually but does not have the intended behav

I have the same exact issue!

**Comment by ymeinergrm** [comment] 2022-08-02 15:26
i'm not sure this one is closed. i tried to implement every suggestion here and still see the same issue. any idea how to resolve for gatsby?
