### ISSUE TITLE
Domain activation

### ISSUE THREAD

**Issue by henryodinakamin** [aws-amplify/amplify-console#2159] opened 2021-08-12 18:12 UTC
### Before opening, please confirm:

- [X] I have checked the [custom domains troubleshooting guide](https://docs.aws.amazon.com/amplify/latest/userguide/custom-domain-troubleshoot-guide.html).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d6eer7zhsxjya

### Region

eu-west-2

### Step

Domain activation

### Status

Failed

### Issue or question

I cannot add custom domain

### Error message

We had issues connecting your custom domain: min.ng. Please visit the Domain Management page for more information.

**Comment by siegerts** [comment] 2021-08-12 18:38
Duplicate of #2158

**Closed by siegerts** 2021-08-12 18:38 UTC
Labels: custom-domain
