### ISSUE TITLE
Amplify Console redirects to wrong url when trailing slash required

### ISSUE THREAD

**Issue by idrisov-ri** [aws-amplify/amplify-console#405] opened 2020-02-04 11:22 UTC
Not sure this is right place for my question.

From AWS Amplify documentation:

> The Amplify Console automatically creates clean URLs by adding a trailing slash when required. The table below highlights different scenarios:

> User inputs in browser | URL in the address bar | Document served
> -- | -- | --
> /about | /about | /about.html
> /about (when about.html returns 404) | /about/ | /about/index.html
> /about/ | /about/ | /about/index.html
> 

In App we are working at now the second scenario is not true.

When user inputs `/about` (no trailing slash in the end)and needed to be redirected to `/about/`(have trailing slash in the end), instead he is being redirected to  a url similar  to something like `/0000000030/about/`. Where the `0000000030` part  of the url seems to be a Build ID of AWS Amplify App.
This url not exists so user get **403** response status with `AccessDenied` XML error message.

My question is, is it desired behavior or is it a bug?
If it is a bug what can we do to make it work as desired?(`/about`, is rediricted to `/about/`, not to`/0000000030/about/`) 

By the way, there are no Rewrite or Redirect rules set up in our Amplify Console App.

thanks in advance!

**Comment by Joycehao19** [comment] 2020-02-11 18:51
Hi @idrisov-ri we cut a ticket in our customer oncall backlog, will investigate your issue later. Thank you for understanding.

**Comment by Joycehao19** [comment] 2020-04-09 22:23
Hi @idrisov-ri , Thank you for reporting. I cut a ticket in our team backlog. We will working on investigating a fix!

**Comment by j-yamamoto** [comment] 2020-08-12 09:40
@Joycehao19 +1 for this problem to be fixed. Btw, is there any workarounds to redirect url without trailing slash to one with trailing slash?

**Comment by eganondorf** [comment] 2020-09-23 00:06
I add myself to this problem, but for me the problem is as follows:
If I navigate to my application via the base URL `https://<app_url>`, perform the login, navigate through my menus, everything works fine.

But if for some reason I refresh, either by pressing F5 or pressing the icon on the browser, then I get the `https://<app_url>/<build_#>/<path_I_was_on>` instead of a simple reload to `https://<app_url>/<path_I_was_on>`

I do have a single redirect setup due to my app being a SPA build on VueJS:
`[
    {
        "source": "/<*>",
        "target": "/index.html",
        "status": "200",
        "condition": null
    }
]`

My application id is `d2a5vpuqb7f44i` on `us-east-1`

**Comment by eganondorf** [comment] 2020-09-23 18:12
> I add myself to this problem, but for me the problem is as follows:
> If I navigate to my application via the base URL `https://<app_url>`, perform the login, navigate through my menus, everything works fine.
> 
> But if for some reason I refresh, either by pressing F5 or pressing the icon on the browser, then I get the `https://<app_url>/<build_#>/<path_I_was_on>` instead of a simple reload to `https://<app_url>/<path_I_was_on>`
> 
> I do have a single redirect setup due to my app being a SPA build on VueJS:
> `[ { "source": "/<*>", "target": "/index.html", "status": "200", "condition": null } ]`
> 
> My application id is `d2a5vpuqb7f44i` on `us-east-1`

Forget my initial reply, I just followed the info on https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa and now its redirecting correctly.

The only heads up is to copy paste the Regex using the *Open text editor* option after you clicked *Edit* on the *Rewrites and redirects* page, that way you are sure you didn't copy some undesired space.

**Comment by theelk801** [comment] 2020-11-10 23:48
Hi, I'm also having this issue. Will there be a fix soon?

**Comment by theelk801** [comment] 2020-11-12 02:40
Just to add some info, I've noticed that the problem doesn't happen on build previews, only on main deployments.

**Comment by hankyupark** [comment] 2020-12-02 05:37
> > I add myself to this problem, but for me the problem is as follows:
> > If I navigate to my application via the base URL `https://<app_url>`, perform the login, navigate through my menus, everything works fine.
> > But if for some reason I refresh, either by pressing F5 or pressing the icon on the browser, then I get the `https://<app_url>/<build_#>/<path_I_was_on>` instead of a simple reload to `https://<app_url>/<path_I_was_on>`
> > I do have a single redirect setup due to my app being a SPA build on VueJS:
> > `[ { "source": "/<*>", "target": "/index.html", "status": "200", "condition": null } ]`
> > My application id is `d2a5vpuqb7f44i` on `us-east-1`
> 
> Forget my initial reply, I just followed the info on https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa and now its redirecting correctly.
> 
> The only heads up is to copy paste the Regex using the _Open text editor_ option after you clicked _Edit_ on the _Rewrites and redirects_ page, that way you are sure you didn't copy some undesired space.

this works for me

**Comment by jasonrundell** [comment] 2021-01-29 19:38
This has been open for a long time. When is this issue coming out of the backlog and being worked on?

**Comment by msmurgui** [comment] 2021-02-17 16:22
Same issue here! Cannot accept url query params because of the trailing dash, it cleans everything on the query

**Comment by msmurgui** [comment] 2021-02-19 14:39
Fixed it by changing my "Rewrites and Redirects" rules. The only one I left was this one:
`[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "/",
        "status": "200",
        "condition": null
    }
]`

**Comment by hsspain** [comment] 2021-02-19 18:49
The issue with build numbers being appended to redirects has been resolved.  I am closing out this issue, but please open a new one if anyone continues to have issues.

**Closed by hsspain** 2021-02-19 18:49 UTC
Labels: bug, pending-prioritization
