### ISSUE TITLE
on the CI/CD, amplifyPush should only deploy changes made (frontend/backend)

### ISSUE THREAD

**Issue by aprilmintacpineda** [aws-amplify/amplify-console#868] opened 2020-07-15 15:25 UTC
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**

- `amplifyPush` pushes backend even when there are no changes on the backend.
- `amplifyPush` pushes frontend even when there are no changes on the frontend.

**Amplify CLI Version**
4.24.1

**To Reproduce**

just use `amplifyPush` on the CI/CD

**Expected behavior**

- `amplifyPush` should skip the backend when there are no changes.
- `amplifyPush` should skip the frontend when there are no changes.

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: N/A
 - Node Version: N/A

**Additional context**

N/A

**Comment by brene** [comment] 2020-07-16 23:02
Transferring this to console. cc @litwicki

**Comment by aprilmintacpineda** [comment] 2020-08-06 23:46
Updated ticket description and title, please see above...

**Comment by RossWilliams** [comment] 2020-08-12 01:44
I came to ask for a similar feature. My frontend build phase had a file corruption, but i couldn't quickly rebuild the frontend only, instead I needed to wait an extra 10 minutes for the backend to do nothing. I had this earlier when CloudFront decided to ignore my custom header changes and it took a long time to have the backend do nothing.

**Comment by keponk** [comment] 2020-09-14 08:47
Have had same annoyance since the beginning of using Amplify. So far I ran with the assumption this is by design but now tracking this issue since I'd also appreciate being able to deploy only the frontend.

**Comment by hisham** [comment] 2020-09-29 20:28
+1. Quick deployments are essential when doing emergency bug fixes. Backend does not need to be rebuilt if frontend only has changed. It just needs the aws-exports. Why is amplify push in my terminal smarter than amplify push via amplify console? 

Smarter backend deployments will also save cost since AWS Amplify console charges per build minute.

**Comment by mansiva** [comment] 2020-10-02 01:30
+1 Please AWS, this shouldn't be that hard to fix, CLI only updates what's changed, why can't the Console do the same??

**Comment by arturocanalda** [comment] 2020-11-04 10:35
+1

**Comment by frank-unovica** [comment] 2021-08-10 09:35
+1

**Comment by CloudWindSolutions** [comment] 2021-09-16 12:49
+my team

**Comment by swaminator** [comment] 2021-11-10 01:43
Sorry for missing this @arturocanalda @mansiva @hisham @keponk @mhamendes @frank-unovica @RossWilliams @aprilmintacpineda  we added support for conditional backend builds: https://docs.aws.amazon.com/amplify/latest/userguide/conditional-backends.html

**Closed by swaminator** 2021-11-10 01:43 UTC
Labels: feature request, backend-build
