### ISSUE TITLE
Deploy phase keeps getting stuck at "Updating Edge config"

### ISSUE THREAD

**Issue by ryanbagwell** [aws-amplify/amplify-console#1459] opened 2021-01-15 22:37 UTC
Our deploys periodically get stuck at "Updating Edge config".

It happened today:

```
2021-01-15T22:30:18 [INFO]: Starting Deployment
2021-01-15T22:30:19 [INFO]: Updating Edge config
```

Also happened last week:

```
2021-01-07T21:24:46 [INFO]: Starting Deployment
2021-01-07T21:24:47 [INFO]: Updating Edge config
```

Many others have also noted this failure (see #1417 #1387 #1395 #1167 #1313 #1380 #1250).

**Comment by nimacks** [comment] 2021-01-15 22:44
Can you provide your app Id and region?

**Comment by ryanbagwell** [comment] 2021-01-15 22:51
Region: us-east-1
App ID I think: d2lnj6dcs32j7m

**Comment by arnaskro** [comment] 2021-01-16 12:47
We are experiencing the same issue, except it always gets stuck at `Updating Edge config` step whenever we try to deploy a file from S3. Manual deployments when uploading a file directly works without issues. Tried restarting a few times and waiting for a few hours, but nothing happens. Also tried creating new S3 Buckets and new apps but no changes... Had an attempt to wait overnight but then it just failed without any additional logs. Strange that this was working two days ago...

**Comment by hsspain** [comment] 2021-01-19 18:53
@arnaskro Can you provide your app ID and region?

@ryanbagwell We have root caused intermittent issues that may be affecting your deployments and a fix is being pushed shortly. We will continue to monitor, but the reliability of your deployments should be better in the coming days.

**Comment by arnaskro** [comment] 2021-01-19 19:12
@hsspain the issue has went away around 2 days ago... We haven't changed anything, just tried creating a new deployment some time after commenting here.
Since then we already tried creating new apps and there are no issues for now 😄 
This was in the eu-north-1region

**Comment by hsspain** [comment] 2021-01-19 19:22
@arnaskro Thank you for the update. We will continue to monitor and the latest update should also increase your reliability in the coming days.

**Comment by ryanbagwell** [comment] 2021-01-22 20:53
@hsspain still running into errors here.

Stuck in the deploy phase just now:

```
2021-01-22T20:31:37 [INFO]: Starting Deployment
2021-01-22T20:31:37 [INFO]: Updating Edge config
uildId 0000000159
2021-01-22T20:31:59 [INFO]: Got archive: 1843331307 bytes
2021-01-22T20:33:04 [INFO]: Deployment complete
```

**Comment by hsspain** [comment] 2021-01-22 20:58
@ryanbagwell We are looking into this now.

**Comment by hsspain** [comment] 2021-01-22 21:03
@ryanbagwell We are not seeing any issues with that build or the one that happen subsequently. The build and deployment succeeded in both cases which should reflect in the console.  Are you still seeing the job stuck in the deploy phase?

**Comment by ryanbagwell** [comment] 2021-01-22 21:15
@hsspain sorry, you're right, I'm not being careful. Something's definitely wonky though. I manually cancelled several builds today but it looks like they were never cancelled as I see them listed as "succeeded."

I'll keep an eye on things and if I can be more precise I'll post back here.

**Comment by ganipcanot** [comment] 2021-02-01 17:54
Closing this for now.  If anyone is still experiencing issues please re-open and provide your `appId` and `region` so we can take a look.

**Closed by ganipcanot** 2021-02-01 17:54 UTC
Labels: work-in-progress

**Comment by zugger14** [comment] 2021-06-09 11:03
I think i am having similar issue to this one. My appId=dv86zirxr0et3 and region=eu-central-1. Thanks for any help

**Comment by anilsavani** [comment] 2022-01-24 19:45
Facing same issue that nothing gets deployed to the S3 bucket.
Though same thing is working fine if we do amplify publish from cli

appId = d2qksd9d6escp7
resion =  us-east-1

------
2022-01-24T19:33:30 [INFO]: Starting Deployment
2022-01-24T19:33:30 [INFO]: Updating Edge config
ue, buildId 0000000001
2022-01-24T19:33:30 [INFO]: Got archive: 4395275 bytes
2022-01-24T19:33:32 [INFO]: Deployment complete
