### ISSUE TITLE
Deployment failed die to permissions: not authorized to perform: amplify:ListJobs

### ISSUE THREAD

**Issue by sytolk** [aws-amplify/amplify-console#1536] opened 2021-02-04 09:38 UTC
**Describe the bug**
I want to separate app from amplify project dir and move amplify project in another git repository and git clone app here.
Yesterday deploment with amplify cli succeeded from an other github repo but today after move the same amplify project in another git repository its have error: 
```
✖ Deployment failed! Please report an issue on the Amplify Console GitHub issue tracker at https://github.com/aws-amplify/amplify-console/issues.
An error occurred during the publish operation: User: arn:aws:sts::615763143317:assumed-role/eu-central-1_uj2ZGhlMB_Full-access/amplifyadmin is not authorized to perform: amplify:ListJobs on resource: arn:aws:amplify:eu-central-1:615763143317:apps/d2pqy5x9osr3is/branches/dev/jobs/*
```

**To Reproduce**
1.  copy amplify project in another directory `amplify pull --appId d2pqy5x9osr3is --envName dev`
2. `amplify publish`

**Screenshots**
![B1BEC666-546E-48A7-99E2-8DBFBC1800DA](https://user-images.githubusercontent.com/1415463/106872638-2d132600-66dc-11eb-9eb9-e9d19e2f5cbb.jpg)

**Desktop (please complete the following information):**
 - OS: mac os

**Comment by sytolk** [comment] 2021-02-04 10:03
I can confirm that `amplify configure` is missing: https://github.com/aws-amplify/amplify-console/issues/1369#issuecomment-743929211

And the main reason for this error is that AWS profile is missing in my local-evs-info.json
```
{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "default"
  }
}
```
![5B7DBFD1-AA89-4CC3-B855-4E3787BC20BA](https://user-images.githubusercontent.com/1415463/106876988-f8ee3400-66e0-11eb-8f96-57f05bbfd6d9.jpg)

**Comment by chkrause** [comment] 2021-03-11 14:48
Also facing the same Issue:

To reproduce:
create IAM User with Policy AdministratorAccess-Amplify
call "amplify push"

![amplifyerror](https://user-images.githubusercontent.com/40870406/110804798-c9eb5500-8280-11eb-9db2-c390f5599229.png)

amplify:ListJobs is missing in policy
![image](https://user-images.githubusercontent.com/40870406/110805229-2e0e1900-8281-11eb-9c99-d666a0248aaa.png)

**Comment by Rahat-ch** [comment] 2021-03-25 04:12
Having the exact same issues as stated above, has anyone been able to find a workaround?

**Comment by sherod** [comment] 2021-03-25 04:38
I resolved this by editing amplify/.config/local-aws-info.json and duplicating the 'dev' environment

Original file:
`{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "ipms-show"
  },
  "prod": {
    "configLevel": "amplifyAdmin"
  }
}`

New file:

{
  "dev": {
    "configLevel": "project",
    "useProfile": true,
    "profileName": "ipms-show"
  },
  "prod": {
    "configLevel": "project"
    "useProfile": true,
    "profileName": "ipms-show"
  }
}

It seems to work now.

**Comment by sherod** [comment] 2021-03-25 09:43
> Having the exact same issues as stated above, has anyone been able to find a workaround?

See my comment below.

**Comment by Rahat-ch** [comment] 2021-03-25 10:10
Thank you @sherod it looks like my issue might be that the local-aws-info.json is not being generated

**Comment by ganipcanot** [comment] 2021-08-06 23:03
This managed policy should be updated:

![image](https://user-images.githubusercontent.com/21091073/128578721-bf489597-0bff-4050-bb4b-48e8ca3b259d.png)

Closing for now - if you still have an issue please re-open.

**Closed by ganipcanot** 2021-08-06 23:03 UTC
