### ISSUE TITLE
How to debug: Template format error: Resource name License 2 is non alphanumeric ?

### ISSUE THREAD

**Issue by kjetilge** [aws-amplify/amplify-console#876] opened 2020-07-14 13:39 UTC
I repatedly get the error: ```Template format error: Resource name License 2 is non alphanumeric``` after doing a few ```amplify push```

I don't do anything special. Just small changes in the schema or a function. Then when it's time too push the update this error keeps coming up.

In transform.conf.json I can see things like:
```
{
    "Version": 5,
    "ElasticsearchWarning": true,
    "StackMapping": {
        "LicensemanagersResolver": "ConnectionStack 2",
        "ManagerlicenseResolver": "ConnectionStack 2",
        "LicenseTable": "License 2",

...
```

Why does this happen ? How do I debug this ? How do I fix it ?
Could a sync service like iCloud be responsible ?

My current schema:

```
enum InstitusjonsType {
  ungdomsskole
  vgs
  annen
}

type License @model
  @auth(rules: [
    { allow: public, provider: iam, operations: [read] },
  ])
{
  id: ID!
  eier: String
  gyldigFraDato: AWSDate
  aktiv: Boolean
  ressursnummer: String
  institusjonsType: InstitusjonsType
  kontaktperson: String
  kontaktpersonEpost: AWSEmail
  adresse: String
  postnummer: String
  sted: String
  brukerantall: Int
  betalt: Boolean
  managers: [Manager] @connection(name: "LicenseManagers", sortField: "name", limit: 20)
}

type Manager @model
  @auth(rules: [
    { allow: public, provider: apiKey },
    { allow: groups, groups: ["Admin"], operations: [create, update, delete, read] }
  ])
{
  id: ID!
  name: String!
  email: AWSEmail!
  license: License @connection(name: "LicenseManagers")
}
```

``` amplify --version 4.24.1```

```node --version v10.17.0```

os: mac

**Comment by renebrandel** [comment] 2020-07-20 21:01
Transferring this to the Console repo, given that the issue is only happening on Console bulids.

**Comment by ganipcanot** [comment] 2020-07-22 15:56
Could you please share your appId and region?

And if possible could you share any steps to reproduce the issue (i.e. I cloned sample repo "X" and made these changes then ran `amplify push`)?

**Comment by kjetilge** [comment] 2020-07-24 02:25
After moving my local repo outside icloud (no longer backed up by icloud, google drive, dropbox etc), I have not experienced this problem. If it coourc again, I will report to this hread.

**Closed** 2020-08-14 17:34 UTC
Labels: pending-customer-response

**Comment by bumbleparrot** [comment] 2020-10-16 14:45
I've been experiencing this issue too. I'll try @kjetilge suggested.

**Comment by bumbleparrot** [comment] 2020-10-16 22:44
The problem also went away for me after doing the same thing in a non iCloud synced folder.

I think using an iCloud synced folder is the issue. @kjetilge

**Comment by 293nav** [comment] 2020-11-06 15:51
I am facing the issue despite moving the project to a non iCloud synced folder.

I started seeing this issue while running amplify push for the first time after deploying

**Comment by bumbleparrot** [comment] 2020-11-06 16:20
@293nav , try deleting all the generate files and re-creating the amplify resources. you probably still have a bunch of the duplicate files in the amplify backend folder.

**Comment by isbkch** [comment] 2020-11-16 00:28
I have the same issue with `amplify --version 4.32.1` on Mac Os Big Sur
it only started after I added sms notifications
