### ISSUE TITLE
Domain activation is Failed - External Domain Addition fails on Amplify

### ISSUE THREAD

**Issue by heightsInnov** [aws-amplify/amplify-console#1798] opened 2021-05-02 12:41 UTC
**App Id**: d1jlz4qc1uwfqn
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I got a response to check the CloudFront console Distribution page but I couldn't find anything there. Nothing in the list to remove.
My error is from the Amplify domain management console. It is not recognizing my domain and it is not associated to any resource, but I keep getting the same error.
I need help.

**Error message**
Error message: One or more of the CNAMEs you provided are already associated with a different resource.
<img width="1238" alt="Screenshot 2021-05-02 at 13 40 57" src="https://user-images.githubusercontent.com/13130013/116813530-0a15d800-ab4c-11eb-9002-4ea25ef84591.png">

**Comment by ferdingler** [comment] 2021-05-03 04:48
Duplicate of #1797

**Closed by ferdingler** 2021-05-03 04:48 UTC
Labels: custom-domain
