### ISSUE TITLE
New deploy process breaking redirects?

### ISSUE THREAD

**Issue by simpson** [aws-amplify/amplify-console#1201] opened 2020-11-04 12:33 UTC
** Please describe which feature you have a question about? **
We haven't made any changes to our config in months and now our production level app is down. It looks like this might be related to the major updates you pushed to fix the  amplify deploy process. Is it breaking redirect settings?

** Provide additional details**
Our production app, designed.org, is stuck in a redirecting loop and we haven't made any changes.

**Comment by simpson** [comment] 2020-11-04 12:34
@litwicki @ericclemmons @swaminator @nimacks  Any other reports of builds being broken with the new deploy process?

**Comment by ericclemmons** [comment] 2020-11-04 18:02
@simpson Is the redirect loop still happening? I just visited https://www.designed.org/ in both Chrome & Firefox (macOS) and didn't see anything out of the ordinary.  (If you have any other details (screenshot or HAR file from DevTools' Network panel), I would appreciate it)

Or is the issue with the build process within Amplify Console?

**Comment by nimacks** [comment] 2020-11-04 18:09
@simpson I'm not seeing any issues with https://www.designed.org/ in chrome or Firefox. Please send us some details if you are having issues and we'll look into this for you.

**Comment by simpson** [comment] 2020-11-04 18:51
@ericclemmons @nimacks It looks like we had about a 3hr outage, from around 0700-1000am EST. We haven't touched or changed anything on our end. It was a redirect loop returning no response. 

![Screen Shot 2020-11-04 at 1 49 45 PM](https://user-images.githubusercontent.com/1605737/98155763-c72cbd80-1ea4-11eb-976a-f2ce49ed67f9.png)

**Comment by ericclemmons** [comment] 2020-11-04 18:54
@simpson Do you have more information on the redirect loop?  I'm curious if it was a `301` / `302` or had a specific `location: ...` header to query for...

**Comment by simpson** [comment] 2020-11-04 18:56
@ericclemmons this is all I have

```
curl https://www.designed.org/index.html -I
HTTP/2 302
location: /index.html
```

**Comment by ericclemmons** [comment] 2020-11-04 19:02
@simpson Just what I needed. Thanks! That's a circular redirect for sure, so now to determine _why_. (Especially during a nearly exact 3 hour window)

**Comment by Athena96** [comment] 2020-11-06 17:49
Hi @simpson can you please share your appId

**Comment by simpson** [comment] 2020-11-06 18:17
@Athena96 We are in southeast-1

App ARN
arn:aws:amplify:ap-southeast-1:252100588959:apps/d12hn9rteao8a1

**Comment by litwicki** [comment] 2020-11-10 07:52
@simpson are you still experiencing any issues? We have not been able to reproduce or identify any issues on our end.

**Comment by simpson** [comment] 2020-11-10 11:50
@litwicki we have not had any additional outages since that, we will continue to monitor

**Comment by litwicki** [comment] 2020-11-10 18:55
@simpson thanks for following up. I'm going to close this but if anything similar happens again please reopen or create a new issue, thanks!

**Comment by simpson** [comment] 2020-11-13 13:30
@litwicki @Athena96 The ghosts in the machine strike again, we had another 3hr outage from 1:03AM EST to 4:05AM EST
![Screen Shot 2020-11-13 at 8 29 40 AM](https://user-images.githubusercontent.com/1605737/99077232-69763080-258a-11eb-8e5f-22d309364aad.png)

**Comment by simpson** [comment] 2020-11-13 14:18
I spoke with Cloudflare again and we found that the AWS origin is in fact returning high amounts of 302 in those timeframes.
 
![Screen Shot 2020-11-13 at 9 14 16 AM](https://user-images.githubusercontent.com/1605737/99081444-d1c81080-2590-11eb-8788-a224c3996483.png)

![Screen Shot 2020-11-13 at 9 17 41 AM](https://user-images.githubusercontent.com/1605737/99081642-210e4100-2591-11eb-9a26-fec0c71dbd6f.png)

**Comment by litwicki** [comment] 2020-11-13 16:57
@simpson this is the same app `arn:aws:amplify:ap-southeast-1:252100588959:apps/d12hn9rteao8a1` right? I'll ask the team to cross reference that time window on our end and see what we can find.

**Comment by simpson** [comment] 2020-11-13 16:59
@litwicki Yessir. Interesting how similar the duration is, the time is different though

**Comment by kahdojay** [comment] 2020-11-18 01:00
@simpson I do see that ordinarily the healthcheck is running constantly, requests `/`, and gets 200, but sometimes will get 302 and receive index.html which can happen if a non-existing resource is requested with a trailing slash and a 404 redirect rule is in place (which your app does have), i.e.:

```
curl -I https://www.designed.org/bogusuri/
HTTP/2 302
...
location: /index.html
...
```

So I'm wondering if any of your health checks are configured to look for a non-existing file?

The good news is that I do see 200 responses during the first reported window above (11/4 ~7am - 10am ET), bolstering the possibility that it's an issue with the health checker. However I didn't see any during the second reported window (11/13 ~1am - 4am ET), not sure if it was a quiet period.

**Comment by simpson** [comment] 2020-11-18 14:00
@kahdojay here are the settings in which Fathom uses to run, it just hits our base domain

![Screen Shot 2020-11-18 at 8 54 21 AM](https://user-images.githubusercontent.com/1605737/99539664-804ac780-297c-11eb-8df8-adb6e61c2a48.png)

**Comment by kahdojay** [comment] 2020-11-18 17:46
@simpson do you mind emailing us at aws-amplify-customer@amazon.com? I can send you some more details, it'd be worth checking with Fathom to see if they're doing any of their own checks outside of your config.

**Comment by simpson** [comment] 2020-11-18 18:11
@kahdojay email sent! Thank you for the help!

**Comment by simpson** [comment] 2020-11-19 18:10
@kahdojay @litwicki We have an active outage, hit designed.org

**Comment by kahdojay** [comment] 2020-11-20 22:21
@simpson based on our email conversation I believe we've found the cause of the outages, I'll close this for now but please reopen if you feel that the issue is still with Amplify

**Closed by kahdojay** 2020-11-20 22:21 UTC
