### ISSUE TITLE
Deployment fails to update appsync schema

### ISSUE THREAD

**Issue by kldeb** [aws-amplify/amplify-console#674] opened 2020-05-14 18:59 UTC
Intermittent issue. I occasionally have to redeploy a build because the schema changes in connected branch are not visible in the AppSync app schema tab.

**Comment by swaminator** [comment] 2020-05-14 19:48
@kldeb can you provide more details? What is your appid? What changes did you make that didn't reflect?

**Comment by kldeb** [comment] 2020-05-14 20:06
@swaminator it was a schema change - adding new queries with outside amplify project function resolver. 

Is there a delay in refreshing the AppSync schema editor page? It's there now...

By appid you mean the arn? if so: arn:aws:amplify:us-east-1:761018932039:apps/d191sgobvml2os

**Comment by swaminator** [comment] 2020-05-14 20:56
@kldeb there shouldn't be. Could you explain what you mean by 'outside amplify project function'? The steps you are taking would be helpful for us to reproduce.

**Comment by kldeb** [comment] 2020-05-14 21:02
@swaminator create a lambda custom resolver outside the amplify project. reference that lambda inside the schema using the `@function` directive then deploy via amplify console / git push.

**Comment by swaminator** [comment] 2020-05-14 22:16
Got it. So you're saying that it just takes time for the change to show up in the AppSync editor? Or it sometimes doesn't show up?

**Comment by kldeb** [comment] 2020-05-19 21:09
@swaminator it just happened again but this time a type just disappeared! i was testing and suddenly got the error that the standard get (by id) query on the type is not defined! 

the schema in my build dir has it but the schema downloaded from appsync console does not have it. 

No issues reported with the build.

**Comment by kldeb** [comment] 2020-05-20 15:28
Now a new table was dropped?!?! what the hell is going on?

**Comment by kldeb** [comment] 2020-05-20 15:35
I suspect the issue is that i deployed the wrong pk for the table so i removed the `@model` directive, redeployed then added the `@model` directive back with the proper `@key` for the pk etc...

**Comment by kldeb** [comment] 2020-05-20 17:15
Commented out new type, deployed then un-commented and deployed. that seems to be working now. Still not sure why the schema doesn't always update right away.

**Comment by kldeb** [comment] 2020-05-20 17:25
the table disappeared again.

**Comment by kldeb** [comment] 2020-05-20 17:46
it's there now because i ran `amplify push` from the cli

**Comment by swaminator** [comment] 2020-05-20 18:59
@kldeb in order to help you we need to understand the steps you took. Could you please fill in the blanks?

1. Add @model with incorrect pk
2. git push
3. Triggered a build in AC that did not make changes to the added type (???)
4. Removed @model but kept the type
5. ????
6. Added back @model 
7. `git push` that triggered a build in AC but dropped a table (??)
7. Run `amplify push` from the CLI that made the table appear again (??)

**Comment by kldeb** [comment] 2020-05-21 18:14
@swaminator this just happened again where changes committed are not showing up appsync console. 

I'll fill this in best i can: 

>     1. Add @model with incorrect pk
> 
>     2. git push
> 
>     3. Triggered a build in AC that did not make changes to the added type (???)

in this case, the changes here were done and ddb table was created with pk i defined (wrong field for key was my fault)
 
>     4. Removed @model but kept the type 
>     5. ????

committed the change to the repo and triggered a new build AC.
 
>     6. Added back @model
> 
>     7. `git push` that triggered a build in AC but dropped a table (??)

i don't know exactly because i wasn't watching but the table with the corrected pk existed then disappeared. no idea how that happened. 
 
>     8. Run `amplify push` from the CLI that made the table appear again (??)

yes, amplify push from the cli and the table was re-created and did not "disapper". 

I just experienced this issue again where the schmema changes (no ddb table changes) were not reflected on the server when i logged into appsync console. i'm currently running an amplify push from cli to fix.

**Comment by ganipcanot** [comment] 2021-08-20 18:37
@kldeb Closing for now due to the age of this issue.  If you are still seeing issues please feel free to re-open and we will investigate further.

**Closed by ganipcanot** 2021-08-20 18:37 UTC
Labels: bug
