### ISSUE TITLE
Gatsby deployment stuck in "deploy" stage

### ISSUE THREAD

**Issue by alacret** [aws-amplify/amplify-console#1464] opened 2021-01-18 14:28 UTC
**Describe the bug**
I've tried for a couple of oof days to deploy our gatsby site without any luck. I keep Canceling the build and trying to run it again via de console or sending dummy pushes without luck. 

I had in the past solved the issue by deleting the pipelines and re-creating them again, but this seems cumbersome as I have to shut down the site for a couple of hours. 

I've tried node version 10 and 12. using the other build Image provided without any luck

The Deploy stage logs:

```
2021-01-18T02:22:04 [INFO]: Starting Deployment
2021-01-18T02:22:04 [INFO]: Updating Edge config

```

And nothing else, the process won't stop, it keeps "running" until I manually cancel it.

**Expected behavior**
Consistent and predictable deployment.

**Screenshots**
<img width="1680" alt="Screen Shot 2021-01-18 at 9 26 38 AM" src="https://user-images.githubusercontent.com/918895/104927333-4e9bb000-596f-11eb-8124-7eec1923acf4.png">

NOTE:  My site is kind of large. The build usually takes 35 minutes, so maybe there is a way of resetting the images without having to delete the branches?

NOTE: Or maybe the site is too large to be hosted on Ampplify?

**Comment by hsspain** [comment] 2021-01-19 17:05
@alacret Can you provide your app ID and region so that we can look to find the root cause and resolve this issue? How long are you waiting for the deployment to finish?

**Comment by alacret** [comment] 2021-01-19 19:45
@hsspain after a few hours, I stopped the deployments. 

As a final step, I tried downgrading Gatsby version until it worked: 

"gatsby": "^2.24.92",

**Comment by hsspain** [comment] 2021-01-19 20:48
@alacret Thank you for that info.  Can you provide your app ID and region so I can look at our logs?

**Comment by alacret** [comment] 2021-01-25 14:12
@hsspain sorry that I missed this message. It was working ok, but now is stuck again:

This is the URL, I'm guessing this is the project id: `d11sorihqky0fe` 

`https://console.aws.amazon.com/amplify/home?region=us-east-1#/d11sorihqky0fe`

**Comment by ganipcanot** [comment] 2021-07-27 04:14
Closing due to age - please re-open if still experiencing issues.

**Closed by ganipcanot** 2021-07-27 04:14 UTC
Labels: pending-customer-response
