### ISSUE TITLE
403 ERROR The request could not be satisfied.

### ISSUE THREAD

**Issue by Maheshkumar094** [aws-amplify/amplify-console#581] opened 2020-04-10 06:24 UTC
**Issue I am Facing**
This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
**When it occurs?**
 While redirecting from another web app(Paytm gateway), directly to this app's path (say, https://abc.xz.com/myRedirectedPath).

**My Current amplify.yml:*
```
version: 0.1
frontend:
phases:
preBuild:
commands:
- yarn install
build:
commands:
- yarn run build
artifacts:
# IMPORTANT - Please verify your build output directory
baseDirectory: build/
files:
- '**/*'
customHeaders:
- pattern: '**/paymentCallback'
headers:
- key: 'Accept'
value: 'application/json, text/plain, */*'
- key: 'Access-Control-Allow-Methods'
value: '*'
cache:
paths:
- node_modules/**/*
```

> Its a PWA react app:
**Issue/question**
On hitting the url (say, https://abc.xz.com/myRedirectedPath), does not gives any error. But when it is redirected from other app, it shows the error. The site is served from Git and not from S3.

**Error message**
403 ERROR
The request could not be satisfied.
**Additional information from error message**
Generated by cloudfront (CloudFront)
Request ID: FEQiDffDdsFBX2Sg6Ct-IrNSFgGpe41WwHsJB5OOV-XilBKO-7PW7g==

Please help me with your valuable suggestion.
Any comment will be highly appreciated.
Thank You

**Comment by Maheshkumar094** [comment] 2020-04-11 09:30
@SwaySway 
Thank You very much for your reply
We are using Amplify Console.

**Comment by adriencg** [comment] 2020-04-13 17:20
> **When it occurs?**
> While redirecting from another web app(Paytm gateway), directly to this app's path (say, https://abc.xz.com/myRedirectedPath).
> > Its a PWA react app:
> > **Issue/question**
> > On hitting the url (say, https://abc.xz.com/myRedirectedPath), does not gives any error. But when it is redirected from other app, it shows the error. The site is served from Git and not from S3.

@Maheshkumar094 Just to clarify: You've a redirect from one app ("App A") to another ("App B") and both are Amplify-hosted web apps, correct?

**Comment by Maheshkumar094** [comment] 2020-04-13 17:52
@adriencg 
Thank You reply
No, both apps are not hosted on Amplify
We are integration Paytm payment gateway with app hosted in Amplify ("App A" & "https://AppA.amplify.com"). We provide a callback url of our app ("https://AppA.amplify.com/callback") to the payment gateway to redirect the response.
When payment gateway redirects this URL this error occurs.
I hope this will clarify your query.
Please provide your valuable suggestion we are struggling to resolving it.

**Comment by adriencg** [comment] 2020-04-15 00:29
@Maheshkumar094 One more q: Would you mind sharing your rewrite/redirect configuration? Also if you don't mind providing your appId and region:
You can find your APP-ID and REGION by looking at the amplify console:

App Settings --> General --> AppArn: It will look something like this:

arn:aws:amplify:REGION:accountId:apps/APP-ID

**Comment by Maheshkumar094** [comment] 2020-04-15 05:58
@adriencg 
Thank you for your reply
Arn:-arn:aws:amplify:ap-southeast-1:054746742825:apps/d3vjvp53w86h9f
Rewrite/ Redirect
sourece:-  /<*>
Target address:- /404.html
Type:- 404 (Rewrite)
Domain:-https://food.hexashuttle.com
Redirect Domain:- https://food.hexashuttle.com/paymentCallback
Please let us know for any other query.

**Comment by adriencg** [comment] 2020-04-15 18:44
@Maheshkumar094 I see you've a redirect set up, which is why /paymentCallback redirects to /404.html .

It's unclear why a redirect from the payment gateway would work differently w/o seeing an example URL. Would you mind providing more steps to repro the issue (you can also email us at aws-amplify-customer@amazon.com if you don't wanna post it on GH)? It's possible this is an issue with the redirects/rewrites you've configured. 403's from cloudfront mean that the requested file doesn't exist typically, although based on your rewrite/redirect rule above they should be getting rewritten to 404.html.

**Comment by adriencg** [comment] 2020-04-15 20:48
https://github.com/aws-amplify/amplify-console/issues/571 is this a duplicate issue?

**Comment by Maheshkumar094** [comment] 2020-04-16 08:25
@adriencg 
Is there is any encoding occurs on URL in amplify side because on completion of payment  amplify redirect on some arbitrary URL endpoint
 https://food.mydomain/CrVsaVO22BHWm1PRWQLsUiCzxb1guqOzlSurAjBBQ/
and this url endpoint is not constant.
We send mail on aws-amplify-customer@amazon.com with detail steps.
Thank You

**Comment by adriencg** [comment] 2020-04-17 00:26
@Maheshkumar094 Can you try a 200 rewrite instead of a 404 rewrite in your redirects/rewrites to see if that fixes the issue? Also i sent a reply for more info via email, so please check that as well. Thanks

**Comment by ShoubhikBanerjee** [comment] 2020-04-20 07:10
@adriencg . It does not work with 200 rewrite. 

Things to note : its build with ceate-react-app and does not have any backend. All server side are communicated with APIs.

**Comment by adriencg** [comment] 2020-04-20 08:39
https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa Sorry, I initially didn't understand the intended behavior/issue. This link will show you how to configure a rule which will:
- serve associated JS/CSS/image assets (based on the suffix)
- else: do a 200 redirect to the configured index.html (in your case 404.html). This preserves the location so you can take advantage of react routing.

I believe this should work for your use-case, where you want the payment callback to still display in the browser url bar, 404.html/index.html to load, and all your JS/static assets to be fetched correctly.

**Comment by ShoubhikBanerjee** [comment] 2020-04-20 10:00
@adriencg A lot hearty thanx from me and @Maheshkumar094 . Our issue was resolved by following our link and by using "Reverse Proxy Rewrite".  

The final redirect rule is : 

`[
    {
        "source": "/paymentCallback",
        "target": "https://my-domain/paymentCallback",
        "status": "200",
        "condition": null
    },
    {
        "source": "/<*>",
        "target": "/404.html",
        "status": "404-200",
        "condition": null
    }
]`

**Closed** 2020-04-20 17:14 UTC
Labels: documentation, pending-customer-response, question

**Comment by danielmhair** [comment] 2020-09-10 13:31
For those in the future that might have this issue where it gives a 403 when doing a request to the API Gateway setup by amplify, I had to make sure that the body I sent to the request (for a GET request was null). For some reason, I was passing in an object with a GET request. I received this issue. When setting the body to null for GET requests, it fixed this.

**Comment by zdebrine** [comment] 2021-01-01 20:08
> For those in the future that might have this issue where it gives a 403 when doing a request to the API Gateway setup by amplify, I had to make sure that the body I sent to the request (for a GET request was null). For some reason, I was passing in an object with a GET request. I received this issue. When setting the body to null for GET requests, it fixed this.

Lol you just saved me so much time @danielmhair
