### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Gamedoper** [aws-amplify/amplify-console#1295] opened 2020-11-26 19:01 UTC
**App Id**: d3e2xikkscic4d
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
UNABLE TO ADD SUBDOMAIN TO AWS AMPLIFY TO HOST STATIC Website

**Error message**
Error message: The status of this certificate request is "Failed". One or more domain names have failed validation due to a Certificate Authority Authentication error. Learn more:

**Additional information**
i HAVE ADDED DNS CNAME RECORDS IN MY HOSTING BUT STILL VERIFY FAILS

**Comment by cslogan-red** [comment] 2020-11-30 23:03
Closing as duplicate of #1294

**Closed by cslogan-red** 2020-11-30 23:03 UTC
