### ISSUE TITLE
[NEXTJS] Starting SSR Build...Error

### ISSUE THREAD

**Issue by andrewgadziksonos** [aws-amplify/amplify-console#1889] opened 2021-05-28 12:48 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d1i7qtt97aq61n

### Region

us-east-2

### Amplify Console feature

Logging

### Describe the bug

My NextJS application fails to build without any additional information.  The build logs contain the following,

```
2021-05-28T12:39:53.668Z [INFO]: Starting SSR Build...
2021-05-28T12:40:49.064Z [INFO]: Error
```

### Expected behavior

I would expect to see detailed error messaging around why the build is failing

### Reproduction steps

1. Launched Amplify console
2. Created a new project based on my Github repository
3. Selected defaults
4. Finished creating project, CICD kicked off - Build failed

### Build Settings

```yaml
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install --frozen-lockfile
    build:
      commands:
        - yarn build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

### Additional information

I tried using `NODE_OPTIONS=--max-old-space-size=5120` but this didnt resolve the issue

I followed along here as well

#1853
#1874
#1882

**Comment by Athena96** [comment] 2021-05-28 16:30
@andrewgadziksonos sorry you are facing this issue, i have a change that will provide better error logging which will be deployed in the coming weeks, but I looked up the build logs and it appears to be an issue with TypeScript + Webpack5: `Error: Cannot find module 'webpack'` 
I would suggest trying to downgrade your Next.js version to 10.2.0 or 10.0.0 as we only support 9.x.x: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#nextjs-version-support

**Comment by andrewgadziksonos** [comment] 2021-05-28 16:55
No worries!  Not sure how I missed that version requirement, I feel silly 😅 - I appreciate the help.  

Is there a way for me to check these logs myself or is this more of an internal log system?

**Comment by QB3L** [comment] 2021-06-04 20:12
Also having the same issue myself and wondering how I can get better logs around it. Using NextJS 10.0.8 so probably related but better logs would be appreciated

**Comment by tajindersinghminhas** [comment] 2021-06-16 22:10
Hi QB3L were you able to resolve this issue. I am also facing the same issue with NextJS 10.0.7

I am getting the following error 
`2021-06-16T21:08:30.160Z [INFO]: ----- Exported Successfully -----
2021-06-16T21:08:30.165Z [INFO]: Starting SSR Build...
2021-06-16T21:09:54.631Z [ERROR]: Internal error`

This is what my amplify.yml file looks like
`version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    # IMPORTANT - Please verify your build commands
    build:
      commands:
        - npm run build --env=dev
  artifacts:
    # IMPORTANT - Please verify your build output directory
    baseDirectory: out
    files:
      - "**/*"
  cache:
    paths:
      - node_modules/**/*
      - .next/cache/**/*
`
I have been following all these threads but no concrete resolutions.

This is what my package.json file looks like 
` "scripts": {
    "web": "node scripts/set-next-env-config.js $npm_config_env dev",
    "build": "node scripts/set-next-env-config.js $npm_config_env build",
    "start-web": "node scripts/set-next-env-config.js $npm_config_env start",
    "android": "node scripts/set-mob-env-config.js $npm_config_env run-android",
    "ios": "node scripts/set-mob-env-config.js $npm_config_env run-ios",
    "android-build": "node scripts/set-mob-env-config.js $npm_config_env run-android build",
    "start-mobile": "node scripts/set-mob-env-config.js $npm_config_env start",
    "test": "jest",
    "lint": "eslint .",
    "fastlane": "node scripts/run-fastlane.js $npm_config_env all",
    "export-ios": "node scripts/run-fastlane.js $npm_config_env ios",
    "export-android": "node scripts/run-fastlane.js $npm_config_env android"
  },`

**Comment by QB3L** [comment] 2021-06-17 15:18
Unfortunately @tajindersinghminhas  I have not been able to figure it out and opened up [this issue](https://github.com/aws-amplify/amplify-console/issues/1928) 
I have tried simplifying the project to see if I can perhaps the specific library that may be causing issues but no luck yet

**Comment by victorccccc** [comment] 2021-06-22 01:28
> Hi QB3L were you able to resolve this issue. I am also facing the same issue with NextJS 10.0.7
> 
> I am getting the following error
> `2021-06-16T21:08:30.160Z [INFO]: ----- Exported Successfully ----- 2021-06-16T21:08:30.165Z [INFO]: Starting SSR Build... 2021-06-16T21:09:54.631Z [ERROR]: Internal error`
> 
> This is what my amplify.yml file looks like
> `version: 1 frontend: phases: preBuild: commands: - npm install # IMPORTANT - Please verify your build commands build: commands: - npm run build --env=dev artifacts: # IMPORTANT - Please verify your build output directory baseDirectory: out files: - "**/*" cache: paths: - node_modules/**/* - .next/cache/**/* `
> I have been following all these threads but no concrete resolutions.
> 
> This is what my package.json file looks like
> ` "scripts": { "web": "node scripts/set-next-env-config.js $npm_config_env dev", "build": "node scripts/set-next-env-config.js $npm_config_env build", "start-web": "node scripts/set-next-env-config.js $npm_config_env start", "android": "node scripts/set-mob-env-config.js $npm_config_env run-android", "ios": "node scripts/set-mob-env-config.js $npm_config_env run-ios", "android-build": "node scripts/set-mob-env-config.js $npm_config_env run-android build", "start-mobile": "node scripts/set-mob-env-config.js $npm_config_env start", "test": "jest", "lint": "eslint .", "fastlane": "node scripts/run-fastlane.js $npm_config_env all", "export-ios": "node scripts/run-fastlane.js $npm_config_env ios", "export-android": "node scripts/run-fastlane.js $npm_config_env android" },`

Hi, currently Amplify only supports 9.x.x of Next.js https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#nextjs-version-support

Could you downgrade to Next js version and try to redeploy? and also could you provide your appId please? Thanks

**Comment by QB3L** [comment] 2021-06-22 01:53
Hey @victorccccc 
I did downgrade and was able to get more info at least, it seems there is an issue with this pg-native module which is related to the pg module for postgres connections. 

```
exitCode: 1,
                                  signal: undefined,
                                  signalDescription: undefined,
                                  stdout: 'build id: code-pipeline-1622207196156-a9bab94b10074e143e2e0ef63d73ecab8a7479e2\n' +
                                  'info  - Creating an optimized production build...',
                                  stderr: 'Browserslist: caniuse-lite is outdated. Please run:\n' +
                                  'npx browserslist@latest --update-db\n' +
                                  'Failed to compile.\n' +
                                  '\n' +
                                  "ModuleNotFoundError: Module not found: Error: Can't resolve 'pg-native' in '/codebuild/output/src546776359/src/healtharmor-nextjs/node_modules/pg/lib/native'\n" +
                                  '\n' +
                                  '\n' +
                                  '> Build error occurred\n' +
                                  'Error: > Build failed because of webpack errors\n' +
                                  '    at build (/codebuild/output/src546776359/src/healtharmor-nextjs/node_modules/next/dist/build/index.js:15:918)\n' +
                                  '    at runMicrotasks (<anonymous>)\n' +
                                  '    at processTicksAndRejections (internal/process/task_queues.js:97:5)',
                                  failed: true,
                                  timedOut: false,
                                  isCanceled: false,
Terminating logging...

```

**Comment by victorccccc** [comment] 2021-06-22 22:48
> ModuleNotFoundError: Module not found: Error: Can't resolve 'pg-native'
Ref:
1. https://github.com/nestjs/ng-universal/issues/128
2. https://stackoverflow.com/questions/41522744/webpack-import-error-with-node-postgres-pg-client

```Unfortunately, some Node.js packages (especially native bindings, e.g. pg-native in this case) cannot be easily bundled using Webpack.```

You may adjust your webpack configuration (ref #1)or ignore this plugin (ref #2)

**Comment by victorccccc** [comment] 2021-06-22 22:51
We are sorry to know this. Currently, `Internal Error` needs to be reviewed case by case. Could you provide your appId for us to lookup please? Thanks @tajindersinghminhas

**Comment by vuongnguyenthanh-agilityio** [comment] 2021-06-23 03:02
I got same this issue too. Anyone can help?
` λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-06-23T02:49:27.849Z [INFO]: Starting SSR Build...
2021-06-23T02:50:48.824Z [ERROR]: Internal error
Terminating logging...`

**Comment by victorccccc** [comment] 2021-06-23 03:11
> I got same this issue too. Anyone can help?
> ` λ (Server) server-side renders at runtime (uses getInitialProps or getServerSideProps) ○ (Static) automatically rendered as static HTML (uses no initial props) ● (SSG) automatically generated as static HTML + JSON (uses getStaticProps) (ISR) incremental static regeneration (uses revalidate in getStaticProps) 2021-06-23T02:49:27.849Z [INFO]: Starting SSR Build... 2021-06-23T02:50:48.824Z [ERROR]: Internal error Terminating logging...`

Hi, Could you provide your AppId? Thanks

**Comment by vuongnguyenthanh-agilityio** [comment] 2021-06-23 03:31
@victorccccc My AppId:  `d3r71rj9jv8heq`. Thanks for help

**Comment by victorccccc** [comment] 2021-06-23 04:04
> @victorccccc My AppId: `d3r71rj9jv8heq`. Thanks for help

@vuongnguyenthanh-agilityio We saw `AccessDenied` error in our logs, please make sure you set correct Service Role in Amplify Console, thanks.

https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#add-service-role

**Comment by vuongnguyenthanh-agilityio** [comment] 2021-06-23 05:00
@victorccccc I am using service role with policy `AdministratorAccess`. But I don't know why I got the `AccessDenied` error. Can you help to check again?

**Comment by tajindersinghminhas** [comment] 2021-06-23 05:39
@victorccccc - My App ID - d3eyxgyk7b3qii

**Comment by victorccccc** [comment] 2021-06-23 06:04
> @victorccccc I am using service role with policy `AdministratorAccess`. But I don't know why I got the `AccessDenied` error. Can you help to check again?

Hi, can you confirm `AdministratorAccess` policy is attached to `amplify-backend-role` ? I cannot reproduce your issue

**Comment by victorccccc** [comment] 2021-06-23 06:04
> @victorccccc - My App ID - d3eyxgyk7b3qii

From our logs, Error for latest build 33 is  
`Error: Cannot find module 'private-next-pages/app.mobile.js'\n" +`

We are working on the improvement of logging. Thanks for the understanding

**Comment by vuongnguyenthanh-agilityio** [comment] 2021-06-23 08:02
> > @victorccccc I am using service role with policy `AdministratorAccess`. But I don't know why I got the `AccessDenied` error. Can you help to check again?
> 
> Hi, @vuongnguyenthanh-agilityio can you confirm `AdministratorAccess` policy is attached to `amplify-backend-role` ? I cannot reproduce your issue

Thanks for your help @victorccccc. I attached `AdministratorAccess` policy into `amplify-backend-role` role. But I still got the same the isssue

**Comment by blaineo** [comment] 2021-06-24 07:03
@victorccccc I am also having this issue repeatedly. It wasn't an issue at first, but just started cropping. My appID is: dv8ybb6qjbg9d. Thanks in advance for an help

**Comment by dletozeun** [comment] 2021-07-01 09:07
Hi @victorccccc 

> From our logs, Error for latest build 33 is
> `Error: Cannot find module 'private-next-pages/app.mobile.js' at webpackMissingModule (/codebuild/output/src103070434/src/cpynew-frontend/.next/serverless/pages/app.mobile.js:143560:87)`
> 
> We are working on the improvement of logging. Thanks for the understanding

In the meantime, where can we find these logs ourselves? Can we find them on CloudWatch or run the command locally somehow? That would be very helpful to analyze a similar problem we are having.

Also, would you be so kind as to explain us what command is causing the "Starting SSR Build... Internal error" lines?

Thanks!

**Comment by alberdg** [comment] 2021-07-01 13:24
Hi, I have the same Internal error issue like some people. My appId is: d1jq8wr0iuaxel

Thanks in advance

2021-07-01T13:13:02.848Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-01T13:13:03.091Z [INFO]: Starting SSR Build...
2021-07-01T13:14:52.475Z [ERROR]: Internal error
Terminating logging...

**Comment by johnjensenish** [comment] 2021-07-01 18:48
We're also experiencing a vague internal error with increasing frequency:
```
2021-07-01T17:46:33.790Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-01T17:46:33.938Z [INFO]: Done in 23.39s.
2021-07-01T17:46:33.943Z [INFO]: Starting SSR Build...
2021-07-01T17:48:05.238Z [ERROR]: Internal error
```

My app id is: ddng4mtfv633m
Region: us-east-2
Preview branch showing error at this time: pr-47

Any additional troubleshooting advice would help. Thank you!

**Comment by kaydrohealth** [comment] 2021-07-02 20:32
Hi there, please is there update or idea on what this could be.

`2021-07-02T20:25:38.854Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-02T20:25:39.045Z [INFO]: Starting SSR Build...
Terminating logging...`

**Comment by Musbell** [comment] 2021-07-02 20:52
Same here
```
2021-07-02T20:36:35.111Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-02T20:36:35.267Z [INFO]: Done in 41.93s.
2021-07-02T20:36:35.271Z [INFO]: Starting SSR Build...
2021-07-02T20:37:59.990Z [ERROR]: Internal error
Terminating logging...
```

**Comment by noelrobinson** [comment] 2021-07-02 21:49
same error for me using next v 10

2021-07-02T21:34:32.540Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-02T21:34:32.736Z [INFO]: Starting SSR Build...
Terminating logging...

**Comment by dn-l** [comment] 2021-07-04 00:29
Got the same error with v10 and v11
```
2021-07-03T00:04:07.579Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-03T00:04:07.688Z [INFO]: Starting SSR Build...
Terminating logging...
```

**Comment by adamjamesturner93** [comment] 2021-07-05 19:35
@victorccccc, could you shine any light on when you will support NextJS v10/11? It is almost 8 months old and has some really powerful optimisations that I think most of the community would be keen to have access to.

**Comment by brainer1** [comment] 2021-07-06 14:28
also have the same problem, `d26abm7d659424`

would appreciate log clarity since it's super urgent

**Comment by dletozeun** [comment] 2021-07-06 16:04
FYI, in our case, we have contacted AWS business support and managed after a few days to get the detailed logs regarding our SSR build internal error. As said, they are currently working on improving the Amplify build log.

Regarding our particular case, if this helps some of you, we are using `next` module with `next-i18next` module for internationalization of our app. However it seems that older version of `next-i18next` are not working over the latest Amplify SSR support of Lambda@Edge. This has been fixed in recent `next-i18next` version >= 8 however this version requires `next` module version >= 10 which is not officially (but mostly) supported on Amplify.

So we are in the process of attemting to use `next` 10 anyway as we don't have any way to disable SSR on Amplify as it was before [it happened to be supported](https://aws.amazon.com/fr/about-aws/whats-new/2021/05/aws-amplify-hosting-announces-server-side-rendering-support-for-next-js-web-apps/) and the "Internal build" error we have is more specically the following:

```
Unhandled error during request: Error: Cannot find module '/codebuild/output/src174821515/src/handbook-web/next-i18next.config.js'
at webpackEmptyContext (/codebuild/output/src174821515/src/handbook-web/.next/serverless/pages/404.js:141609:10)
at /codebuild/output/src174821515/src/handbook-web/.next/serverless/pages/404.js:6356:73 {
code: 'MODULE_NOT_FOUND'
}
```

**Comment by sansmc** [comment] 2021-07-08 15:23
i have facing this issue
my App Id : d2v4k9pnfyq03v
![Screenshot from 2021-07-08 20-41-36](https://user-images.githubusercontent.com/47749578/124947721-b92fcd80-e02d-11eb-88bb-9520939ebcb6.png)

next.config.js:
------------------
const withImages = require('next-images')
module.exports = withImages({
    exportTrailingSlash: true,
    webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {
        config.optimization.splitChunks.cacheGroups = { }
        config.optimization.minimize = true;
        return config
      },
});

how to resolve this issue
thanks advance

**Comment by simpson** [comment] 2021-07-09 18:39
Same problem, seems kinda crazy that the lag time for a major version bump to be released (NextJS v11 isn't far away)

Any updates @victorccccc?

**Comment by webycel** [comment] 2021-07-13 07:42
Same problem
```
2021-07-12T12:24:24.701Z [INFO]: λ  (Server)  server-side renders at runtime (uses getInitialProps or getServerSideProps)
                                 ○  (Static)  automatically rendered as static HTML (uses no initial props)
                                 ●  (SSG)     automatically generated as static HTML + JSON (uses getStaticProps)
                                 (ISR)     incremental static regeneration (uses revalidate in getStaticProps)
2021-07-12T12:24:24.903Z [INFO]: Starting SSR Build...
Terminating logging...
```

App `d2ygnwbvrtqqk6` on `eu-central-1`

**Comment by dletozeun** [comment] 2021-07-20 14:17
FYI, we have been able to deploy recent versions of Next.js (version >= 10.x) using [Serverless Next.js Component
](https://github.com/serverless-nextjs/serverless-next.js)
Compared to Amplify frontend management, it doesn't support out of the box, multiple stage deployments (see FAQ at the end) but like it says it is very simple to use and supports recent Next.js versions as far as we have tested. 

Also it has been super helpful to get logs about the "Internal Error" we were having on Amplify. Fixing these error on serverless deployment fixed Amplify frontend builds. However in our particular case, as Amplify doesn't support the new [Next.js i18n routing](https://nextjs.org/docs/advanced-features/i18n-routing), we sticked to serverless deployment and use Amplify only for the backend deployment from now on.

Hoping this help some of you.

**Comment by Athena96** [comment] 2021-07-27 17:20
Hi all, we've recently made improvements to our SSR error logging and have added support for Next.js 10/11. 
Please follow this guide to upgrade to our latest support of Next.js: https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html#update-app-nextjs-version

**Comment by thiagozulato** [comment] 2021-07-29 13:30
@Athena96 Same error here as pointed out by @dletozeun. I have tried following the guide to upgrade my Amplify environment, but with no success. It's seems when using **NextJs i18n routing** it's not possible to use Amplify to deploy a static web site. 

```Unhandled error during request: Error: Cannot find module '/codebuild/output/src891184255/src/landing-page/next-i18next.config.js'
at webpackEmptyContext (/codebuild/output/src891184255/src/landing-page/.next//pages/index.js:61192:10)
at /codebuild/output/src891184255/src/landing-page/.next//pages/index.js:2711:73```

**Comment by RealDrewKlayman** [comment] 2021-08-05 15:53
This is most likely related to: https://github.com/aws-amplify/amplify-console/issues/2098

**Comment by hughesjj** [comment] 2021-08-16 23:16
When adding sentry to my application, the issue with webpack not being recognized/found during the SSR portion of the build started appearing for me.

This is super annoying because nextjs has essentially no built in error support, and they strongly suggest using sentry for any error handling.

**Comment by johnjensenish** [comment] 2021-08-16 23:26
> When adding sentry to my application, the issue with webpack not being recognized/found during the SSR portion of the build started appearing for me.

I'm having an issue like this, when adding `sentry/nextjs` and overriding creating error handling [like this example](https://github.com/vercel/next.js/blob/canary/examples/with-sentry/pages/_error.js). The error message I get when building is:`[DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API`

**Comment by hughesjj** [comment] 2021-08-17 00:47
I'm using aws amplify's logging instead now.  I see logs available in cloudwatch for my regional lambda@edge distribution.  Giving up on sentry for now.

**Closed** 2021-09-01 23:10 UTC
Labels: ssr

**Comment by mauliksoni110** [comment] 2021-09-30 11:41
@johnjensenish Were you able to solve that issue?
```
Failed to compile.
./node_modules/next/dist/compiled/webpack/LICENSE
Module parse failed: Unexpected token (1:10)
```

**Comment by johnjensenish** [comment] 2021-09-30 20:49
> @johnjensenish Were you able to solve that issue?
> 
> ```
> Failed to compile.
> ./node_modules/next/dist/compiled/webpack/LICENSE
> Module parse failed: Unexpected token (1:10)
> ```

No, never figured this out.

**Comment by lindsaybloomsonos** [comment] 2021-10-04 22:10
I am also experiencing this issue and am seeing this in the build console:
`
2021-10-04T21:56:06.960Z [INFO]: Starting SSR Build...
2021-10-04T21:58:55.676Z [ERROR]: Error: Command failed with exit code 1: node_modules/.bin/next build
                                  WARNING! Expected 96% more en-us product data from SFCC than available listed in Sanity
                                  (node:1677) [DEP_WEBPACK_CHUNK_HAS_ENTRY_MODULE] DeprecationWarning: Chunk.hasEntryModule: Use new ChunkGraph API
                                  (node:1677) [DEP_WEBPACK_CHUNK_ADD_MODULE] DeprecationWarning: Chunk.addModule: Use new ChunkGraph API
                                  warn  - Compiled with warnings
                                  ./node_modules/next/dist/server/load-components.js
                                  Critical dependency: the request of a dependency is an expression
                                  ./node_modules/next/dist/server/load-components.js
                                  Critical dependency: the request of a dependency is an expression
                                  ./node_modules/next/dist/server/load-components.js
                                  Critical dependency: the request of a dependency is an expression
                                  ./node_modules/next/dist/server/require.js
                                  Critical dependency: the request of a dependency is an expression
                                  ./node_modules/next/dist/server/require.js
                                  Critical dependency: the request of a dependency is an expression
                                  ./node_modules/next/dist/server/require.js
                                  Critical dependency: the request of a dependency is an expression
                                  > Build error occurred
                                  TypeError: Cannot read property 'Q' of undefined
                                  at Object.Q (/codebuild/output/src897963124/src/sonos-web-app-www/.next//pages/internal/commerce/categories/[cid].js:105:100)
                                  at Object.35957 (/codebuild/output/src897963124/src/sonos-web-app-www/.next//chunks/277.js:4437:51)
                                  at __webpack_require__ (/codebuild/output/src897963124/src/sonos-web-app-www/.next//pages/internal/commerce/categories/[cid].js:2276:43)
                                  at Object.69284 (/codebuild/output/src897963124/src/sonos-web-app-www/.next//chunks/277.js:6744:19)
                                  at __webpack_require__ (/codebuild/output/src897963124/src/sonos-web-app-www/.next//pages/internal/commerce/categories/[cid].js:2276:43)
                                  at Object.19825 (/codebuild/output/src897963124/src/sonos-web-app-www/.next//chunks/727.js:84:69)
                                  at __webpack_require__ (/codebuild/output/src897963124/src/sonos-web-app-www/.next//pages/internal/commerce/categories/[cid].js:2276:43)
                                  at Object.18912 (/codebuild/output/src897963124/src/sonos-web-app-www/.next//chunks/277.js:4685:14)
                                  at __webpack_require__ (/codebuild/output/src897963124/src/sonos-web-app-www/.next//pages/internal/commerce/categories/[cid].js:2276:43)
                                  at Object.87058 (/codebuild/output/src897963124/src/sonos-web-app-www/.next//chunks/277.js:2441:19) {
                                  type: 'TypeError'
                                  }
`

**Comment by ovdahlberg** [comment] 2021-10-07 20:36
Same issue here. Added Sentry on API Routes and now get SSR error on build.

**Comment by nshunt639** [comment] 2021-11-17 03:02
Isn't this issue solved yet? I am using Next.js v11.

**Comment by Emily-Thomas** [comment] 2021-12-15 21:55
Has this been solved at all yet? Running into the same issue.

**Comment by johnjensenish** [comment] 2021-12-15 22:21
I was able to build my app with Sentry by using [the steps in this issue](https://github.com/aws-amplify/amplify-console/issues/2427). Not sure of other implications.

**Comment by dar0xt** [comment] 2022-04-20 12:48
same issue.

**Comment by hloriana** [comment] 2022-04-20 15:47
Hi @dar0xt what error are you seeing? Can you share your appID and region?

**Comment by ronyfhebrian** [comment] 2022-04-28 09:26
I'm using NextJS v12 and getting this error, Can't resolve 'webpack'
<img width="1340" alt="Screen Shot 2022-04-28 at 16 25 06" src="https://user-images.githubusercontent.com/15209354/165721923-aae07b50-9aa3-4fad-bb09-17298bd5c7c4.png">

**Comment by jeremyrajan** [comment] 2022-05-16 06:37
Same here +1

**Comment by ocordova** [comment] 2022-05-18 21:55
Adding config to serverSideTranslations fixed it for me.
`...(await serverSideTranslations(locale, ['common'], nextI18NextConfig)),`

_Originally posted by @crathert in https://github.com/isaachinman/next-i18next/issues/990#issuecomment-943438144_
