### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by Devichand1** [aws-amplify/amplify-console#1910] opened 2021-06-02 11:33 UTC
**App Id**: d2bfm2vq7qmpea
**Region**: us-east-1
**Step**: Domain activation
**Status**: Failed

im facing some issues in DNA setup with hostinger

**Comment by nimacks** [comment] 2021-06-02 16:27
Duplicate of #1909

**Closed by nimacks** 2021-06-02 16:27 UTC
