### ISSUE TITLE
Add Gitlab branch Next button is grey

### ISSUE THREAD

**Issue by hepatus** [aws-amplify/amplify-console#446] opened 2020-02-18 08:46 UTC
Hello,

I have setup an amplify app for my reactjs website. I have deployed master branch of gitlab repository with success.

But ... when I try to connet an other branch (development in my example) I can connect to gitlab, I can see my branch list but the "next" button to add my new branch stay disabled even if I wait a very long time 

<img width="965" alt="Capture d’écran 2020-02-18 à 09 45 29" src="https://user-images.githubusercontent.com/15123428/74719009-8700ae80-5233-11ea-8e3a-977f9e15f388.png">

Can anybody help me ?
--

** Provide additional details**

**Comment by ganipcanot** [comment] 2020-02-18 17:00
Can you provide your:

**Comment by ganipcanot** [comment] 2020-02-18 17:22
Also - just curious if maybe the branch autodetection feature could help you in this case (https://aws.amazon.com/about-aws/whats-new/2019/07/aws-amplify-console-support-git-based-branch-pattern-detection/):

![image](https://user-images.githubusercontent.com/21091073/74760952-1015e680-5230-11ea-8059-8cd231a4b81a.png)

**Comment by hepatus** [comment] 2020-02-20 17:33
I tried, unfortunately it doesn't change anything. What is very strange is that one of my colleagues manages to add a branch without any problem.

appId: d3sw3i683rr12o
region : eu-west-1

**Comment by ganipcanot** [comment] 2020-02-20 18:05
@hepatus I just verified this in my test account:

Enable branch autodetection and set the autodetection pattern to "*" meaning "all" or put another way: this will autodetect all your branches automatically with no name restriction!

![image](https://user-images.githubusercontent.com/21091073/74964404-3ec6c500-53c8-11ea-9afe-3d5e2460ab2d.png)

I have observed that once you enable this feature it will not detect new branches automatically (meaning that if you only had an Amplify build for "master" branch but you also had "branch1" and "branch2" it will not pull these branches in automatically).

What you can do though is commit a change to "branch1" or "branch2" and the branch autodetection will detect the branch and build your changes.

Please give it a try and let me know if this works.

**Comment by hepatus** [comment] 2020-02-21 08:37
thank you @ganipcanot 

I tried to setup Branch autodetection and a commit on all branches but it doesn't work anymore.
My new was not added;
And when I try manually, the next button is always disabled 👍 
![image](https://user-images.githubusercontent.com/15123428/75017654-c1fe1e80-548d-11ea-8f77-f1a6b88dc325.png)

**Comment by Joycehao19** [comment] 2020-02-25 00:48
@hepatus did you try it in different browser?

**Comment by veacks** [comment] 2020-02-28 09:28
I'm having the same issue when trying to add new Gitlab branches, tried with  Firefox and Chrome.

I have this Javascript error in the Chrome console:

> Refused to load the script 'https://phd.aws.amazon.com/phd/auth?state=hashArgs' because it violates the following Content Security Policy directive: "script-src https://d25ir82nywnt3g.cloudfront.net/ https://d1b6ig1vwyrbxe.cloudfront.net/ https://media.amazonwebservices.com/urchin.js https://d2q66yyjeovezo.cloudfront.net/ https://d1ge0kk1l5kms0.cloudfront.net/ https://d18ovsmfaucn3d.cloudfront.net/". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

And this one in the Firefox one (which seems to be the same):

> Content Security Policy: The page’s settings blocked the loading of a resource at https://phd.aws.amazon.com/phd/auth?state=hashArgs (“script-src”).

Don't know if it's related.

**Comment by Joycehao19** [comment] 2020-02-28 17:35
@veacks Thank you for reporting this issue. We will work on investigation.

**Comment by abhi7cr** [comment] 2020-03-30 19:24
@hepatus @veacks This issue has been fixed in the latest release. Let us know if you still see the issue.

**Comment by hepatus** [comment] 2020-03-30 19:58
hi @abhi7cr ,
unfortunately it still doesn't work for me. I still can't add a new branch, the next button remains disabled after selecting the branch.
I tried to delete and recreate the whole amplify project but it's not better, I still only have one branch.
I also tried to activate "branch autodection" without success.

**Comment by abhi7cr** [comment] 2020-03-30 20:24
hi @hepatus. I just went to eu-west-1 and set up an app through gitlab, first for master, and then for develop. I was able to proceed with develop too:

![image](https://user-images.githubusercontent.com/5371802/77957997-3b591000-7289-11ea-9847-96ec536f4d45.png)

If possible, could you try deleting the app and reconnecting master and develop?

**Comment by abhi7cr** [comment] 2020-03-30 20:29
hi @hepatus. I just went to eu-west-1 region, and connected an app (with master) through gitlab, and then connected the develop branch:

![image](https://user-images.githubusercontent.com/5371802/77958540-0c8f6980-728a-11ea-9297-1685f1bb38a3.png)

Also in the app settings, there is a 'Reconnect repository button'. Could you try clicking that, and trying again?

**Comment by hepatus** [comment] 2020-03-30 20:50
no more success :(
![image](https://user-images.githubusercontent.com/15123428/77960608-e6dd8100-72d8-11ea-8477-ad94677eb2b4.png)

**Comment by abhi7cr** [comment] 2020-03-30 20:56
@hepatus  Is there any console errors you are seeing in the developer console? Also what's your app id.

**Comment by hepatus** [comment] 2020-03-30 21:08
@abhi7cr : Nothing in the console. No visible errors in the network traces either. my app id is d1hiceo86kcyrb

**Comment by abhi7cr** [comment] 2020-03-30 22:02
@hepatus Thanks! The only time next button is disabled is when your repository provider (in your case, gitlab) has not been connected yet.  Just to rule out the 2 branch scenario, could you create a 3rd branch in gitlab and see if you are able to reproduce? Also, is this happening with/without a refresh in between connecting the master and development branches?

**Comment by hepatus** [comment] 2020-04-01 06:32
hi @abhi7cr I have added a new branch. next button is also disabled
![image](https://user-images.githubusercontent.com/15123428/78105883-7fb3ef80-73f2-11ea-9b37-a6a0744e2130.png)

 I tried to refresh master branch and to add development branch just after but it doesn't work.

 I have exactly the same problem with an other project : I have deployed master branch successfully but i can't deploy an other branch
![image](https://user-images.githubusercontent.com/15123428/78106236-4465f080-73f3-11ea-9e32-d219635b2d88.png)

**Comment by abhi7cr** [comment] 2020-04-01 16:17
@hepatus Thanks for verifying. So this is happening only with Gitlab or other providers like Git too?

**Comment by hisham** [comment] 2020-04-16 04:31
Any update on this issue? It's been ongoing for a while and a major blocker for gitlab users (fortunately I can re-enable the button by editing the html and workaround this...)

**Comment by abhi7cr** [comment] 2020-04-16 06:40
@hisham We had fixed a general issue of the disabled next button occurring between the connection of 2 branches (without refreshing the page). But this seems to be a specific issue with gitlab. We are working on our end to reproduce this issue, and will get back to you with an update. Thanks for your patience.

**Comment by hisham** [comment] 2020-05-15 22:03
Any update on this? It's still occurring.

**Comment by abhi7cr** [comment] 2020-06-01 20:15
@hisham  Sorry for the late response. Unfortunately, we are still not able to reproduce the gitlab specific next issue in our environments. Can you share your app Id and region? To test it, we performed the following steps:
1) Connected a repo from **gitlab** in **master** branch
2) Once the build was running, we then connected the **develop** branch for the same repo. The next button was not disabled, and we were able to proceed with the build
These were the steps you followed?

**Comment by hisham** [comment] 2020-06-01 22:05
Sure app id is d2d6ty1wlg8jch. Region is us-east-1. For me I believe the next button would always be disabled even in step 1. I also did file a support ticket on Feb 28 with video of repro. Support ticket id is 6842412851.

**Comment by hisham** [comment] 2020-06-02 18:00
In chrome btw, clicking "Next" in this screen just grays out the Next button. I have to do this in Safari, and even in Safari, in the second screen, Next button goes gray but I re-enable it by editing the html: 

<img width="535" alt="AWS Amplify Console 2020-06-02 11-59-58" src="https://user-images.githubusercontent.com/81853/83553640-b7114c00-a4c8-11ea-8de2-ffd4e8b6d3c2.png">

**Comment by hisham** [comment] 2020-06-02 18:08
Actually for https://github.com/aws-amplify/amplify-console/issues/446#issuecomment-637712379 - it looks like the reason it's happening is because I have EFF Privacy Badger chrome extension installed (https://chrome.google.com/webstore/detail/privacy-badger/pkehgijcmpdhfbdbbnkijodmdjhbjlgp) and it was blocking gitlab cookie. 

After running in Chrome Incognito mode everything works fine. So you're free to close this if you want. Looks like my EFF Privacy Badger chrome extension was causing issues.

**Comment by abhi7cr** [comment] 2020-06-02 18:50
@hisham Thats great, thanks for looking into this! @hepatus do you have similar extension(s) in your Chrome browser which might be causing the gitlab cookie to be blocked?

**Comment by hepatus** [comment] 2020-06-03 05:59
hi @abhi7cr , sorry but I tried with chrome and safari, included in incognito mode, without success. 
I also tried to disable all my Chrome extensions. next button is still disabled

**Comment by LostSummer-Anson** [comment] 2020-08-25 23:29
Hello, I've ran into the same issue, and what I did was I logout and back using my manager's account, and that account uses an email exactly the same one she registered with gitLab, and all went through well. The connection is disabled again when I changed back to my own account (although authorized with many permissions).

**Comment by SourceCode** [comment] 2020-10-14 19:22
Here is my hot take on this one.

`amplify console` opens up the Amplify console.  You do a few things, then attempt to wire up a branch.  Your session at AWS isn't either fully authenticated or validated, and when you attempt to connect the branch, what happens is that the service just fails to load correctly when you are in this dialog in the AWS Amplify console.

Log out, clear session/delete browser storage/cache etc.  Log back in.  Click connect branch.  Notice the button is already orange, gitlab will connect, load, and proceed to allowing you to select a branch (its selection will be empty) and then a backend, and proceed forward.

This IMO has to do with your session in the browser at AWS.

We should be able to launch these with `amplify connect` or something from the CLI and not require the Amplify Console @ AWS.

**Comment by srchulo** [comment] 2020-12-10 03:40
I am also seeing the Next button greyed out

**Comment by jflaflamme** [comment] 2020-12-22 10:49
I opened the JavaScript console, an 
error so paused in debugger, clicked to continue and button was green ..

![image](https://user-images.githubusercontent.com/712558/102880504-0081b280-447e-11eb-8c4d-4a329878cde6.png)

**Comment by hepatus** [comment] 2021-01-19 22:13
Hi,
does anyone have any news on this subject? it's very penalizing! i still can't add branches.
in the meantime I've changed my computer, deployed new projects and it's always the same: the first branch is ok, as soon as I want to deploy a second one the button is grayed out.
Each time I have to ask a colleague who can do it every time without any problem!

**Comment by hepatus** [comment] 2021-01-19 22:16
Note that if I create a new Amplify App from the new gitlab branch ... it works. The problem occur only on multi branches deployments

**Comment by charleslouis** [comment] 2021-01-21 10:56
> Does anyone have any workaround to quickly add new branches, like eg with the aws CLI the time for the issue to be fixed?
> 
> ---- [EDIT]
> Found a quick and dirty workaround in case of (a bit hacky):
> 
> Right-click on the "next" button and select "inspect element", then in the console, remove the "disabled" attribute and the "awsui-button-disabled" class.
> 
> Then click on the "next" button and wait until the next page load (take a bit of time).
> 
> ![image](https://user-images.githubusercontent.com/417293/75537519-904e0000-5a17-11ea-92f0-2d5204f3a5f1.png)

Worked for me

**Comment by abhi7cr** [comment] 2021-02-01 21:07
hi @hepatus, 
could you tell how you connected the project ? was it through a team invite or an individual account ? We are looking to see if there are possible permission issues associated with this.

**Comment by Razin-Tailor** [comment] 2021-03-19 21:46
> > Does anyone have any workaround to quickly add new branches, like eg with the aws CLI the time for the issue to be fixed?
> > ---- [EDIT]
> > Found a quick and dirty workaround in case of (a bit hacky):
> > Right-click on the "next" button and select "inspect element", then in the console, remove the "disabled" attribute and the "awsui-button-disabled" class.
> > Then click on the "next" button and wait until the next page load (take a bit of time).
> > ![image](https://user-images.githubusercontent.com/417293/75537519-904e0000-5a17-11ea-92f0-2d5204f3a5f1.png)
> 
> Worked for me

This is weird fix. But it works!!

**Comment by pradheepbully** [comment] 2021-03-24 05:39
> > > Does anyone have any workaround to quickly add new branches, like eg with the aws CLI the time for the issue to be fixed?
> > > ---- [EDIT]
> > > Found a quick and dirty workaround in case of (a bit hacky):
> > > Right-click on the "next" button and select "inspect element", then in the console, remove the "disabled" attribute and the "awsui-button-disabled" class.
> > > Then click on the "next" button and wait until the next page load (take a bit of time).
> > > ![image](https://user-images.githubusercontent.com/417293/75537519-904e0000-5a17-11ea-92f0-2d5204f3a5f1.png)
> > 
> > 
> > Worked for me
> 
> This is weird fix. But it works!!

As a UI developer, It is a foul play but who cares it works!!

**Comment by djmlacerda** [comment] 2021-04-28 21:04
I have the same problem, and used the hack of removing the disabled of button. I'm thinking it's a delay beetwen the gitlab auth and the button, so when a gitlab responds with OK, the button dosen't refresh.

**Comment by HarrisonJackson** [comment] 2021-05-20 01:42
Ran into this today with gitlab and amplify:

1. New repo w/ master only
2. Deployed master
3. Added develop branch
4. Could not deploy develop branch because the button was disabled

Workaround:
Inspect element in chrome and remove the disabled property and the `awsui-button-disabled` class on the button element, close the dev console, then click the button and it works fine

**Comment by Nxtra** [comment] 2021-07-24 15:43
> Ran into this today with gitlab and amplify:
> 
> 1. New repo w/ master only
> 2. Deployed master
> 3. Added develop branch
> 4. Could not deploy develop branch because the button was disabled
> 
> Workaround:
> Inspect element in chrome and remove the disabled property and the `awsui-button-disabled` class on the button element, close the dev console, then click the button and it works fine

Lol, this is indeed working :)

**Comment by neonexxa** [comment] 2021-10-01 04:49
usually i just keep retry n refresh, somehow after 4-5 attempts it turns orange n able to click 'next'.. most of the time i had to do that for new branch ..

**Comment by ilya-bmi** [comment] 2021-10-31 10:17
![image](https://user-images.githubusercontent.com/38156878/139577914-15ee20b6-35a8-4ab6-941a-6fd7b1082957.png)
I have the same issue.  The next button is always disabled.

**Comment by ztdr** [comment] 2021-11-07 15:17
> Also - just curious if maybe the branch autodetection feature could help you in this case (https://aws.amazon.com/about-aws/whats-new/2019/07/aws-amplify-console-support-git-based-branch-pattern-detection/):
> 
> ![image](https://user-images.githubusercontent.com/21091073/74760952-1015e680-5230-11ea-8059-8cd231a4b81a.png)

This help me.

**Comment by Narrator** [comment] 2021-12-01 17:04
We have published a fix for this and it should now be available in all regions. Please try connecting a new branch with GitLab and let us know if you face any issues.

**Closed** 2022-01-06 01:40 UTC
Labels: bug, pending-prioritization, pending-release, work-in-progress
