### ISSUE TITLE
Build failure on amplify

### ISSUE THREAD

**Issue by manni-p** [aws-amplify/amplify-console#788] opened 2020-06-24 10:08 UTC
I am experiencing an issue with amplify and all of a sudden this error is appearing:

```
2020-06-24T09:52:50.413Z [INFO]: info Done building in 68.840799567 sec
2020-06-24T09:54:22.252Z [WARNING]: /codebuild/output/src816153359/src/383-project-website-FE-2020/amplify.sh: line 19:  1979 Killed                  npm run build
2020-06-24T09:54:22.298Z [ERROR]: !!! Build failed
2020-06-24T09:54:22.385Z [ERROR]: !!! Non-Zero Exit Code detected
2020-06-24T09:54:22.386Z [INFO]: # Starting environment caching...
2020-06-24T09:54:22.399Z [INFO]: # Environment caching completed
Terminating logging...
```

This builds successfully locally but not through amplify. The amplify.yml file is default and has been untouched.

Could we have more information on what this error is or could be?

**Comment by abhi7cr** [comment] 2020-06-24 13:28
Hi @manni-p,

Thanks for reporting. Could you share the appId and region ?

**Comment by manni-p** [comment] 2020-06-24 13:39
Hi, here are the details:

**App Id:** d3ttvrjoreeruz
**Region:** us-west-2

**Comment by VanTigranyan** [comment] 2020-06-24 20:14
> Hi, here are the details:
> 
> **App Id:** d3ttvrjoreeruz
> **Region:** eu-west-2

Hi @manni-p. If you have eslint warnings and the CI=true is set in the env variables, that can be the cause.

**Comment by manni-p** [comment] 2020-06-25 09:49
Hi - this has not resolved the problem and it was working fine before with eslint warnings

**Comment by manni-p** [comment] 2020-06-26 11:17
@VanTigranyan any more ideas?

**Comment by VanTigranyan** [comment] 2020-06-26 11:51
> @VanTigranyan any more ideas?

Hey @manni-p . I am not a contributor here. But I solved the same problem by myself on my project. Look here the last two comments are mine. Please, refer to them for solving your configuration issues https://github.com/aws-amplify/amplify-console/issues/753#issuecomment-649118098
If the configuration will not solve your issue you can download all logs when build fails, just click here when build fails to download all the logs
![image](https://user-images.githubusercontent.com/28480303/85854039-b36d9e00-b7c4-11ea-955a-3319b6141d92.png)
This will help as the was console does not provide the complete logs, and after download, you will be able to see the root cause of your problem in the complete log file. I hope this will help you.

**Comment by Athena96** [comment] 2021-08-24 17:41
closing, feel free to re-open if you are still facing this issue, thank you!

**Closed by Athena96** 2021-08-24 17:41 UTC
Labels: bug
