### ISSUE TITLE
Stripe .redirectToCheckout not working on AWS amplify but does on Netlify for example

### ISSUE THREAD

**Issue by rpostulart** [aws-amplify/amplify-console#362] opened 2020-01-15 15:45 UTC
I have got a Gatsby website created with a component that just does the redirection to stripe. 
But I receive a blank screen and I don't see any errors in the console. I have not added any customer headers. 

I also deployed the same website to Netlify without changing any variables and it's working as expected. So I expect this is an AWS Amplify issue.

Component:
```
import React from "react"
import queryString from "query-string"

let stripeHandler = undefined

class HomeIndex extends React.Component {
  componentDidMount() {
    stripeHandler = window.Stripe("********KEY*****")
    let params = queryString.parse(this.props.location.search)

    if (Object.entries(params).length !== 0) {
      stripeHandler
        .redirectToCheckout({
          // Make the id field from the Checkout Session creation API response
          // available to this file, so you can provide it as parameter here
          // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
          sessionId: params.session,
        })
        .then(function(result) {
          // If `redirectToCheckout` fails due to a browser or network
          // error, display the localized error message to your customer
          // using `result.error.message`.
        })
    }
  }

  render() {
    return <React.Fragment></React.Fragment>
  }
}

export default HomeIndex
```

**Comment by swaminator** [comment] 2020-01-15 19:16
@rpostulart what's the error you're getting?

**Comment by rpostulart** [comment] 2020-01-15 20:12
No error. As long as the session is valid here your can see the difference:

[(https://www.runyourdinner.nl/payment?session=cs_test_nSFMfxh9TW3wCmIXYyGZlpCpGbMVPoLsdIzCyJXWdT2b7R8uJcZ2TEOH)]

or

[https://ryd.netlify.com/payment?session=cs_test_nSFMfxh9TW3wCmIXYyGZlpCpGbMVPoLsdIzCyJXWdT2b7R8uJcZ2TEOH]

The second link is redirecting.

**Comment by rpostulart** [comment] 2020-01-17 18:16
@swaminator  can you reproduce it?

**Comment by Joycehao19** [comment] 2020-01-21 21:18
Hi @rpostulart , we put your question in our customer oncall list and is currently pending investigation. We'll update you when we identify the issue. Thank you!

**Comment by rpostulart** [comment] 2020-02-20 21:26
@Joycehao19 Ok, I don't know what that means, but thank you

**Comment by brnmye** [comment] 2021-02-25 18:59
Hello @rpostulart, are you still having these issues? I was unable to reproduce the issue, but may I ask what browser you are using, are there any status codes in your console log, is the app deleted or still up, and may I have your appId and region please? Thank you

**Comment by rpostulart** [comment] 2021-02-25 19:11
hi I don't have the app running anymore. I guess it was Chrome.

**Comment by brnmye** [comment] 2021-02-25 20:36
Okay I am closing this issue for now, but if you run into this issue again in the future please include the information I asked for above and you can reopen this. Thank you

**Closed by brnmye** 2021-02-25 20:36 UTC
Labels: bug
