### ISSUE TITLE
Domain activation is Failed - One or more of the CNAMEs you provided are already associated with a different resource.

### ISSUE THREAD

**Issue by TorstenS73** [aws-amplify/amplify-console#782] opened 2020-06-22 14:08 UTC
**App Id**: d10hn728d2er93
**Region**: eu-central-1
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
I am trying to add a domain which is a zone in Route53 since yesterday. It keeps failing at the final "Domain activation" step with the above mentioned error message.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
The relevant website has been hosted before on AWS within the very same account from an S3 bucket using CloudFront. I deleted the distribution in CloudFront yesterday. Still this does not help.

**Comment by abhi7cr** [comment] 2020-06-22 16:24
Hi @TorstenS73  

These guides are helpful for common custom domain issues. If those guides can not solve your issues, please let us know.
https://docs.aws.amazon.com/amplify/latest/userguide/custom-domains.html#cnamealreadyexistsexception-error

https://aws.amazon.com/premiumsupport/knowledge-center/resolve-cnamealreadyexists-error/

**Comment by TorstenS73** [comment] 2020-06-22 16:33
Tried all of this in vain several times.
Sorry, but you may need to look into the actual case.

**Comment by abhi7cr** [comment] 2020-06-22 16:44
Sure no problem. Taking a look.

**Comment by abhi7cr** [comment] 2020-06-22 17:44
Hi @TorstenS73, 

Looks like the domain is currently associated with only **one** Cloudfront distribution (_which is correct_). However, CNAME records created by your DNS provider might take some time to propagate. You might not see changes until after the DNS record has fully propagated through your DNS provider and the Time To Live (TTL) has expired on already-served DNS requests. 

Also, in your route 53 hosted zone, did you delete the CNAME which was associated with the old CF distribution?  Meanwhile, we are talking with the CF team to see if we can locate a root cause for similar issues.

**Comment by TorstenS73** [comment] 2020-06-22 19:03
Hi @abhi7cr !

> did you delete the CNAME which was associated with the old CF distribution

Yes, I did. Actually in the meanwhile more than 24 hours ago.

> until after the DNS record has fully propagated through your DNS provider

Our DNS provider is AWS. The domain is registered through a 3rd party, but the name servers are Route53.

**Comment by TorstenS73** [comment] 2020-06-22 19:07
Can you tell me *which* CNAME we are looking for here?

Queries for domain.tld as well as www.domain.tld come back with a NXDOMAIN.

I understand it's those CNAMEs which the Amplify Console wants to set and which it considers already there? Yet I cannot see them.

**Comment by abhi7cr** [comment] 2020-06-22 19:33
The **CNAME** here corresponds to your **domain name** which was attached to the CloudFront distribution. According to CloudFront, at the time of the activating the domain, there was already another CloudFront distribution which had the same CNAME (domain name), hence the error. Can you try deleting and re-adding the domain, if you haven't already?

**Comment by TorstenS73** [comment] 2020-06-22 20:53
I have now deleted the domain the Amplify-Console and re-created it with only www.domain.tld instead of the default domain.tld with a redirect to www.domain.tld. Now it seems to somehow work better.

I am still waiting for "Domain activation" to finish but I can already access the domain again.

Yet I don't know if this is because of the changed config or because you have done anything.

Sorry, but getting the website back online of course is a priority over finding the root cause, unfortunately.

**Comment by abhi7cr** [comment] 2020-06-22 21:04
@TorstenS73 we haven't changed anything on our end. Is your domain activated successfully?

**Comment by TorstenS73** [comment] 2020-06-22 21:12
Yes, we are back in business.
Maybe deleting and adding the domain again is not the same as using the "Retry" button.
Many thanks for your help.

**Comment by abhi7cr** [comment] 2020-06-22 21:35
No problem! :) Feel free to close this issue if you don't find any other related problems.

**Closed** 2020-06-23 08:26 UTC
Labels: custom-domain, pending-customer-response
