### ISSUE TITLE
Domain activation is Failed - existing wildcard Cloudfront conflict?

### ISSUE THREAD

**Issue by jaymcguinness** [aws-amplify/amplify-console#212] opened 2019-10-26 07:23 UTC
**App Id**: d3203l8rg5g22r
**Region**: eu-west-2
**Step**: Domain activation
**Status**: Failed

**Issue/question**
Should I be able to set up custom domain if I have an existing Cloudfront distro bound to wildcard domain?

I already have multiple cloudfront distros where one is bound to wildcard domain and others to specific sub-domains.  Eg.

* Cloudfront distribution #1 - *.foo.com
* Cloudfront distribution #2 - admin.foo.com

The above works directly from Cloudfront.

What I'm trying to do now is set up Amplify Console App on a custom domain - www.foo.com.

**Error message**
One or more of the CNAMEs you provided are already associated with a different resource.

**Additional information**

***What I've tried***
* Removing everything (I'm aware of) from all AWS accounts which could be bound to www.foo.com
* Waiting 12+ hours after removal and trying again
* Without apex/root domain - eg. foo.com

Cheers

**Comment by garyleefight** [comment] 2019-10-29 21:17
@jaymcguinness Sorry. You can't do this. CloudFront will not allow you to attach wild card in one distribution and subdomain in another distribution.

**Comment by jaymcguinness** [comment] 2019-10-29 21:31
Really? Cos I have exactly that working already.

**Comment by garyleefight** [comment] 2019-10-29 21:38
@jaymcguinness https://stackoverflow.com/questions/54115340/cnamealreadyexists-when-setting-a-wildcard-cname-in-a-cloudfront-distribution. 
Can you add your www.foo.com to amplify app right now?

**Comment by jaymcguinness** [comment] 2019-10-29 21:41
Sadly not - so to recap.

I can manually setup 2 distributions - one wildcard, one subdomain and it works.  

I removed the manually created www.foo.com distribution, waited 12 hours and tried to create www.foo.com via Amplify app, but it fails with above error.

**Comment by garyleefight** [comment] 2019-10-29 21:48
@jaymcguinness . Looks like your www. domain is still attached to a cloudFront distribution.
It's in account 087xxxx22640 with distribution ID: d3glvhegruywac.
That should be the root cause

**Comment by jaymcguinness** [comment] 2019-10-29 21:50
HI @garyleefight 

Lol - no, that's me just creating it again (just now) manually to check I wasn't going mad!

**Comment by jaymcguinness** [comment] 2019-10-29 21:51
Feel free to close - and I'll re-create the problem and open a new issue if that's easier.

**Comment by Athena96** [comment] 2020-09-16 16:54
Closing this issue, please feel free to re-open if you are still facing issues.

**Closed by Athena96** 2020-09-16 16:54 UTC
Labels: custom-domain
