### ISSUE TITLE
Deploy fails when tests are present

### ISSUE THREAD

**Issue by jkar32** [aws-amplify/amplify-console#283] opened 2019-12-02 11:47 UTC
**Abbreviated problem**
Angular app builds and tests successfully, but deploy fails with. 
```
2019-12-02T11:26:22 [INFO]: Starting Deployment
2019-12-02T11:26:22 [ERROR]: Failed to deploy
2019-12-02T11:26:22 [INFO]: Deployment finished.
```

**Details**
I created a new angular project, not in the base directory but such that the file structure was so:
```
.
+-- amplify.yml
+-- amplify
|   +-- ...
+-- frontend
|   +-- angular.json
|   +-- package.json
|   +-- ...
```
And with amplify.yml contents
```
version: 1.0

frontend:
  phases:
    preBuild:
      commands:
        - cd frontend
        - npm ci
    build:
      commands:
        - npm run build-prod
  artifacts:
    baseDirectory: frontend/dist
    files:
      - '**/*'
  cache:
    paths:
      - frontend/node_modules/**/*
test:
  phases:
    preTest:
      commands:
        - cd frontend
        - npm ci
    test:
      commands:
        - npm run test-ci
  artifacts:
    baseDirectory: frontend/coverage
    files:
      - '**/*'
```

In the amplify console the build and tests complete successfully but the deploy fails (error seen above) without any description. If I remove the test section in the `amplify.yml` then the app successfully deploys

**To Reproduce**
1. Set up a new repo with angular in a subfolder
2. Create  amplify.yml as stated above
3. connect to amplify
4. See an error in the deploy part of the pipeline

**Expected behavior**
The app too successfully deploy

**Comment by justinharding** [comment] 2020-01-06 21:56
I also have this problem - deploy fails only if I run tests - if I override the environment variable USER_DISABLE_TESTS so that tests are not run, deployment succeeds. My yml file

version: 0.1
frontend:
  phases:
    preBuild:
      commands:
        - nvm install lts/erbium
        - nvm use lts/erbium
        - yarn install
    build:
      commands:
        - nvm use lts/erbium
        - yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

test:
  phases:
    test:
      commands:
        - mkdir -p ./test
        - 'yarn run test --watchAll=false > ./test/test_results.txt'
  artifacts:
    baseDirectory: test
    files:
      - '**/*.txt'

**Comment by cslogan-red** [comment] 2020-01-16 01:26
Related to the latest explanation on #115 and is pending release.

**Comment by litwicki** [comment] 2020-10-19 03:35
Closing this as duplicate of https://github.com/aws-amplify/amplify-console/issues/115 that we're in-progress fixing.

**Closed by litwicki** 2020-10-19 03:35 UTC
Labels: bug, pending-release

**Comment by hanna-becker** [comment] 2021-03-29 04:08
We are still observing this exact issue even though this and the duplicate issue has been closed. We are running Angular tests in the test stage. The test stage passes. Afterwards the deployment fails with the above mentioned error. If we skip the test stage all other stages work fine.

**Comment by kshitijcode** [comment] 2022-05-09 08:13
Still observing this issue.

**Comment by kibolho** [comment] 2022-06-28 11:25
I noticed that the script that runs in the test pass changes the build artifacts which can affect the pipeline, I don't know if it can be related to the case.
