### ISSUE TITLE
Backend build warning: "Could not read cloudformation template at path"

### ISSUE THREAD

**Issue by houmark** [aws-amplify/amplify-console#10] opened 2019-07-09 03:58 UTC
**Which Category is your question related to?**

CLI and Console at the same time.

**What AWS Services are you utilizing?**

I'm running multienv, got the usual `dev` and `prod`. Project is live. To push API or function changes faster I like to use the CLI. To release in full and to deploy to production, I like to merge to my master branch and have it trigger the automatic production build. For testing major changes before deploying to production, I like to push to my develop branch and have it build also using the Console.

Here's what I'm confused about:

* The Console seems to not really care much about the overall state and just pushes according to the CloudFormation templates pulled from the branch, but could it be missing some files that are ignored in my Git?
* The CLI seems to get out of sync and not know what's the current status when Console is also deploying
* Doing `amplify env pull` does not get the CLI up to speed if I my latest deployment is with the Console. Only when I do `amplify push`, the CLI will say "No Change" for all functions and API's.

So my question is. How do I bring both in sync and do I risk any bad overwrites doing `amplify push` if I don't do `amplify env pull` after having deployed with Console?

I thought `amplify env pull` would also pull the cloud down? `amplify pull env --restore` seems a bit dangerous and I'm worried it could overwrite locally changed files?

**Comment by timothy-baker** [comment] 2019-09-24 19:59
I'm running into this issue now. CLI v3.2.0. Here are my build logs:

```
                                 # Starting phase: build
                                 # Executing command: amplifyPush --simple
2019-09-24T19:44:08.047Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-09-24T19:44:08.054Z [INFO]: # Start initializing Amplify environment: dev
2019-09-24T19:44:08.056Z [INFO]: STACKINFO={
                                 "awscloudformation": {
                                 "AuthRoleName": "MYAPP-admin-portal-dev-20190905221435-authRole",
                                 "UnauthRoleArn": "arn:aws:iam::012345678910:role/MYAPP-admin-portal-dev-20190905221435-unauthRole",
                                 "AuthRoleArn": "arn:aws:iam::012345678910:role/MYAPP-admin-portal-dev-20190905221435-authRole",
                                 "Region": "us-west-2",
                                 "DeploymentBucketName": "MYAPP-admin-portal-dev-20190905221435-deployment",
                                 "UnauthRoleName": "MYAPP-admin-portal-dev-20190905221435-unauthRole",
                                 "StackName": "MYAPP-admin-portal-dev-20190905221435",
                                 "StackId": "arn:aws:cloudformation:us-west-2:012345678910:stack/MYAPP-admin-portal-dev-20190905221435/755955d0-d054-11e9-b96f-0ae846f1e916"
                                 },
                                 "categories": {
                                 "function": {
                                 "MYAPPAuthPreTokenGeneration": {},
                                 "MYAPPAuthAdminFunctions": {}
                                 },
                                 "auth": {
                                 "MYAPPAuth": {}
                                 }
                                 }
                                 }
                                 # Importing Amplify environment: dev (amplify env import)
2019-09-24T19:44:15.694Z [INFO]: Successfully added environment from your project
2019-09-24T19:44:15.748Z [INFO]: # Initializing existing Amplify environment: dev (amplify init)
2019-09-24T19:44:19.220Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-09-24T19:44:20.260Z [WARNING]: - Initializing your environment: dev
2019-09-24T19:44:20.577Z [WARNING]: ✔ Initialized provider successfully.
2019-09-24T19:44:20.746Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src999090617/src/MYAPP-admin-portal/amplify/backend/api/MYAPPApi/build/cloudformation-template.json
2019-09-24T19:44:20.803Z [WARNING]: - Updating resources in the cloud. This may take a few minutes...
2019-09-24T19:44:26.313Z [INFO]: 
2019-09-24T19:44:26.317Z [INFO]: UPDATE_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435 AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:21 GMT+0000 (Coordinated Universal Time) User Initiated
                                 UPDATE_IN_PROGRESS storagecontent                        AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:23 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS functionMYAPPAuthPreTokenGeneration   AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:24 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    storagecontent                        AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:24 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    functionMYAPPAuthPreTokenGeneration   AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:24 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:44:31.300Z [INFO]: 
2019-09-24T19:44:31.301Z [INFO]: UPDATE_IN_PROGRESS authMYAPPAuth AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:26 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:44:31.445Z [INFO]: 
2019-09-24T19:44:31.447Z [INFO]: UPDATE_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435-authMYAPPAuth-1IJB7V8A2FDIU AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:27 GMT+0000 (Coordinated Universal Time) User Initiated
2019-09-24T19:44:36.395Z [INFO]: 
2019-09-24T19:44:36.396Z [INFO]: UPDATE_IN_PROGRESS UserPool AWS::Cognito::UserPool Tue Sep 24 2019 19:44:33 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    UserPool AWS::Cognito::UserPool Tue Sep 24 2019 19:44:35 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:44:51.416Z [INFO]: 
2019-09-24T19:44:51.418Z [INFO]: UPDATE_COMPLETE_CLEANUP_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435-authMYAPPAuth-1IJB7V8A2FDIU AWS::CloudFormation::Stack Tue Sep 24 2019 19:44:50 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:06.319Z [INFO]: 
2019-09-24T19:45:06.320Z [INFO]: UPDATE_COMPLETE             authMYAPPAuth                         AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:01 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS          apiMYAPPApi                           AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:04 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_FAILED               apiMYAPPApi                           AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:04 GMT+0000 (Coordinated Universal Time) Parameters: [unauthRoleName, authRoleName] do not exist in the template
                                 UPDATE_ROLLBACK_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435 AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:05 GMT+0000 (Coordinated Universal Time) The following resource(s) failed to update: [apiMYAPPApi].
2019-09-24T19:45:16.394Z [INFO]: 
2019-09-24T19:45:16.396Z [INFO]: UPDATE_IN_PROGRESS functionMYAPPAuthPreTokenGeneration AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:11 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS storagecontent                      AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:11 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    functionMYAPPAuthPreTokenGeneration AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:11 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE    storagecontent                      AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:11 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS authMYAPPAuth                       AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:12 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:16.551Z [INFO]: 
2019-09-24T19:45:16.553Z [INFO]: UPDATE_ROLLBACK_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435-authMYAPPAuth-1IJB7V8A2FDIU AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:12 GMT+0000 (Coordinated Universal Time) User Initiated
                                 UPDATE_IN_PROGRESS          UserPool                                                          AWS::Cognito::UserPool     Tue Sep 24 2019 19:45:14 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE             UserPool                                                          AWS::Cognito::UserPool     Tue Sep 24 2019 19:45:16 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:21.427Z [INFO]: 
2019-09-24T19:45:21.429Z [INFO]: UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435-authMYAPPAuth-1IJB7V8A2FDIU AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:20 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:26.322Z [INFO]: 
2019-09-24T19:45:26.324Z [INFO]: UPDATE_COMPLETE                              authMYAPPAuth                         AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:23 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE                              apiMYAPPApi                           AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:24 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS MYAPP-admin-portal-dev-20190905221435 AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:25 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS                           apiMYAPPApi                           AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:26 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS                           storagecontent                        AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:26 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:26.534Z [INFO]: 
2019-09-24T19:45:26.535Z [INFO]: UPDATE_COMPLETE apiMYAPPApi    AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:26 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE storagecontent AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:26 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:31.348Z [INFO]: 
2019-09-24T19:45:31.349Z [INFO]: UPDATE_IN_PROGRESS authMYAPPAuth AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:26 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:31.439Z [INFO]: 
2019-09-24T19:45:31.439Z [INFO]: UPDATE_ROLLBACK_COMPLETE MYAPP-admin-portal-dev-20190905221435-authMYAPPAuth-1IJB7V8A2FDIU AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:27 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:41.365Z [INFO]: 
2019-09-24T19:45:41.367Z [INFO]: UPDATE_COMPLETE          authMYAPPAuth                         AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:37 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_IN_PROGRESS       functionMYAPPAuthPreTokenGeneration   AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:37 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_COMPLETE          functionMYAPPAuthPreTokenGeneration   AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:38 GMT+0000 (Coordinated Universal Time)
                                 UPDATE_ROLLBACK_COMPLETE MYAPP-admin-portal-dev-20190905221435 AWS::CloudFormation::Stack Tue Sep 24 2019 19:45:38 GMT+0000 (Coordinated Universal Time)
2019-09-24T19:45:51.408Z [WARNING]: Error updating cloudformation stack
2019-09-24T19:45:56.413Z [INFO]: Following resources failed
2019-09-24T19:45:56.416Z [INFO]: init failed
                                 { ResourceNotReady: Resource is not in the state stackUpdateComplete
                                 at constructor.setError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:182:47)
                                 at Request.CHECK_ACCEPTORS (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/resource_waiter.js:44:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 message: 'Resource is not in the state stackUpdateComplete',
                                 code: 'ResourceNotReady',
                                 retryable: false,
                                 time: 2019-09-24T19:45:51.408Z,
                                 statusCode: 200,
                                 retryDelay: 30000 }
2019-09-24T19:45:56.417Z [WARNING]: ✖ An error occurred when pushing the resources to the cloud
                                    ✖ There was an error initializing your environment.
2019-09-24T19:45:56.460Z [ERROR]: !!! Build failed
2019-09-24T19:45:56.588Z [ERROR]: !!! Non-Zero Exit Code detected
2019-09-24T19:45:56.588Z [INFO]: # Starting environment caching...
2019-09-24T19:45:56.588Z [INFO]: # Uploading environment cache artifact...
2019-09-24T19:45:56.700Z [INFO]: # Environment caching completed
Terminating logging...
```

**Comment by swaminator** [comment] 2019-09-24 23:33
@timothy-baker @nino-moreton @houmark: We root caused the issue to the `amplify/backend/api/myapi/build/` folder not being checked into source control. As a workaround, please run `amplify gql-compile` and `amplify push --yes` from your local machine, and check the `build` folder into source control (EXCEPT for the `amplify/backend/api/myapi/build/parameters.json`file). With the next CLI release we will fix this to ensure customers do not face a similar issue.

**Comment by RossWilliams** [comment] 2019-09-25 09:48
@swaminator Can you please link to the CLI issue or PR to track this issue?

Are you stating that including the build folder in git should be done going forward, or that this is a temporary workaround.

**Comment by thedgbrt** [comment] 2019-09-25 10:51
Since I need auto-deploy to work, I found a temporary fix that works for my existing environment (but not for feature branches where new environments are created by the console directly). Hope it can help anyone.

https://gist.github.com/thedgbrt/11158b45df9bc79dd0e8869b5412b19d

**Comment by thedgbrt** [comment] 2019-10-02 08:19
@swaminator what's the progress status? I still can't build existing branches (so basically, all main branches) without using the hacky workaround I posted above. If I want to test on a separate branch / environment, I have to switch the build command to the normal amplifyPush for the first build, and then switch to my hack again. This bug really makes the whole process much more complicated than it needs to be...

**Comment by swaminator** [comment] 2019-10-07 19:48
@thedgbrt we're going to merge this PR today: https://github.com/aws-amplify/amplify-cli/pull/2003

Will update you once it's merged.

**Comment by swaminator** [comment] 2019-10-10 04:36
@thedgbrt @Cas-Laputa the new version of the CLI is out (3.12.0). Can you please verify it works for you. Thanks for your patience.

**Comment by thedgbrt** [comment] 2019-10-10 09:14
@swaminator I just tried it, it has the same issue: `Could not read cloudformation template at path...` and then the build step fails.

I double checked that I was using amplify 3.12.0 override in the console.

I am not sure I understand the fix properly though. Does the cli now generates a new file on build that I should add to my repo? I did a new build locally (with 3.12.0) but couldn't see anything relevant added to my git state.

Here are my config files if that helps:

`amplify.yml`:
```yml
version: 0.1
backend:
  phases:
    preBuild:
      commands:
        - export NPM_TOKEN=$NPM_TOKEN
        - export GATSBY_RECAPTCHA_KEY=$GATSBY_RECAPTCHA_KEY
        - echo -e "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        - echo -e "GATSBY_RECAPTCHA_KEY=${GATSBY_RECAPTCHA_KEY}" > ~/.env.production
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
```

`.gitignore`:
```
amplify/\#current-cloud-backend
amplify/.config/local-*
amplify/mock-data
amplify/backend/amplify-meta.json
amplify/backend/awscloudformation
build/
dist/
node_modules/
aws-exports.js
awsconfiguration.json
```

**Comment by swaminator** [comment] 2019-10-11 05:21
@thedgbrt give it another shot it got merged.

**Comment by swaminator** [comment] 2019-10-11 23:45
@thedgbrt thanks for your patience - we actually found the root cause was something else. We released `3.13.0`. Please give that a shot.

**Comment by thedgbrt** [comment] 2019-10-14 08:24
@swaminator I tested a few scenarios and all seem to be working fine 👍🥳

**Comment by swaminator** [comment] 2019-10-14 19:21
Thanks! Closing this issue.

**Closed by swaminator** 2019-10-14 19:21 UTC
Labels: backend, bug
