### ISSUE TITLE
SSL verification is Running - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by vshamgin** [aws-amplify/amplify-console#230] opened 2019-11-05 21:37 UTC
**App Id**: d3d6p5ntxrs01j
**Region**: us-west-2
**Step**: SSL verification
**Status**: Running

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
A clear and concise description of what the issue/question is.

**Error message**
If there is an error message, please include it here. 
**Note**: Be sure to check the message for sensitive information. 

**Additional information**
Please add any other relevant information. Please feel free to include screenshots.

Domain:

https://everhint.com | master | https://www.everhint.com

https://www.everhint.com

It's been more than 24 hours when it stuck at this stage and almost a week I am trying to set up my domain via Amplify/Route 53.
"We validated that the CNAME record exists in your DNS file. We will now verify ownership of the domain. If this takes longer than 8 hours, please create an issue in our GitHub issue tracker."

**Comment by vshamgin** [comment] 2019-11-06 21:00
Guys, It's been I am stuck on every step while trying to set up my domain with you. C'mmn!

**Comment by Joycehao19** [comment] 2019-11-16 00:27
@vshamgin Sorry for the late response. It seems like your domain is working. 
 
If you have this issue in the future, you could try:

[1]. Go to the domain manage page and click the re-try button
If [1] doesn't work, you could try:
[2]. Delete your current failed domain and try to add it again

**Comment by Joycehao19** [comment] 2019-11-16 00:29
duplicate of #57

**Closed** 2020-01-03 21:44 UTC
Labels: custom-domain, duplicate, pending-customer-response
