### ISSUE TITLE
Problems with routes and 404 page on Gatsby site in AWS Amplify

### ISSUE THREAD

**Issue by anatolzak** [aws-amplify/amplify-console#886] opened 2020-07-23 08:47 UTC
I have created a multi-page site with gatsby.js deployed on Amplify.

When I go to any page other than index.html, it shows me my 404.html and then after a few seconds, it shows the actual page I should see for that route.

Obviously there is something wrong with that. I deployed the same site with Netlify and that doesn't happen there.

Here are my Rewrites and redirects:

![image](https://user-images.githubusercontent.com/53095479/88267889-31489a80-ccda-11ea-8edf-68685c5c24cc.png)

**Comment by ohlr** [comment] 2020-07-27 12:42
`</index\.html/> ->  /404.html`

**Comment by anatolzak** [comment] 2020-07-27 15:05
@ohlr that worked by it doesn't keep query params.

**Comment by ohlr** [comment] 2020-07-27 15:52
there is a whole discussion here https://github.com/aws-amplify/amplify-console/issues/70..

**Comment by fpsoriano** [comment] 2020-07-31 19:45
I have the same problem.

https://www.apresentar.me/fabricio => does not work
https://www.apresentar.me/fabricio/ => works.

Did you find a solution?

**Comment by anatolzak** [comment] 2020-08-01 05:00
@fpsoriano I haven’t yet found a solution. I have been using Netlify instead because everything works perfectly with them. 

I wish deploying to amplify didn’t include having to figure out weird bugs that simply aren’t supposed to be part of the platform :(

**Comment by cslogan-red** [comment] 2020-08-03 21:25
As noted by @ohlr the solution in #70 is currently the accepted solution for 404 rewrite behavior. As far as query string params, the target address currently only supports path based params used by most router frameworks, not the transposition of a query string, IE, the below is valid:

Source is: /docs?id=\<resourceId\>&hat=\<hat\>
Target is: /documents/\<resourceId\>/\<hat>

But the following is **not currently directly supported** ( see #97 )

Source is: /docs?id=\<resourceId\>&hat=\<hat\>
Target is: /documents?id=\<resourceId\>&hat=\<hat\>

That said, as others have mentioned in #97 , you can use a _trailing slash with a wildcard_ (the trailing slash is required) in the source to redirect everything (including anything you want preserved in the query string) from one path to another:

Source is: /docs/\<\*\>
Target is: https://myurl.com/<\*\>

Closing this as a duplicate of #70 and #97, please follow those issues for updates and let us know if you have any further questions in either of those issues, thanks!

**Closed by cslogan-red** 2020-08-03 21:25 UTC
