### ISSUE TITLE
Backend Environments Tab in Amplify Console is Empty

### ISSUE THREAD

**Issue by jhoffmcd** [aws-amplify/amplify-console#408] opened 2020-02-04 22:53 UTC
** Please describe which feature you have a question about? **

The tab in Amplify that is supposed to show Backend Environments seems to be empty in my project, even though we have definitlely have two declared environments.

** Provide additional details**

What is actually supposed to show here? We have two environments that do seem to work other than what we see in this tab. Here is what we are seeing in the tab:

![Screen Shot 2020-02-04 at 2 54 22 PM](https://user-images.githubusercontent.com/2348095/73794900-421e4780-475e-11ea-913b-422a0e1c3bb3.png)

However, we do see environments when we use the CLI tool or when we try to connect a branch:

![Screen Shot 2020-02-04 at 2 52 05 PM](https://user-images.githubusercontent.com/2348095/73794827-1ac77a80-475e-11ea-8b96-b3979c51a8ae.png)

Is there a way to connect these two so I can see what value this tab section brings to my team?

**Comment by ganipcanot** [comment] 2020-02-06 17:19
@jhoffmcd Does your application only have a front-end?  Or does it also have a back-end?  Also could you provide your app-id (app ARN) in order to assist you further?  Thanks!

If your application has only deployed a front-end then you wouldn't see a backend environment.

**Comment by jhoffmcd** [comment] 2020-02-06 20:58
It does also have a backend (auth/cognito) component.

App ARN: arn:aws:amplify:us-west-2:059525859496:apps/d2zqif4mv6lhdb

**Comment by Joycehao19** [comment] 2020-02-11 05:48
Hi @jhoffmcd , this is a known issue for us. We are still investigating a fix to pass custom parameters when creates backend env. The current workaround is here: https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-552548466

**Comment by jhoffmcd** [comment] 2020-02-12 04:22
Thanks for the update @Joycehao19, I'm glad to hear the team is on it. I can probably wait of a true fix to this, the work around looks to be a bit bulky and we are able to survive with out it for a while longer I think.

**Comment by Joycehao19** [comment] 2020-02-12 19:57
@jhoffmcd what version of the CLI are you using?

**Comment by jhoffmcd** [comment] 2020-02-13 18:17
Looks like `4.13.1`

**Comment by jhoffmcd** [comment] 2020-02-27 19:09
An update on this, I added a 3rd env, "staging" and that **did** show up in the console, but the other two environments are still lost to the ether... :(

![Screen Shot 2020-02-27 at 11 09 12 AM](https://user-images.githubusercontent.com/2348095/75477726-9aa5c680-5951-11ea-91c0-33cd4954e3ae.png)

**Comment by Joycehao19** [comment] 2020-02-27 19:53
@jhoffmcd To clarify your issue, do you mean that: you created 2 env by amplify cli,  then `amplify push`, but didn't see any backend env. Then you added 3rd env, "staging", then `amplify push`. The app only has 1 backend "staging". In your `team-provider-info.json`, it contains all 3 env.

If you re-create a new project, add env (`amplify init` + your custom setting), do `amplify push`, do you have the same issue? 

I can't reproduce your issue. I did `amplify init` (create env abc) + `amplify add auth` + `amplify auth update` + `amplify init` (create env prod) + `amplify push`, I got 2 backend env on my console..

**Comment by jhoffmcd** [comment] 2020-02-27 20:07
@Joycehao19 correct, we had 2 for a long time, which never showed up in the console, we just added a third one (which did add to the `team-provider-info.json`).

I can try to do this in a brand new project. It should be worth noting that the first two environments were created around 10 months ago, and this new one was created a few days ago. Maybe older environments are not setup to show in the console?

**Comment by Joycehao19** [comment] 2020-02-27 21:45
@jhoffmcd That might be the reason. We launched the front-end and back-end list in recent 4 months. The new back-end environments would be showed on console.

**Comment by jhoffmcd** [comment] 2020-03-03 01:29
So for these old environments, is there nothing we can do to get the console to read those correctly? We don't want to reset everything because we would have to migrate users to the new user pools created by the CF template.

**Comment by H6** [comment] 2020-05-13 13:57
> @jhoffmcd That might be the reason. We launched the front-end and back-end list in recent 4 months. The new back-end environments would be showed on console.

Hi. And old ones will never be visible here? 

I have an old amplify project. And I just migrated to the current CLI and was also wondering, that the backend tab was empty.

**Comment by swaminator** [comment] 2020-09-15 05:38
@jhoffmcd @H6 are you still facing this issue?

**Comment by H6** [comment] 2020-09-15 05:48
> @jhoffmcd @H6 are you still facing this issue?

Yes, my backend tab is still empty in the console.

**Comment by jhoffmcd** [comment] 2020-09-15 18:59
@swaminator I don't work on that project anymore so I can't say for sure.

**Comment by RossWilliams** [comment] 2020-09-15 19:47
I still have the issues with multiple apps. They became duplicated in the console, and the “active” app has an empty backend tab.

**Comment by dylan-westbury** [comment] 2020-10-01 06:31
I am facing this issue for a next.js frontend, for a react native and reactjs frontend it is fine

**Comment by lucafronterotta** [comment] 2020-11-23 11:17
Hello all,I'm having the same problem, my backend console is empty even if the services I configured (analytics, notifications, pinpoint) are working well.

The strange thing I see is that:
- if I create everything from my personal AWS account with administration rights everything is ok and I can see the backend in the Amplify console;
- if I create everything from my Company account where I have limited rights services works well but backend in Amplify is missing, but I get no errors while doing all the configurations.

What I do is:
- create a react native app
- amplify init (creating a single environment)
- amplify add notifications
- amplify add analytics
- amplify push

Could it be a rights problem (missing policies?!?) on my Company account?
Is it possible to have a list of rights mandatory to use Amplify CLI and push everything to the cloud?

Thanks in advance.

**Comment by lucafronterotta** [comment] 2020-11-24 10:33
I solved the problem requesting amplify:* permissions on my AWS Company account; it seems that the Amplify web console, when permissions are missing, simply tells that you have no backend instead of saying something like "You have no right to do this task"

**Comment by ganipcanot** [comment] 2021-08-20 18:35
Resolving this issue based on the update to permissions on your end.

Feel free to re-open if still experiencing issues.

**Closed by ganipcanot** 2021-08-20 18:35 UTC
Labels: bug, pending-prioritization
