### ISSUE TITLE
Query params being removed

### ISSUE THREAD

**Issue by dhoulker** [aws-amplify/amplify-console#792] opened 2020-06-25 07:00 UTC
** Please describe which feature you have a question about? **

Hello, i'm working on a gatsby site deployed using AWS Amplify console, and i'm having problems with URL params.

** Provide additional details**

Steps to reprodcue:

- Navigate to page on site, eg /page-2/ - works ✅
- Navigate to same page with url params /page-2?a=b - ❌  fails - i get redirected back to just /page-2/

I have just on rewrite set up:

![image](https://user-images.githubusercontent.com/5832261/85671437-c778a900-b6b9-11ea-80d6-f7321f1209b5.png)

```
[
    {
        "source": "</^[^.]+$|\\.(?!(css|gif|ico|jpg|js|png|txt|svg|woff|ttf|map|json)$)([^.]+$)/>",
        "target": "index.html",
        "status": "200",
        "condition": null
    }
]
```

Do i need another rule so i can use url params?

Thanks!

**Comment by abhi7cr** [comment] 2020-06-25 14:55
Hi @dhoulker,

The rule you have is for Single Page Applications in general (_any route that doesn’t explicitly request for the file extensions mentioned in the rule would be redirected to index.html_). 
This means all the routing is done on the client side. You would have to define a client route that extracts the query strings on your client router. https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication.

Let me know if you have any questions.

**Comment by adamJLev** [comment] 2020-07-17 16:57
Having the same issue, I think this has nothing to do with Single Page Apps @abhi7cr.

The issue is clear when you need tracking params in the URL, and for some reason somebody is linking to it without a slash at the end:

**This is happening:**
`/product?utm_source=google` redirects to `/product/`

**Expected behavior:**
`/product?utm_source=google` redirects to `/product/?utm_source=google`

By the way, this is on a total vanilla/unmodified new amplify projects. I dont have any redirects set or anything. 
Keeping query params in there is important for many reasons.

**Comment by genert** [comment] 2020-07-26 15:04
Same problem here.

The workaround is to add slash at the end of the URL before query params start.

Therefore `/product?utm_source=google` becomes `/product/?utm_source=google` - the latter should work.

**Comment by swaminator** [comment] 2020-09-15 05:30
Track this in #97. Closing

**Closed by swaminator** 2020-09-15 05:30 UTC
Labels: bug
