### ISSUE TITLE
Its possible to send gzip js bundle instead of only plain .js one?

### ISSUE THREAD

**Issue by rallona** [aws-amplify/amplify-console#343] opened 2019-12-20 01:13 UTC
I am using AWS AMPLIFY CONSOLE to launch a React App

I have created the React App using Amplify Auth and Amplify core.

My app is built and running very well, but the main .js bundle size is 1,3MB. Too high!!

I want to reduce the bundle size, but I don't know how to force to serve only the .js.gz (gzipped version of the bundle) instead of the plain js version.

Its possible to get this in AWS Amplify?

Thanks in advance,

**Comment by swaminator** [comment] 2020-01-03 22:27
Closing as duplicate of #330

**Closed by swaminator** 2020-01-03 22:27 UTC
Labels: question

**Comment by crantini** [comment] 2020-05-26 23:06
Hello all,

My question is identical to @rallona's.

Did anyone ever figure out how to serve GZip-ed web assets when hosting an Amplify Front-End with the AWS Amplify Console?

**Comment by Tporkka** [comment] 2020-05-27 04:20
Having the same issue here trying to reduce my bundle size using the Amplify console instead of Cloudfront directly. It says "file size after gzip" in the build logs is ~3mb, however, when I run it through a website analyzer (gtmetrix.com), it says it is over 17mb so doesn't seem like it's actually compressed.

**Comment by bishonbopanna** [comment] 2020-08-17 19:36
**Same issue. +1
Can some one from Amplify team answer this ?**

**Comment by guidiamond** [comment] 2021-05-17 16:19
Anyone solved this? Having the same issue here. (for both brotli and gziped files)

**Comment by jayvolr** [comment] 2021-08-20 20:41
Ditto here, files on Amplify are not being gziped. Are we all missing something? Is lack of gzip intentional?

**Comment by s4geraldyeong** [comment] 2021-09-21 15:41
Hey all, there is this thing call the performance mode. After you've enabled in "General" > "Settings" > "Your branch", you should start seeing your resource being served as gzip.

**Comment by pennjammin** [comment] 2021-09-25 18:27
@s4geraldyeong are you sure I thought that was just allowing the CDN to cache for longer? I feel this is something highly requested and should be a bit more transparent. I can’t even set performance mode do I really need the CLI for that? Thanks.

**Comment by yeongkongpoh** [comment] 2021-10-01 07:23
@pennjammin I went back to check and you are correct on the performance mode.

My project is using the standard gitlab flow where there are 2 branches. I did another check and made sure the performance mode wasn't activated. 

My JS/CSS assets are served as a gzip already.

**Comment by s4geraldyeong** [comment] 2021-10-01 07:25
@pennjammin I went back to check and you are correct on the performance mode.

My project is using the standard gitlab flow where there are 2 branches. I did another check and made sure the performance mode wasn't activated. 

My JS/CSS assets are served as a gzip already.
