### ISSUE TITLE
Amplify CI/CD stops working after changed username in Github

### ISSUE THREAD

**Issue by entest-hai** [aws-amplify/amplify-console#2493] opened 2022-01-07 02:07 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d2bdgfrxcjfn9h

### Region

ap-southeast-1

### Amplify Console feature

Build settings

### Describe the bug

Amplify CI/CD stops working, does not detect branch changes. This happens after I changed username in Github, I think it is  the reason. 

### Expected behavior

Amplify CI/CD still working. 

### Reproduction steps

1. Just need to change username in Github and push a commit to see

**Comment by arundna** [comment] 2022-01-09 04:31
Hi @entest-hai 👋, thanks for opening this issue and providing the steps to recreate. I've successfully reproduced this by changing the GitHub username and CI/CD stops working with new push commits. Changing it back to the original username (while it was still available) and pushing newer commits ensured that Amplify CI/CD started working again.

We'll keep you posted with further updates.

**Comment by anbav** [comment] 2022-01-09 18:51
Hi, I have a related issue. Not only did ​CI/CD stop working but my app is missing from Amplify entirely, this all occurred after changing my GitHub username.

However, my app is still live at https://www.vibu.work/ (?)

I'm not entirely sure if it's even live, but I'm unable to find the transferred domain from GoDaddy on Route 53 . I seem to have no way to access the app as of right now.

**Comment by hloriana** [comment] 2022-01-12 16:07
Hi @anbav can you confirm that you're logged into the same region that the app is deployed in

**Comment by hloriana1** [comment] 2022-01-12 16:17
Hi @entest-hai 👋🏽 when you change your username in GitHub you need to reconnect the repository to your Amplify application because the URL will have changed. After changing your username, navigate to the Amplify console -> App Settings -> General -> **Reconnect repository** . You will be prompted to select the repository and the dropdown menu should reflect the apps under your new username.

**Closed** 2022-01-12 16:30 UTC
Labels: question, UX, console

**Comment by entest-hai** [comment] 2022-01-12 16:32
@hloriana thank you!! yes, it works well now.
