### ISSUE TITLE
AWS doesn't show my app. It shows JS exceptions in chrome console 

### ISSUE THREAD

**Issue by hamidgh** [aws-amplify/amplify-console#1021] opened 2020-09-02 00:57 UTC
When I go to my app, it shows almost an empty page
![image](https://user-images.githubusercontent.com/2271701/91919915-1845e880-ec8d-11ea-99ba-e0dca82e1f6a.png)

When I open the chrome dev console, it shows bellow error:
![image](https://user-images.githubusercontent.com/2271701/91919891-07957280-ec8d-11ea-9be0-9993b88cbe27.png)

Would you please help me understand what is wrong here?

**Comment by hamidgh** [comment] 2020-09-02 02:01
I found the issue,
I had to remove the version 0.1 on the yml file.
But it should not return JS Exception for the page. It should give the user an appropriate error on the screen. I read the chrome dev tool to understand and fix the issue

**Comment by gwryssekk** [comment] 2020-09-02 23:33
Hi @hamidgh.  Thank you for reporting this.  Can you elaborate a bit more on "I had to remove the version 0.1 on the yml file along with the old steps".  I'd like to understand the opportunity we have to improve the customer experience and understanding your issue a bit more could help with that.

**Comment by hamidgh** [comment] 2020-09-03 13:31
My yml file looked like this:
`version: 1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:
        - yarn run test --watchAll=false && yarn run build
  artifacts:
    baseDirectory: build
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  artifacts:
    baseDirectory: cypress
    configFilePath: '**/mochawesome.json'
    files:
      - '**/*.png'
      - '**/*.mp4'
  phases:
    preTest:
      commands:
        - npm ci
        - npm install wait-on
        - npm install pm2
        - npm install mocha mochawesome mochawesome-merge mochawesome-report-generator
        - npx pm2 start npm -- start
        - 'npx wait-on http://localhost:3000/#/'
    test:
      commands:
        - 'npx cypress run --reporter mochawesome --reporter-options "reportDir=cypress/report/mochawesome-report,overwrite=false,html=false,json=true,timestamp=mmddyyyy_HHMMss"'
    postTest:
      commands:
        - npx mochawesome-merge cypress/report/mochawesome-report/mochawesome*.json > cypress/report/mochawesome.json
        - npx pm2 kill

**version 0.1
frontend:
  phases:
    preBuild:
      commands:
        - yarn install
    build:
      commands:**

`
As you can see it has 2 frontend with 2 different versions. I had to remove the second frontend (bold text) to resolve the issue.

**Comment by gwryssekk** [comment] 2020-09-03 19:11
Ok, thanks, @hamidgh.  We'll create a backlog item to fix this.

**Comment by dragosiordachioaia** [comment] 2020-09-14 08:32
I've had the same issue (and I opened a similar bug to this one). It has nothing to do with the "version 0.1". The issue is, like it says in the console, that there is a duplicate key in the yml file and while it reports the error, the Amplify Console isn't handling, so it just crashes.

**Comment by Athena96** [comment] 2020-09-17 23:34
Hello all, thank you for your patience. We have deployed a fix for this, so it should no longer be an issue. Feel free to re-open this ticket if you continue to face this or related issues. Thank you!

**Closed by Athena96** 2020-09-17 23:34 UTC
Labels: bug
