### ISSUE TITLE
amplifyPush ignores SourceDir and puts aws-exports.js to a wrong path

### ISSUE THREAD

**Issue by asyschikov** [aws-amplify/amplify-console#342] opened 2019-12-27 14:06 UTC
**Describe the bug**
I have the following  amplify/.config/project-config.json

```
{ 
    "projectName": "zzz", 
    "version": "2.0", 
    "frontend": "javascript", 
    "javascript": { 
        "framework": "react", 
        "config": { 
            "SourceDir": "frontend/src", 
            "DistributionDir": "frontend/build", 
            "BuildCommand": "npm run-script build", 
            "StartCommand": "npm run-script start" 
        } 
    }, 
    "providers": [ 
        "awscloudformation" 
    ] 
}
```

When I do `amplify push` on my machine it works fine, the aws-exports.js is created where SourceDir points to. When amplifyPush is executed during the build in the console it generates the file in ./src, ignoring SourceDir setting.

**Amplify CLI Version**
4.6.0

**Comment by BabyDino** [comment] 2019-12-30 19:23
I am running into the same issue. I can confirm `amplifyPush --simple` places the file into `./src`

**Comment by heitorlessa** [comment] 2020-01-16 16:02
Same here. Added this temporary fix in my `amplify.yml` file for now before my frontend build:

> NOTE: I use `src/frontend` but yours may be simply `src`. The info is under `amplify/.config/project-config.json` under `SourceDirectory` key
```yaml
- test -f src/aws-exports.js && cp src/aws-exports.js src/frontend/ # temporary fix: https://github.com/aws-amplify/amplify-console/issues/342
```

**Comment by kahdojay** [comment] 2020-01-27 23:24
@asyschikov @BabyDino can you please upgrade Amplify CLI to 4.13 and let us know if the issue persists?

**Comment by BabyDino** [comment] 2020-01-28 13:17
Looks good! Thank you! :)

**Comment by heitorlessa** [comment] 2020-01-28 18:31
Just upgraded to 4.13.1, kicked a new build and it's now fixed. 

Thank you @kahdojay and team

**Closed** 2020-01-28 23:45 UTC
Labels: backend, bug

**Comment by amorealz** [comment] 2022-01-27 08:49
Hello guys.

I'm sorry to comment in this old thread, but the issue is still happening. I can confirm that it places the file in the wrong or default directory (./src) and ignores the SourceDir configuration.

In  my specific case is a monorepo setup, and maybe that needs to be checked as well somewhere.

Also there is a lot of people with the same pain on this issue in the docs: [503](https://github.com/aws-amplify/docs/issues/503)
