### ISSUE TITLE
Build logs show success but console marks it as failed

### ISSUE THREAD

**Issue by silent-vim** [aws-amplify/amplify-console#2363] opened 2021-11-03 16:59 UTC
### Before opening, please confirm:

- [X] I have checked to see if my question is addressed in the [FAQ](https://github.com/aws-amplify/amplify-console/blob/master/FAQ.md).
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-console/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-console/blob/master/CONTRIBUTING.md).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d3dxquv3bv5ptg

### Region

us-west-2

### Amplify Console feature

Previews

### Describe the bug

We have a pr open that is being marked as failed in the Build stage even though from the logs we can see if successfully completes the build stage. 

### Expected behavior

Build stage should be marked as a success

### Reproduction steps

Redeploy the PR and wait for the build to complete it will succeed but get marked as failed

**Comment by hloriana** [comment] 2021-11-08 21:21
Hi @silent-vim just to confirm, are you able to successfully deploy your app? Also, is it just the icon for build that's showing a failed build status?

**Comment by silent-vim** [comment] 2021-11-08 21:23
We have not merged the PR since we aren't sure how it will impact the main
branch. The build completes based on looking at the logs but on the console
remains in progress for hours and then gets marked as failed. It is still
happening.

**Comment by silent-vim** [comment] 2021-11-12 19:58
@hloriana still waiting to hear back? should we abandon aws-amplify 😕

**Comment by hloriana** [comment] 2021-11-18 21:26
Hi @silent-vim, apologies for the delay. I've not been able to reproduce this behavior. Could you please send an email to aws-amplify-customer@amazon.com with your contact info so we can setup a call with you to further investigate?

**Comment by victorccccc** [comment] 2022-01-28 06:03
Hi, sorry for the inconvenience. From our database record, I saw the status is `SUCCEED` for `pr-93` branch `build 1`. Are you still seeing the inconsistency in Amplify Console?

**Comment by ganipcanot** [comment] 2022-03-03 19:17
Closing due to age - please re-open or create a new ticket if you are still having issues.

**Closed by ganipcanot** 2022-03-03 19:17 UTC
Labels: pending-customer-response
