### ISSUE TITLE
Retrieving deployment details

### ISSUE THREAD

**Issue by spinningrachel** [aws-amplify/amplify-console#873] opened 2020-07-20 10:59 UTC
I created a frontend app with Amplify for a static site. I generated the code on my own and when prompted, uploaded the zip file. The initial deployment worked great, and currently, that content can be viewed from our domain. 

However, when I access the app and upload a new zip to overwrite the existing content, it gets stuck in Retrieving deployment details forever. 

Currently some of the environments are password protected. Initially I moved them all to password protection. 

I've tried adding a new environment and the same thing happens. I also tried removing a bad environment and then declaring the new environment as the prod and I tried to see if the password protection was affecting it so I tried with and without. 

I also tried creating a new app. The problem does NOT happen in the new app - but we also haven't customized the domain there yet and I didn't password protect - and those are the only differences between the two. 

I'm attaching screenshots and logs - I see there's some sort of error in the logs but not really sure where I might be going wrong ... 
[amplify.zip](https://github.com/aws-amplify/amplify-console/files/4947246/amplify.zip)

Help?

**Comment by abhi7cr** [comment] 2020-07-20 15:51
Hi @spinningrachel,

Could you share your appId and region?

**Comment by spinningrachel** [comment] 2020-07-20 16:37
The ARN is arn:aws:amplify:us-east-1:231290928314:apps/d2yakiojcs06ai and the region is us-east-1
Also I've tried cancelling the deployments so I could try uploading from scratch - but while the history now shows the processes have been cancelled, the same Retrieving deployment details message still appears ...

**Comment by spinningrachel** [comment] 2020-07-20 17:57
Also, I cancelled the deployments and then, they still kept the Retrieving deployment details message and appearance of pending even though the history reflected that the stuck deployments had been cancelled. 

Then for 1 environment (the one in prod) I uploaded new files anyway, and it worked successfully within 40 seconds, overriding the old message and finally displaying that deployment had been successful. 

The other environment however, when I tried the same thing, got stuck again and is now stuck trying to deploy my newest attempt.

**Comment by kahdojay** [comment] 2020-10-30 21:11
@spinningrachel apologies for the delay here. I took a look and it looks like there may have been an issue with the zip file being deployed - I wasn't able to reproduce the issue (having both access control and custom domain setup as well), and see that you have some subsequent / successful deploys. 

Can you please let me know if you're still seeing the issue, and if so, also provide the environment name and Deploy number?

**Comment by kahdojay** [comment] 2020-11-02 19:10
@spinningrachel based on my investigation above I'll close this for now but please don't hesitate to re-open this issue and let me know if you're still experiencing the issue and need more help here.

**Closed by kahdojay** 2020-11-02 19:10 UTC
Labels: bug
