### ISSUE TITLE
How to properly redirect using regex

### ISSUE THREAD

**Issue by akefirad** [aws-amplify/amplify-console#816] opened 2020-07-01 08:58 UTC
** Please describe which feature you have a question about? **
I'm trying to redirect `/<3-digit-integer>` to `/code/<same-integer>` but for some reason I can't get it working. What I tried so far (I wasn't sure about the exact syntax):
```
/<[0-9]{3}> to /code/<*>
/</[0-9]{3}/> to /code/<*>
/<^[0-9]{3}$> to /code/<*>
/</^[0-9]{3}$/> to /code/<*>
```
Can someone please take a look and tell me if I'm missing anything here. Thanks.

**Comment by nimacks** [comment] 2020-07-01 23:35
Please refer to our documentation which provides examples on redirects. https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html

Let us know if that doesn't work for you.

**Comment by akefirad** [comment] 2020-07-02 09:38
No, not really. I already talked to AWS support and demoed the whole things. For some reason the exact regex above doesn't work.

**Comment by WolfyUK** [comment] 2021-02-04 12:55
@akefirad Did you ever get a resolution to this? It seems to me like regular expressions just do not work as advertised in the documentation.

**Comment by akefirad** [comment] 2021-02-06 10:51
Nope. Seems messed up 😞

**Comment by ganipcanot** [comment] 2021-07-27 04:31
Resolving due to age - please re-open if you are still experiencing issues.

**Closed by ganipcanot** 2021-07-27 04:31 UTC
Labels: question

**Comment by akefirad** [comment] 2021-07-27 05:51
> Resolving due to age

Not sure if "age" can resolve such issues. Perhaps "Closing due to age" is a better wording.
> please re-open if you are still experiencing issues.

Not sure why we should retry. There's no update regarding any fix. If nothing is fixed then people would still be experiencing the issue.

**Comment by simonjpartridge** [comment] 2021-09-14 20:59
I'm experiencing this exact same problem

**Comment by kookster** [comment] 2021-11-04 15:18
I'm seeing the same - regular expressions don't seem to work at all.

**Comment by amatzen** [comment] 2021-12-02 10:11
December 2021: I'm having the issue as well.

**Comment by taylormadeapps** [comment] 2022-06-09 16:13
I think you need to escape the / characters like so \/
Can't get capture groups working though. Dedperately needed - as per https://github.com/aws-amplify/amplify-hosting/issues/816

**Comment by tatethurston** [comment] 2022-11-23 20:19
> Please refer to our documentation which provides examples on redirects. https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html
> 
> Let us know if that doesn't work for you.

The only reference to regex is https://docs.aws.amazon.com/amplify/latest/userguide/redirects.html#redirects-for-single-page-web-apps-spa which does not demonstrate capture groups. The docs also do not specifically mention `regex` anywhere. There is a large opportunity to better document regex usage.

**Comment by jackdewhurst** [comment] 2022-12-01 11:07
Agreed the documentation on regex in redirects is basically nonexistent. Can't get anything to work

**Comment by dannyhchan** [comment] 2023-02-01 01:11
Agree, they need better documentation for this.

**Comment by Janosch** [comment] 2024-06-12 15:53
I don't know if a capture group is possible, but I was able to make something work which is close enough for my purpose:

Source: `</^\/(?!frontend\/).*$/><*>`
Target:`/frontend/<*>`

So it is possible to combine the capture-like thing `<*>` with a regex. Please note that you have to escape forward slashes as shown in my example. This is probably why it did not work for @akefirad and @iceye. Apparently, regexes need to be placed inside of `</` and `/>`.

It is sad that AWS is unable to resolve this and provide proper docs. This issue has been reported almost four years ago!

**Comment by AlejandroPerez92** [comment] 2024-10-22 17:43
@Janosch I'm checking your regex and It is not working for me, also I've found something wierd. When I save the changes all the "\" are removed automatically from the regex.

Before save:
![Screenshot 2024-10-22 at 18 40 57](https://github.com/user-attachments/assets/f874386b-253b-4a84-890c-d8e6b824809d)

After save
![Screenshot 2024-10-22 at 18 41 14](https://github.com/user-attachments/assets/f97b11ce-b615-4f19-b193-1c3e96e52e7f)

**Comment by KartikSoneji** [comment] 2026-04-12 23:14
In case someone else comes across this.
@AlejandroPerez92 the issue is you're editing the rules as json, so `"\/"` escapes the subsequent `/` character.
To write `\/` in json, you must double-escape the `\`, making it `"\\/"`
