### ISSUE TITLE
Deployment stuck at provision step

### ISSUE THREAD

**Issue by steverandy** [aws-amplify/amplify-console#296] opened 2019-12-09 04:50 UTC
**Describe the bug**
Sometimes deployment stuck at the provision step and does not progress.
There is no additional information displayed or an error message.

![Screenshot 2019-12-09 at 12 32 26 PM](https://user-images.githubusercontent.com/525332/70408169-1e05f900-1a82-11ea-90ce-7a9684d745c7.png)

**Comment by swaminator** [comment] 2019-12-09 21:35
Can you share your appid please? (Found in `App settings > General`)

**Comment by steverandy** [comment] 2019-12-09 23:44
@swaminator d347fpgoiyxpzr

**Comment by steverandy** [comment] 2019-12-10 03:37
@swaminator build status is showing `Pending` and any subsequent webhook triggers appeared to be not processed.

**Comment by kahdojay** [comment] 2019-12-10 23:12
@steverandy I see all the builds for d347fpgoiyxpzr in that region for 12/8 as being successful. Can you share the specific build number we should look at? Also if you have a way we can reproduce the issue, please let us know.

**Comment by steverandy** [comment] 2019-12-11 00:06
Sure. Please check build no 367, 357, 355.

It usually happens for deployment triggered by webhook. Manually triggered deployment usually always successful.

**Comment by abouroubi** [comment] 2019-12-13 17:18
Same but here, Webhook started builds always hangs on provisionning

**Comment by swaminator** [comment] 2019-12-13 21:40
@abouroubi can you share your appid, build settings, and the build IDs that fail.

**Comment by abouroubi** [comment] 2019-12-16 20:38
AppID : d3egu8kdaurpmi
Build Settings : 
```YAML
version: 0.1
backend:
  phases:
    build:
      commands:
        - '# Execute Amplify CLI with the helper script'
        - amplifyPush --simple
frontend:
  phases:
    preBuild:
      commands:
        - npm ci
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: public
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*

```

Build ID that hangs: Build #10

**Comment by kahdojay** [comment] 2019-12-17 00:00
@abouroubi I see the build failed. If you visit the console are you able to see the build logs?

**Comment by kahdojay** [comment] 2019-12-17 00:02
> Sure. Please check build no 367, 357, 355.
> 
> It usually happens for deployment triggered by webhook. Manually triggered deployment usually always successful.

@steverandy I see these builds finished. If you go into the console after the fact, are you able to see them (i.e. now)? I wasn't able to reproduce - how long did you wait? If you can reproduce it again, does refreshing the console after some time show the right thing? Just trying to narrow it down.

**Comment by steverandy** [comment] 2019-12-17 00:16
<img width="960" alt="Screenshot 2019-12-17 at 8 13 27 AM" src="https://user-images.githubusercontent.com/525332/70953690-21623b80-20a5-11ea-8d68-4eb6db528809.png">

@kahdojay it does not show finished for me. It shows it only reaches provision step and I can't see any logs. I had to manually cancel this deployment and manually re-deploy in order to resume it.

Refreshing the console shows the same thing for me. I waited for more than 1 hour.
We deploy multiple times a day and this issue is occurring every day for us.

**Comment by kahdojay** [comment] 2019-12-17 01:46
@steverandy thanks. Just to confirm, this issue happens inconsistently for webhook-triggered deploys, whereas for manually triggered deploys, everything works fine?

**Comment by steverandy** [comment] 2019-12-17 03:05
@kahdojay yes that's correct.

The branch is release.

**Comment by abouroubi** [comment] 2019-12-17 13:56
@kahdojay I had to cancel it and relaunch a new build

**Comment by kahdojay** [comment] 2019-12-17 21:50
@abouroubi I see you had some successful builds afterward and were unable to unblock yourself. 

To help us investigate further, were you able to reproduce the issue consistently, or is it the same as steverandy's situation where it happens inconsistently, and only for webhook-triggered builds?

**Comment by abouroubi** [comment] 2019-12-18 13:32
@kahdojay just reproduced it yesterday, a Webook triggered the build, and it's stuck on provisionning.

I can unlock my self by cancelling and starting a new build but it's not sustanable, the webhooks are triggered when a new article is added to a Blog, I can't afford to give access to the amplify console to my copywriters, and tell them to check the builds each time they write a blog post

**Comment by kahdojay** [comment] 2019-12-18 17:51
@abouroubi I understand it's not a sustainable solution, just trying to confirm whether it's the exact same issue as steverandy's since it will help us better understand the problem and come up with a  fix. steverandy mentioned it happens inconsistently, i.e., sometimes the webhook-triggered build fails, but other times it works for a given branch. Is it the same experience for you?

**Comment by maxnatt** [comment] 2019-12-20 14:50
Same issue with app dpv4no0oh3u0r at eu-central-1.
Webhook-triggered build sometimes gets stuck at Provision stage, but always works after cancelling and starting it manually.

**Comment by abouroubi** [comment] 2019-12-23 13:20
@kahdojay had to delete and create a new app, but the issue seems to appear on every webhook call for me.

**Comment by canofpopcom** [comment] 2019-12-24 09:03
Same here just gets stuck on provisioning via the webhook and that then blocks updates from Git Branch, we had to revert to our fall back i.e. using: netlify.com which isn't ideal. 

Do we think the issue will be resolved any time soon? 

Andy.

**Comment by steverandy** [comment] 2019-12-30 02:04
@kahdojay do you have any updates on this issue?

**Comment by kahdojay** [comment] 2019-12-30 18:42
@steverandy not at this time unfortunately, we are still investigating a fix.

**Comment by canofpopcom** [comment] 2020-01-01 17:49
@kahdojay - HNY, we've got a site going live for CES 2020 tomorrow and we really need this to be resolved and an alternative workaround suggested (i.e. use an alternative datacentre) any ETA or are we to keep doing manual builds?

**Comment by kahdojay** [comment] 2020-01-02 16:51
@canofpopcom no ETA yet, please bear with us and use the workaround for the time being while we continue investigating a fix

**Comment by canofpopcom** [comment] 2020-01-06 14:39
@kahdojay - any news?

**Comment by canofpopcom** [comment] 2020-01-09 15:14
@kahdojay is this now fixed?

**Comment by matteomelani** [comment] 2020-01-29 23:54
Same issue here

**Comment by steverandy** [comment] 2020-02-06 06:47
@kahdojay is there any update? thanks.

**Comment by husamuddin** [comment] 2020-02-21 16:16
any anydate?

**Comment by husamuddin** [comment] 2020-02-21 16:16
any update on this?

**Comment by gwryssekk** [comment] 2020-02-21 21:43
@steverandy @husamuddin @canofpopcom @matteomelani @abouroubi @maxnatt 

Hi All.  Just wanted to update everyone that we have identified a fix for this issue and will be rolling it out soon.

**Comment by poolieweb** [comment] 2020-03-18 14:17
Any update on the roll out of the release ?

**Comment by gwryssekk** [comment] 2020-03-27 17:35
Hi all, this fix has been deployed for all regions.  Feel free to test and let us know if you still see the issue.

**Comment by tkjaergaard** [comment] 2020-04-01 08:57
Hi @gwryssekk,

I don't know if it's related, but I have just experienced that I'm getting stuck at the provisioning step when pushing to GitHub.

https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d3ab2d1gmwnk9b/dev/21

and

https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d3ab2d1gmwnk9b/master/14

**Comment by gwryssekk** [comment] 2020-04-01 18:06
@tkjaergaard -- Hmm, ok, I'll check and see if it is related or if there is another similar issue.

**Comment by gwryssekk** [comment] 2020-04-01 18:31
@tkjaergaard --  From the logs I have available, this doesn't seem to be the same issue.  I see that later builds succeeded.  After you encountered this, how did you proceed?  Did you cancel the stuck job or just resubmit?  Also, are you able to access the build logs from the console for these jobs?

**Comment by tkjaergaard** [comment] 2020-04-01 19:23
@gwryssekk I click the cancel button form within the UI and the pressed the "redeploy this version"-button immediately after. Nothing but the provisioning-logs was available. Like it never got further.

**Comment by gwryssekk** [comment] 2020-04-02 18:39
Thanks, @tkjaergaard....I'll dig a bit more and see what I can find.  After you cancelled and redeployed did it succeed?

**Comment by tkjaergaard** [comment] 2020-04-03 13:33
@gwryssekk Yes, it did. It went right through without any hiccups.

**Comment by madsrasmussen** [comment] 2020-04-03 13:36
Hey @gwryssekk,

I am experiencing the same issue with provisioning. The URL to Amplify: https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d3o9mdzy9l1hu2/master/100 . I canceled the deployment and clicked the "Redeploy this version"-button. After that everything went smoothly.

**Comment by gwryssekk** [comment] 2020-04-13 18:02
Hi folks, thanks for the updates here. =  While we did fix one issue that was causing this to occur it seems there is another one we have to track down.  I'm going to create a task to have the team look into this in detail.

**Comment by tkjaergaard** [comment] 2020-08-10 10:58
@gwryssekk Just experienced the issue again today on another Amplify project.

https://eu-central-1.console.aws.amazon.com/amplify/home?region=eu-central-1#/d2dldaj4mfy118/dev/116?step=PROVISION

**Comment by behrooziAWS** [comment] 2020-08-12 00:18
@tkjaergaard we had an issue with screenshotting that was impacting builds during that window (https://github.com/aws-amplify/amplify-console/issues/948).  We've resolved the underlying issue so builds shouldn't be blocked.  It looks like subsequent builds have succeeded for you.  Was this a one-off that occurred only in the last week or so or is this a recurring issue for you?

**Comment by harishperfect** [comment] 2020-08-18 04:11
Provisioning takes a very long time. Have the same issue. Took at least 18 Mins.

**Comment by maksym-bordun-ynd** [comment] 2020-08-27 08:24
Are there any news? Fix was deployed about 5 months ago, but builds still get stuck on Provision from time to time (and always work when build gets restarted manually), as described in the first message.

**Comment by shide1989** [comment] 2020-09-25 11:04
@gwryssekk This issue is still happing while the fix has been deployed months ago. Any update ?

**Comment by gregeatworld** [comment] 2020-09-28 17:48
Same here.
![image](https://user-images.githubusercontent.com/3019709/94466865-c41a1f80-01ca-11eb-9269-38e0b973a8cc.png)
Really very frustrating situation as for paid service. Can we count on soonest fix or at least any details regarding this?

**Comment by stevechanvii** [comment] 2020-10-12 02:18
> Same here.
> ![image](https://user-images.githubusercontent.com/3019709/94466865-c41a1f80-01ca-11eb-9269-38e0b973a8cc.png)
> Really very frustrating situation as for paid service. Can we count on soonest fix or at least any details regarding this?

Have same problem this couple of weeks (region Sydney). Some times stuck at provision, once I click cancel the status of provision change from pending to success, but other steps failed. Manually rebuild the project would successfully build the project.

**Comment by litwicki** [comment] 2020-10-19 03:32
@stevechanvii @gregeatworld @shide1989 @maksym-bordun-ynd @judygab We are revisiting this issue this week and will update here as soon as we have more information.

**Comment by talhaabbasi** [comment] 2020-11-11 05:38
Same issue for me:
![image](https://user-images.githubusercontent.com/28659121/98773083-02ca0900-240a-11eb-9cb8-07a7e556efc6.png)


@litwicki any update on this?

**Comment by litwicki** [comment] 2020-11-11 05:46
@talhaabbasi are you running multiple builds on 1 or more apps? There is a maximum number of concurrent builds that can be ran at once, and an issue we are working to resolve where that limit isn't displaying correctly in some cases. While I know this isn't ideal, are you able to cancel and "Redeploy this version" with any success?

**Comment by talhaabbasi** [comment] 2020-11-11 05:48
> @talhaabbasi are you running multiple builds on 1 or more apps? There is a maximum number of concurrent builds that can be ran at once, and an issue we are working to resolve where that limit isn't displaying correctly in some cases. While I know this isn't ideal, are you able to cancel and "Redeploy this version" with any success?

Yes, I am running multiple builds. 
Yes, it works fine when I cancel and redeploy.

**Comment by ganipcanot** [comment] 2020-11-24 18:45
If anyone is still having issues please feel free to re-open this ticket.

Generally speaking there could be a couple issues:
1. We have a maximum number of concurrent builds/jobs that customers can run in a single account/region (Check the Service Quotas dashboard)
2. For very large manual deployments (Very large zip files) there is an issue which can cause builds to hang.  We are currently deploying a workaround for this but it isn't live in all regions yet.  If manual builds are hanging (once this new workaround is deployed) you should be able to upload your ZIP to S3 and deploy from there.

**Closed by ganipcanot** 2020-11-24 18:45 UTC
Labels: bug, pending-prioritization

**Comment by pocket5s** [comment] 2020-11-25 20:23
Running into this myself, on us-east-1. Tried to cancel and redo a few times with no success. a few have hung for a couple hours.

**Comment by gasPoweredSticks** [comment] 2020-11-25 20:28
Having some issues with deployment as well. two builds have been stuck on provision for a few hours now. us-east-1

**Comment by ganipcanot** [comment] 2020-11-25 20:39
AWS is experiencing a Large Scale Event (LSE). Please follow the [AWS Service Health Dashboard](https://status.aws.amazon.com/).

> Increased Error Rates
>
> 8:05 AM PST: Kinesis is experiencing increased API errors in the US-EAST-1 Region. This is also causing issues with ACM, Amplify Console, API Gateway, AppStream2, AppSync, Athena, Cloudformation, Cloudtrail, CloudWatch, Cognito, Connect, DynamoDB, EventBridge, IoT Services, Lambda, LEX, Managed Blockchain, Resource Groups, SageMaker, Support Console, and Workspaces. This issue has also affected our ability to post updates to the Service Health Dashboard.

Business/enterprise customers may contact their Technical Account Manager.

**Comment by pocket5s** [comment] 2020-11-26 05:11
9 hours later, still no remedy...

**Comment by litwicki** [comment] 2020-11-26 18:05
@pocket5s the event has since cleared and operations are working normally now. Can you please try a new build and let us know if you have any issues.

**Comment by pocket5s** [comment] 2020-11-26 18:53
The app deployed at 12:15 AM central. So about an hour after my last comment.

**Comment by SwapnilPatil07** [comment] 2021-06-14 14:24
I am having same issue today. Cancelled deployment 5 times and restarted. Not it is stuck in provisioning step since 1 hour. Please help.

**Comment by wolflingorg** [comment] 2021-06-14 14:25
Having the same issue...

**Comment by xKbryan** [comment] 2021-06-14 14:29
The same here...
Using: us-east-1

**Comment by alokparikh1692** [comment] 2021-06-14 14:33
Having the same issue. Using `us-east-1`

**Comment by SwapnilPatil07** [comment] 2021-06-14 14:36
Same issue. Stuck in "Provision" step since more than hour.

**Comment by KLaci** [comment] 2021-06-14 14:53
Same issue here.

**Comment by krikork** [comment] 2021-06-14 15:08
Been stuck on this all morning.

**Comment by nimacks** [comment] 2021-06-14 15:21
We are currently experiencing increasing build latency rates for the AWS Amplify Console in the US-EAST-1 region

**Comment by jansony1** [comment] 2021-06-14 15:43
same issue

**Comment by carlosgpn** [comment] 2021-06-14 15:43
Same here

**Comment by yupingwyp** [comment] 2021-06-14 15:46
Same here. Maybe a sev outage going on at aws?

**Comment by bhvngt** [comment] 2021-06-14 16:05
Same here... Hope we get some clarification from the team.

**Comment by yupingwyp** [comment] 2021-06-14 16:08
Agreed. Especially since AWS's health dashboard still shows everything green. Please please help!

**Comment by bhvngt** [comment] 2021-06-14 17:26
It has started working.. Maybe it was some sort of an outage.

**Comment by mduecker** [comment] 2021-07-13 13:30
Having the same issue in `eu-central-1`

**Comment by mauhdz** [comment] 2021-08-07 03:46
Hi, still experiencing this issue. Any fix? These bugs make me feel so insecure about using Amplify as it is truly unreliable.

**Comment by walesdata** [comment] 2022-02-14 23:03
Hello! 

If you are having this problem, I was able to fix it by:
1. Go to the app dashboard where you can see your stuck deployment
2. Click the "provision" step in the stuck deployment, this will take you to a provision tab on another page.
3. On that page, click the orange "View build history" button in the upper right
4. On the build history page, you'll see your 'stuck' builds. Go to each one and cancel it.
5. When all are cancelled, go back to the latest build and look for a "Redeploy this version" button right under the orange button you clicked to go to build history
6. The re-deploy should work now after you cleared out all the previous 'stuck' deploys.
