### ISSUE TITLE
build settings (amplify.yml): difference between backend and frontend sections

### ISSUE THREAD

**Issue by helloPiers** [aws-amplify/amplify-console#546] opened 2020-03-27 14:42 UTC
Trying to learn more detail than is currently given at the page https://docs.aws.amazon.com/amplify/latest/userguide/build-settings.html about the amplify.yml build settings.

There are sections backend and frontend. Do these have any actual meaning or differences? 

It seems that even the shell environment flows between them - for example I had a `cd` command in backend and one in frontend but the frontend one failed as the build was still in the directory from the backend `cd` command.

**Comment by Athena96** [comment] 2020-03-27 21:50
Hi @helloPiers, thanks for your question.
The 'backend'/'frontend' sections are used to appropriately group the logs during the build. 
The commands that are in each section happen in the same container/shell environment, and the state does not reset between steps.
Let us know if you have any follow-up questions.

**Comment by helloPiers** [comment] 2020-03-28 17:21
Thanks for the response - understand now that this split allows the Console UI to separate the log output into Backend and Frontend sections.

A quick follow-up - in the docs it says 
> postBuild - The post-build script runs after the build has finished and we have copied all the necessary artifacts to the output directory

I'm not quite sure what "output directory" means here, but, I put a command in postBuild to overwrite a file in my /dist/ folder, and the overwritten file was what was published. In other words postBuild seems to run _before_ the artifacts are collected.

Do preBuild, build, and postBuild actually do anything different or just provide a conceptual way to organise the file?

**Comment by adriencg** [comment] 2020-04-20 09:00
@helloPiers The three phases are borrowed from CodeBuild terminology, and primarily meant to organize _your_ commands into sections; you could stick them all in a single phase and it'd work all the same. The only thing the runner guarantees is the run-order (preBuild > build > postBuild).

The "we" is a bit confusing in that section, since it refers to what _your_ commands did in the build phase (presumably generate your assets and stick 'em in the output dir).

Closing for now, since this reply mostly just confirmed your correct understanding of what was happening. Feel free to reopen if you've any more questions.

**Closed by adriencg** 2020-04-20 09:00 UTC
Labels: question
