### ISSUE TITLE
Amplify console - Build successful but fails to deploy

### ISSUE THREAD

**Issue by rnaresh** [aws-amplify/amplify-console#291] opened 2019-12-05 12:11 UTC
Hi,

We are using Amplify to build a new website using docusaurus. It started failing to deploy  from the past 2 days

App ARN - ```arn:aws:amplify:us-east-2:582734241681:apps/dpwfbpxczhwpr```
The artifact size is ~45MB

All of our preview deploys are failing
![image](https://user-images.githubusercontent.com/4458618/70234018-b865f400-1785-11ea-8dfd-32ca5b0cc145.png)

![image](https://user-images.githubusercontent.com/4458618/70233956-98cecb80-1785-11ea-97d7-3d6cf67c1f5c.png)

Logs say  'Failed to deploy without mentioning the reason'
![image](https://user-images.githubusercontent.com/4458618/70234101-e64b3880-1785-11ea-8782-aa90958bd85b.png)

**Comment by swaminator** [comment] 2019-12-09 21:50
@rnaresh how big is your `node_modules` folder? We have a known issue in #115 which we are actively working on. The workaround is to delete unused branches in your app.

**Comment by rnaresh** [comment] 2019-12-10 01:39
Thanks @swaminator . Size of the node_modules folder is ~150MB

**Comment by despau** [comment] 2020-01-06 16:40
I have the same issue and I have been struggling with it for the past 6 days. I am really frustrated about this amplify work.

**Comment by iShavgula-TacTill** [comment] 2020-03-12 17:47
Hello,

Any update on this? I'm having exactly the same issue.

**Comment by despau** [comment] 2020-03-12 20:11
I am not sure what happened nor how I fixed the issue.
I remember resolving some git merging conflict issues (CodeCommit in my case).

My advise from it, make sure your git (the source control you're using) has no conflict nor issues.

**Comment by iShavgula-TacTill** [comment] 2020-03-13 15:59
@despau thank you for your response.
I started over to and went step by step to detect what is causing the issue. I reproduced this multiple times, so either there is a bug or I'm doing something wrong.

### In terminal

- initialise git repository
- initialise amplify env `dev`, then push
- initialise amplify env `test`, then push
- commit and push to origin `dev`
- checkout and push to origin `test`

### In AWS Amplify console
- Setup CD for frontend `dev`, link to the backend `dev`
- Setup CD for frontend `test`, link to the backend `test`

Everything works fine.

### In terminal
- checkout git to the `dev` branch
- checkout amplify to the `dev` env 
- add api to the amplify backend
- commit and push to origin `dev`
- checkout to `test`
- merge `dev` into `test`, then push

At this stage, everything still works fine.

Then, I repeat the same steps but, instead of `api` I add a function.
CD works fine for the `dev` environment, but fails for `test`.

The interesting fact is that, the deployment status is green despite the CD error and the new category (`Functions` in this case) is added to the backend environment.

<img width="576" alt="Capture d’écran 2020-03-13 à 16 56 45" src="https://user-images.githubusercontent.com/15924394/76637806-b1e8d480-654b-11ea-8aa0-9d135e327dc7.png">
<img width="800" alt="Capture d’écran 2020-03-13 à 16 54 10" src="https://user-images.githubusercontent.com/15924394/76637799-af867a80-654b-11ea-8e13-9647f86da188.png">

@swaminator Could you please tell me if I'm doing anything wrong here ?

Thank you.

**Comment by Joycehao19** [comment] 2020-04-09 20:57
Hi @iShavgula-TacTill , would you mind provide your appId and region? Thanks!

**Comment by iShavgula-TacTill** [comment] 2020-04-10 07:32
`d2wh1ccxeyzij1 `, `eu-west-1`.

thank you, @Joycehao19

**Comment by adriencg** [comment] 2020-04-13 21:10
Hard to tell, but may be related to https://github.com/aws-amplify/amplify-console/issues/115 . Will look at our internal logs and provide an update.

**Comment by rnaresh** [comment] 2020-04-20 08:45
@swaminator All our preview builds started failing again from the past few weeks. node_modules folder size is 160MB.

**Comment by rnaresh** [comment] 2020-04-22 15:03
@swaminator this is blocking our build pipeline? can you let us know what could be the reason for build failures in the last few weeks?

**Comment by litwicki** [comment] 2020-10-19 03:35
@rnaresh are you still experiencing any issues? This is a duplicate of https://github.com/aws-amplify/amplify-console/issues/115 as stated above. Closing this issue.

**Closed by litwicki** 2020-10-19 03:35 UTC
Labels: bug, investigating
