### ISSUE TITLE
How do I get chrome-headless installed on my build-machine-image (Linux2)?

### ISSUE THREAD

**Issue by blomm** [aws-amplify/amplify-console#344] opened 2019-11-06 12:12 UTC
** Which Category is your question related to? **
Deployment pipeline

** Provide additional details e.g. code snippets **
in the amplify.yml file I'm running "npm install puppeteer" to get chromium installed (must be a better way, no?), and in the env variables I've set CHROME_BIN to be /usr/bin/chromium-browser but the tests timeout because they cant find chrome here.

my test script is:
ng test --no-watch --no-progress --browsers=ChromeHeadless

What are the steps to get this working? thank-you

**Comment by Joycehao19** [comment] 2020-02-26 18:19
Duplicate of #39

**Comment by swaminator** [comment] 2020-02-26 20:14
Reopening as this isn't a duplicate.

**Comment by Joycehao19** [comment] 2020-02-26 21:44
@blomm can you try this https://github.com/aws-amplify/amplify-console/issues/39#issuecomment-519681477

**Comment by swaminator** [comment] 2020-03-23 23:43
@blomm we are resolving this for now. Please let us know if this issue still exists.

**Closed by swaminator** 2020-03-23 23:43 UTC
Labels: pending-customer-response, question
