### ISSUE TITLE
Build error due to failed validation of a stackName variable

### ISSUE THREAD

**Issue by azatoth** [aws-amplify/amplify-console#62] opened 2019-08-19 09:31 UTC
**Describe the bug**
Today, builds started to error out with following error:

```
2019-08-19T09:21:01.568Z [WARNING]: - Initializing your environment: dev
2019-08-19T09:21:01.918Z [WARNING]: ✖ There was an error initializing your environment.
2019-08-19T09:21:01.918Z [INFO]: init failed
2019-08-19T09:21:01.920Z [INFO]: { ValidationError: 1 validation error detected: Value '2019/08/16/[$LATEST]cd0a768c6f1b4318ac2616587be80916' at 'stackName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*
                                 at Request.extractError (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/protocol/query.js:50:29)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
                                 at Request.emit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:683:14)
                                 at Request.transition (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:22:10)
                                 at AcceptorStateMachine.runTo (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/state_machine.js:26:10
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:38:9)
                                 at Request.<anonymous> (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/request.js:685:12)
                                 at Request.callListeners (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
                                 message:
                                 '1 validation error detected: Value \'2019/08/16/[$LATEST]cd0a768c6f1b4318ac2616587be80916\' at \'stackName\' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][-a-zA-Z0-9]*|arn:[-a-zA-Z0-9:/._+]*',
                                 code: 'ValidationError',
                                 time: 2019-08-19T09:21:01.916Z,
                                 requestId: 'a9907160-c262-11e9-8934-a9b35c181078',
                                 statusCode: 400,
                                 retryable: false,
                                 retryDelay: 71.50912785127241 }
2019-08-19T09:21:01.994Z [ERROR]: !!! Build failed
2019-08-19T09:21:01.994Z [ERROR]: !!! Non-Zero Exit Code detected
```

**To Reproduce**
1. Push code to git repo
2. Have it try to build

**Expected behavior**
I expect it to succeed to build

**Additional context**
Locally I've have updated amplify-cli many times, and is currently on 1.12.0; I did try to locally downgrade the version but then ended up with the same error locally;

**Comment by swaminator** [comment] 2019-08-19 18:26
@azatoth Can you use the live updates feature to get the Amplify CLI to its latest version? We are in the process of releasing a fix that will automatically update your CLI version to the latest version:
https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

**Comment by houmark** [comment] 2019-08-19 19:57
@swaminator I have the same issue which I also reported and a loooong grumpy issue in Amplify CLI.

I don't have "Live Package Updates" in my interface:
![Image 2019-08-19 at 2 55 29 PM](https://user-images.githubusercontent.com/467330/63295159-9b1e2000-c291-11e9-9f7a-223426e08217.png)

So?

**Comment by azatoth** [comment] 2019-08-19 19:57
> @azatoth Can you use the live updates feature to get the Amplify CLI to its latest version? We are in the process of releasing a fix that will automatically update your CLI version to the latest version:
> https://docs.aws.amazon.com/amplify/latest/userguide/custom-build-image.html#setup-live-updates

I'm afraid I don't think I'm able to do that; under `Build image settings` there is only `Build Image` and `Build Timeout`; there's no `Live package update`. I am on eu-west-1 btw, so the live update thingi might be only released in us-central-1

**Comment by houmark** [comment] 2019-08-19 20:04
I'm on `us-east-1` and it's the same for me.

**Comment by anatonie** [comment] 2019-08-19 20:58
@houmark @azatoth 

Can you please check and see if it is there now?

**Comment by houmark** [comment] 2019-08-19 21:43
@anatonie It's there now, but exactly what do I need to do to make this change?

I tried with this setup but that didn't work:
https://cl.ly/4d693f

I get this error (it jumps backend and fails on deploy):
https://cl.ly/b44bce

How can you just break stuff in such an important process? How am I supposed to take this platform serious when you can just break things out of the blue? If you knew that having the latest CLI is critical to keeping things working for everyone, how come you don't postpone releases until it's wired in all around? I'm not your test rabbit. I'm your paying client!

**Comment by swaminator** [comment] 2019-08-20 01:16
@hourmark apologies about the issues you're facing. A fix is rolling out right now and should be available in us-east-1. Try redeploying your app and  please verify that this works for you?

**Comment by houmark** [comment] 2019-08-20 01:22
@swaminator Is that with or without the special configuration in build settings?

**Comment by swaminator** [comment] 2019-08-20 02:13
Yes

**Comment by houmark** [comment] 2019-08-20 02:16
I'm building now and it looks like it's working. Currently on Frontend, so the failing parts have passed this time.

Now, why did my production build not break? Something really sketchy is going on here between my two environments and I cannot pinpoint what's happening. I have ElasticSearch issues between the two and I cannot figure out how to get them both in sync.

**Comment by swaminator** [comment] 2019-08-20 02:46
See https://github.com/aws-amplify/amplify-cli/issues/2080#issuecomment-522827168

**Comment by houmark** [comment] 2019-08-20 08:24
I wanted to add that I got this non-blocking error/warning when deploying:

> 2019-08-20T05:33:24.229Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src157097187/src/adleaks-amplify/amplify/backend/api/myapi/build/cloudformation-template.json

I have seen a similar error before when doing `amplify push` in the Console and I'm curious to understand why that happens and what the solution may be?

**Comment by houmark** [comment] 2019-08-20 08:25
I wanted to add that I got this non-blocking error/warning when deploying:

> 2019-08-20T05:33:24.229Z [INFO]: Could not read cloudformation template at path: /codebuild/output/src157097187/src/my-amplify/amplify/backend/api/myapi/build/cloudformation-template.json

I have seen a similar error before when doing `amplify push` in the Console and I'm curious to understand why that happens and what the solution may be?

**Comment by azatoth** [comment] 2019-08-20 10:48
@swaminator It seems to work now, thought the build logs doesn't clearly indicate it's using version `1.12.0`;

Under "Provision" it says `ENV VERSION_AMPLIFY=1.7.2` which for most people would indicate we are using amplify 1.7.2.
And under "Cloning Repository" it only states following:
```
2019-08-20T10:02:11.381Z [INFO]: # Ensuring NPM package '@aws-amplify/cli' is version: 'latest'
2019-08-20T10:02:13.869Z [INFO]: # NPM package '@aws-amplify/cli' already at version 'latest'
```
i.e. somehow it's already at version `'latest'`, though there's nothing in the log stating it ever upgraded to that version.
Perhaps it could be an good to actually print out the version of active `amplify-cli` to the logs for reference purpose?

**Comment by swaminator** [comment] 2019-08-20 16:54
> Under "Provision" it says `ENV VERSION_AMPLIFY=1.7.2` which for most people would indicate we are using amplify 1.7.2.
> Perhaps it could be an good to actually print out the version of active `amplify-cli` to the logs for reference purpose?

Thanks for pointing that out - the text will get updated to the latest version soon. The default build version in the container is now `1.12.0`. We will also provide more helpful text so you know that what version of the Amplify CLI is running.

**Comment by houmark** [comment] 2019-08-20 19:22
I also noticed that but forgot to report it. Happy to see this improved, but I do have a follow-up request in relation to this.

The CLI could still be behind as it's somewhat based on the user manually updating it? So unless the CLI implements a required update to ensure the latest version before being able to push from the CLI, there should be some kind of warning (or even blocking deployment in the Console) if there are version differences I think? Looking at this incident, having version differences can lead to some serious issues like the one @azatoth and I was hit by.

**Comment by houmark** [comment] 2019-08-21 02:37
This is still super weird.

After I fixed the nextToken yesterday both in dev and prod, everything was working nicely. Both had nextToken to `String`. I thought this was solved. I was wrong.

A couple of hours ago I deployed unrelated changes to both dev and prod and dev works, but prod broke and it now yet again complaints that nextToken should be an `Int`.

I did `amplify codegen` in the console on prod, no changes, it wants to be `Int` again?!?!?

This is the error I got (I had to roll back to an earlier version to get prod working again):
> "Validation error of type VariableTypeMismatch: Variable type 'String' doesn't match expected type 'Int' @ 'searchApplications'"

**What do I do now?**

Again, I have latest CLI and I have in the Console I am using `latest` and it shows it's using latest.

I've been looking at the resolvers and they show `String` for both as far as I can tell.

**Comment by houmark** [comment] 2019-08-21 02:40
@swaminator @kaustavghosh06 did anything change somewhere today? I'm more confused than ever. I thought I had understood the situation here and it all made some sense, but now nothing is making sense anymore and I am unable to deploy to production — I mean I can go back to `Int` but I don't know if production randomly changes to `String` in the middle of deployment and then breaks again.

I did `amplify env pull` and `amplify env pull --restore` in the CLI. No help. I'm out of ideas.

**Comment by houmark** [comment] 2019-08-21 05:50
Moving back to dev I and running `amplify codegen` I now get these changes to queries.js:
https://cl.ly/d1a560

Moving to prod and running `amplify codegen` those are not added.

Conclusion: After a day where both seemed synced, prod now once again wants to use `Int` as nextToken and dev wants to use a `String`.

If you could please advice what I should do next? Scared to do `amplify push` from the CLI in prod as I don't want to break anything in production.

**Comment by swaminator** [comment] 2019-08-21 16:22
> I also noticed that but forgot to report it. Happy to see this improved, but I do have a follow-up request in relation to this.
> 
> The CLI could still be behind as it's somewhat based on the user manually updating it? So unless the CLI implements a required update to ensure the latest version before being able to push from the CLI, there should be some kind of warning (or even blocking deployment in the Console) if there are version differences I think? Looking at this incident, having version differences can lead to some serious issues like the one @azatoth and I was hit by.

I think what you're saying is that if a user has an older version of the CLI than what's in the Console, there is a potential for the backend deployment to fail. This is why we update the versions of the CLI on a monthly basis to ensure updates are tested in the Console first. The live updates feature is meant to give customers the ability to always stay at the latest version or pin to a specific version.

**Comment by swaminator** [comment] 2019-08-21 16:25
> @swaminator @kaustavghosh06 did anything change somewhere today? I'm more confused than ever. I thought I had understood the situation here and it all made some sense, but now nothing is making sense anymore and I am unable to deploy to production — I mean I can go back to `Int` but I don't know if production randomly changes to `String` in the middle of deployment and then breaks again.
> 
> I did `amplify env pull` and `amplify env pull --restore` in the CLI. No help. I'm out of ideas.

Looking into this right now.

**Comment by swaminator** [comment] 2019-08-21 17:44
@hourmark there are a bunch of theories we have on what's going on. We'd like to schedule a quick chat with you whenever you're free today.

**Comment by houmark** [comment] 2019-08-21 19:20
@swaminator I'd be happy to and I'm available now. How do we connect?

**Comment by swaminator** [comment] 2019-08-21 19:37
Can you email aws-amplify-customer@amazon.com? I'll send you details.

**Comment by houmark** [comment] 2019-08-21 19:41
Done.

**Comment by swaminator** [comment] 2019-08-22 17:46
Closing this issue: For those who happen upon here there seems to be have been a bug due to the version update of the CLI when automatically merging code to master to trigger a backend build. We solved @hourmarks issue by triggering a backend deployment from the CLI by making a superficial change in the schema.graphql (put a space in and then do an `amplify push`).

**Closed by swaminator** 2019-08-22 17:46 UTC
Labels: backend, bug

**Comment by houmark** [comment] 2019-08-22 21:15
Yeah, that was the solution in my case, but it points to some kind of bug in the `amplify codegen` when run in the CLI manually as it was not updating the `nextToken` correctly. If this was only due to version differences, then the Console should have corrected it when I did later deployments using the Console with the same latest version as the CLI.

This points to a bigger issue where you cannot trust to use the Console only if you have major changes because the Console will not do the same codegen work as the CLI will when doing `amplify push`. This means merging from for example `develop` into `master` which I believe is a common and normal practice can create issues in some situations and the result is more or less silent. The solution seems to be something like that the Console would somehow auto-detect that it would need to abort due to required codegen changes or automatically do them if need to, but I do not have enough insight into this.

Until something has been improved on that, I will probably sneak in a manual `amplify push` on my prod environment when I have major changes and I now know what can solve a broken production setup in the future. To do the CLI push and ensure it's done safely with other side effects it's probably best to have a clean git state and then do `amplify env pull --restore` before the `amplify push`.

Thanks again for the help @swaminator — I do hope that my experience puts some focus on how to solve this in a better way in the future.

**Comment by walter-scott** [comment] 2019-08-24 04:58
@houmark what would you say is the most ideal workflow then when using a develop and a prod branch and environment in regards to using the console with the cli? 

I need to have my app ready for users on Monday and today I had to create an entirely  new branch and environment for Develop and production because the others randomly broke the day before yesterday when building through the console. I built these two new ones completely through the console (as in just pushing to github and letting the console create all the resources), aside from the initial `amplify init`. It seemed like that might work but then I realized that my elastic search is throwing the Int problem you mentioned above in addition to the fact that I cannot find a way pull the resources down locally for testing (`amplify env pull —restore` works for the most part but throws an error), so I am back to looking for another potential solution. 

I’m past the point of trying to fix the problems, they all make no sense. I just need a structure and workflow that works so my users can start signing up on Monday and the stack they exist on isn’t at a risk of going up in flames and importantly, actually works. Or at least is more stable than what I have now.

Any information will help immensely and is appreciated. If you would like to contact me directly at mail.wscott@gmail.com you can.

**Comment by houmark** [comment] 2019-08-24 08:13
@walter-scott I honestly cannot tell you. Mixing them can lead to "side effects" or weird issues, but as a general rule, you should be able to make a simple change (even just an empty line in schema.json) and do a CLI `amplify push` and that should normally fix anything "broken" from having used mainly the Console.

As far as I understand, the Console is not running `amplify codegen` as a part of the build process (and this is not a bug, this is by current design I was told). And running `amplify codegen` in the CLI is not the solution, because it will use the current cloud configuration to update your queries.js, mutations.js etc.

But when you do `amplify push` in the CLI it will run `amplify codegen` AFTER the cloud has been updated and your queries.js should then get updated accordingly.

So if you have major changes, use the CLI as it will "do stuff" the Console will not. To be safe, have a clean git before doing so and run `amplify env pull --restore` before doing the CLI push. If you get errors there, then you may have unrelated issues and that I cannot help you with, unfortunately.

If you are not too concerned about the added cost (Elasticsearch is especially costly here, ping AWS devs, please make it possible to configure a smaller EC2 instance for Elasticsearch for dev/testing as requested in aws-amplify/amplify-cli#1819), I would recommend adding a third environment in the mix, so you have dev/develop, prod/master and maybe staging/staging, which you treat the same way as prod/master by Git merging and mainly using the Console for deployments. That way if you break something, it happens outside of production and you can play with fixing it in the CLI without worrying about your production breaking.
