### ISSUE TITLE
Console build is failing - auth headless init missing inputParams

### ISSUE THREAD

**Issue by Jordan-SportX** [aws-amplify/amplify-console#243] opened 2019-11-14 06:49 UTC
**Describe the bug**
Hi,

Our backend builds are failing with error message:
`Error: auth headless init is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool`

We are using amplify cli 3.17.0 and react for the front end.
This is the build log: 
```
# Starting phase: build
2019-11-14T06:35:53.366Z [INFO]: # Executing command: amplifyPush --simple
2019-11-14T06:35:53.369Z [INFO]: # Getting Amplify CLI Cloud-Formation stack info from environment cache
2019-11-14T06:35:53.425Z [INFO]: # Start initializing Amplify environment: dev
2019-11-14T06:35:53.427Z [INFO]: # Initializing new Amplify environment: dev (amplify init)
2019-11-14T06:35:54.284Z [INFO]: Scanning for plugins...
2019-11-14T06:35:59.781Z [INFO]: Plugin scan successful
2019-11-14T06:35:59.803Z [INFO]: Note: It is recommended to run this command from the root of your app directory
2019-11-14T06:35:59.809Z [INFO]: For more information on AWS Profiles, see:
                                 https://docs.aws.amazon.com/cli/latest/userguide/cli-multiple-profiles.html
2019-11-14T06:35:59.815Z [WARNING]: - Initializing your environment: dev
2019-11-14T06:36:00.681Z [WARNING]: ✔ Initialized provider successfully.
2019-11-14T06:36:00.763Z [WARNING]: ✖ There was an error initializing your environment.
2019-11-14T06:36:00.763Z [INFO]: init failed
2019-11-14T06:36:00.765Z [INFO]: Error: auth headless init is missing the following inputParams facebookAppIdUserPool, facebookAppSecretUserPool, googleAppIdUserPool, googleAppSecretUserPool
                                 at updateConfigOnEnvInit (/root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/provider-utils/awscloudformation/index.js:367:15)
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/amplify-category-auth/index.js:213:28
                                 at /root/.nvm/versions/node/v10.16.0/lib/node_modules/@aws-amplify/cli/node_modules/promise-sequential/index.js:16:18
                                 at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-14T06:36:00.810Z [ERROR]: !!! Build failed
2019-11-14T06:36:00.810Z [ERROR]: !!! Non-Zero Exit Code detected
2019-11-14T06:36:00.811Z [INFO]: # Starting environment caching...
2019-11-14T06:36:00.811Z [INFO]: # Environment caching completed
Terminating logging...
```

We're not sure what's causing the issue, thanks!

**Comment by swaminator** [comment] 2019-11-14 17:36
@Jordan-SportX we are aware of this issue and will work on a fix soon. As a workaround, you can follow these instructions: https://github.com/aws-amplify/amplify-console/issues/206#issuecomment-552548466

**Comment by Jordan-SportX** [comment] 2019-11-15 01:53
@swaminator Thank you for the quick response. We just added the workaround bash script and all seems to work :)

This seems a little unsafe since we are committing our app secrets to the repo. 

Can we leave this issue open until the problem is fixed on your end? Thanks again

**Comment by Joycehao19** [comment] 2019-11-20 23:30
Closing as duplicate of #206. Please follow that thread for updates.

**Closed by Joycehao19** 2019-11-20 23:30 UTC
Labels: backend, bug, duplicate
