### ISSUE TITLE
Domain activation is Failed - [BRIEF DESCRIPTION]

### ISSUE THREAD

**Issue by drumcircle** [aws-amplify/amplify-console#2025] opened 2021-07-02 15:24 UTC
**App Id**: d2i8chyssopb54
**Region**: us-east-2
**Step**: Domain activation
**Status**: Failed

>**Note**: Do not include information that is sensitive in nature such as your domain name, company etc.

**Issue/question**
Please help me figure out what is wrong

**Error message**
Error message: One or more aliases specified for the distribution includes an incorrectly configured DNS record that points to another CloudFront distribution. You must update the DNS record to correct the problem. For more information, see https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/CNAMEs.html#alternate-domain-names-restrictions

**Comment by nimacks** [comment] 2021-08-23 17:07
Duplicate of #2026

**Closed by nimacks** 2021-08-23 17:07 UTC
Labels: custom-domain
